import assert from 'node:assert/strict';
import {newProfile,stats} from '../lib/rpg/model';
import {upgrade} from '../lib/rpg/immortal';
import {advanceMeridian,meridianCost,totalMeridians,meridianBonuses,MERIDIANS} from '../lib/rpg/meridians';
import {codexEntries,CODEX_CATEGORIES,normalizeCodexText} from '../lib/rpg/encyclopedia';
assert.equal(normalizeCodexText('Hồi Linh Đan'),'hoi linh dan');assert.equal(normalizeCodexText('ĐỘNG KHIẾU'),'dong khieu');
const p=newProfile();assert.equal(totalMeridians(p),0);assert.equal(p.meridianRoute,'none');
let before=JSON.stringify(p);assert.equal(advanceMeridian(p,'spoofed').ok,false);assert.equal(JSON.stringify(p),before);
p.meridianXp=100;p.star=1;before=JSON.stringify(p);assert.equal(advanceMeridian(p,'qihai').ok,false);assert.equal(JSON.stringify(p),before,'Blocked rank consumes nothing');
p.star=2;const mp=stats(p).mp,stone=p.coins.stone;assert.equal(advanceMeridian(p,'qihai').ok,true);assert.equal(p.meridians.qihai,1);assert.equal(p.meridianXp,76);assert.equal(p.coins.stone,stone-10);assert.equal(stats(p).mp,mp+8);
before=JSON.stringify(p);assert.equal(advanceMeridian(p,'qihai').ok,false);assert.equal(JSON.stringify(p),before,'Second node requires higher realm');
p.realm=44;p.coins.stone=0;before=JSON.stringify(p);assert.equal(advanceMeridian(p,'mind').ok,false);assert.equal(JSON.stringify(p),before,'Missing currency consumes nothing');
p.coins.stone=999999;p.materials.essence=99999;p.meridianXp=999999;for(const m of MERIDIANS)while(p.meridians[m.id]<18)assert.equal(advanceMeridian(p,m.id).ok,true);
assert.equal(totalMeridians(p),108);assert.equal(advanceMeridian(p,'mind').ok,false);assert(meridianCost(6).essence>0);
p.meridianRoute='sword';assert.equal(meridianBonuses(p).attackMult,1.03);p.meridianRoute='guardian';assert.equal(meridianBonuses(p).attackMult,1);assert.equal(meridianBonuses(p).hpMult,1.03);
const legacy=newProfile();delete (legacy as any).meridians;delete (legacy as any).meridianXp;delete (legacy as any).meridianRoute;upgrade(legacy);assert.equal(totalMeridians(legacy),0);assert.equal(legacy.meridianXp,0);
const entries=codexEntries(legacy);assert.equal(new Set(entries.map(e=>e.id)).size,entries.length);for(const c of CODEX_CATEGORIES)assert(entries.some(e=>e.category===c.id));assert.equal(entries.filter(e=>e.category==='npc').length,108);assert.equal(entries.filter(e=>e.category==='enemy').length,759);
assert.equal(entries.find(e=>e.id==='npc-0')!.known,false);legacy.talked.push(0);assert.equal(codexEntries(legacy).find(e=>e.id==='npc-0')!.known,true);
const secret=entries.find(e=>e.id==='s-cloud')!;assert(!secret.description.includes('Tàn niệm'),'Hidden lore remains unrevealed until discovery');legacy.secretsFound.push('s-cloud');assert(codexEntries(legacy).find(e=>e.id==='s-cloud')!.description.includes('Tàn niệm'));
console.log('Meridian/codex passed: atomic costs, rank and resource gates, 108-node cap, stat effects, exclusive routes, legacy upgrade, eight categories, unique IDs, verification and hidden lore.');
