import assert from 'node:assert/strict';
import {STORY_IDS,QUESTS,questUnlocked,NPCS,npcPosition} from '../lib/rpg/catalog';
import {newProfile,enemiesFor,questProgress,resourceNodes} from '../lib/rpg/model';
const p=newProfile();
assert.equal(enemiesFor(p).length,0,'New cultivators begin in a peaceful map');
for(let i=0;i<STORY_IDS.length;i++){
 const q=QUESTS.find(q=>q.id===STORY_IDS[i])!;
 assert.equal(questUnlocked(p.claimed,q),i===0,'Later chapters require their predecessor');
 assert.equal(q.hidden,false,'Story chapters can always be found in the journal');
}
p.claimed=STORY_IDS.slice(0,3);
assert.deepEqual(enemiesFor(p).map(e=>e.index),[0,1,2]);
p.claimed.push(STORY_IDS[3]);
assert.equal(enemiesFor(p).filter(e=>e.boss).length,1);
p.claimed.push(STORY_IDS[4]);assert.equal(enemiesFor(p).length,14);
p.claimed=[];p.dungeon={mapId:0,wave:1,kills:0,enteredAt:Date.now()};assert.equal(enemiesFor(p).length,14,'Dungeon combat remains available');
p.dungeon=null;p.mapId=1;assert.equal(enemiesFor(p).length,14,'Other maps retain their enemies');
p.gathered['0:herb']=3;assert.equal(questProgress(p,QUESTS.find(q=>q.id===STORY_IDS[1])!),3);
assert.notDeepEqual(npcPosition(NPCS[0]),npcPosition(NPCS[1]));
assert.equal(resourceNodes(0)[0].label,'Thanh Tâm Thảo');
console.log('Opening story: peaceful spawn, chapter prerequisites, enemy unlocks, legacy maps, dungeon, gathering and NPC positions passed.');
assert.equal(p.storyRituals?.length,0);
const fresh=newProfile();assert.equal(fresh.mapId,0);assert.equal(fresh.accepted[0],STORY_IDS[0]);assert.equal(fresh.trackedQuestId,STORY_IDS[0]);assert.equal(STORY_IDS.length,8);
for(const id of STORY_IDS.slice(5))assert(QUESTS.some(q=>q.id===id),'Three authored continuation quests exist');
const seal=QUESTS.find(q=>q.id==='story-seal')!;assert.equal(questProgress(fresh,seal),0);fresh.storyRituals=['0:seal'];assert.equal(questProgress(fresh,seal),1);assert(!questUnlocked(fresh.claimed,seal),'A ritual cannot bypass the predecessor');
assert(resourceNodes(0).some(n=>n.id===3&&n.type==='ritual'));assert(!resourceNodes(1).some(n=>n.type==='ritual'),'The ritual is local to the novice village');
const legacy=newProfile();delete legacy.storyRituals;assert.equal(questProgress(legacy,seal),0,'Older saves without ritual state remain valid');
const bamboo=QUESTS.find(q=>q.id==='story-bamboo')!;assert.equal(questProgress(fresh,bamboo),0);fresh.visited.push(1);assert.equal(questProgress(fresh,bamboo),1);
const message=QUESTS.find(q=>q.id==='story-message')!;assert.equal(questProgress(fresh,message),0);fresh.talked.push(2);assert.equal(questProgress(fresh,message),1);assert.equal(message.rewardBook,0);
console.log('Novice continuation: auto-accepted opening, three sequential quests, map-scoped ritual, legacy saves, travel and NPC objectives passed.');
