import assert from 'node:assert/strict';
import {TITLES,titleUnlocked,titleProgress,equippedTitle} from '../lib/rpg/titles';
import {newProfile,availableTitles,stats} from '../lib/rpg/model';
import {QUESTS} from '../lib/rpg/catalog';
import {RANKING_BOARDS,rankingTitleId} from '../lib/rpg/ranking-defs';
assert.equal(TITLES.length,152);assert.equal(new Set(TITLES.map(t=>t.id)).size,152);assert.equal(new Set(TITLES.map(t=>t.name)).size,152);
const p=newProfile();assert.equal(equippedTitle(p)?.id,'novice');assert(!availableTitles(p).some(t=>t.ranking));
for(const t of TITLES){assert(t.name&&t.color&&t.effect);assert(t.tier>=1&&t.tier<=5);if(t.ranking)continue;const q=newProfile();const value=t.requirement;switch(t.type){case 'kill':q.kills=value;break;case 'boss':q.bosses=value;break;case 'visit':q.visited=Array.from({length:value},(_,i)=>i);assert(value<=54);break;case 'book':q.books=Array.from({length:value},(_,i)=>i);assert(value<=72);break;case 'realm':q.realm=value;assert(value<=44);break;case 'quest':q.questCount=value;assert(value<=QUESTS.length);break;case 'meditate':q.meditations=value;break;case 'secret':q.secretsFound=Array.from({length:value},(_,i)=>String(i));assert(value<=12);break;case 'raid':q.raidCompletions=value;break;case 'gather':q.gathered={'0:herb':value-1,'1:ore':1};break;case 'meridian':{let remaining=value;for(const id of Object.keys(q.meridians) as Array<keyof typeof q.meridians>){q.meridians[id]=Math.min(18,remaining);remaining-=q.meridians[id];}assert.equal(remaining,0);assert(value<=108);}break;}assert.equal(titleProgress(q,t.type),value);assert(titleUnlocked(q,t));}
for(const b of RANKING_BOARDS)for(let rank=1;rank<=3;rank++){const t=TITLES.find(t=>t.id===rankingTitleId(b.id,rank))!;assert.equal(t.bonus,0);assert(!titleUnlocked(p,t));p.rankingTitles=[t.id];assert(titleUnlocked(p,t));p.titleId=t.id;assert.equal(equippedTitle(p)?.id,t.id);p.rankingTitles=[];assert.equal(equippedTitle(p),undefined);}
p.titleId='hunter';assert.equal(equippedTitle(p),undefined);const before=stats(p).attack;p.kills=20;assert.equal(equippedTitle(p)?.id,'hunter');assert(stats(p).attack>before);p.kills=20000;const one=stats(p).attack;p.titleId='novice';assert(stats(p).attack<one); // Only equipped title contributes.
console.log('Titles passed: 152 unique titles, reachable goals, legacy IDs, equipped-only bonuses and all 24 revocable podium titles.');
