'use client';
import {useEffect,useRef,useState} from 'react';
import type {Act,GameData} from './game';
const channels=[{id:'all',name:'Tất cả'},{id:'world',name:'Thế giới'},{id:'nearby',name:'Gần đây'},{id:'party',name:'Tổ đội'},{id:'sect',name:'Tông môn'}];
export function ChatPanel({data,act,busy}:{data:GameData;act:Act;busy:boolean}){
 const [filter,setFilter]=useState('all'),[text,setText]=useState(''),[expanded,setExpanded]=useState(false),[emoji,setEmoji]=useState(false),[seen,setSeen]=useState<Record<string,number>>({}),box=useRef<HTMLDivElement>(null);
 useEffect(()=>{const ids=filter==='all'?channels.slice(1).map(c=>c.id):[filter];setSeen(old=>{const next={...old};for(const id of ids)next[id]=Math.max(old[id]||0,...data.messages.filter((m:any)=>m.channel===id||(id==='world'&&m.channel==='system')).map((m:any)=>m.id));return next;});},[filter,data.messages]);
 const unread=(id:string)=>data.messages.filter((m:any)=>(m.channel===id||(id==='world'&&m.channel==='system'))&&m.id>(seen[id]||0)).length;
 const messages=data.messages.filter((m:any)=>filter==='all'||m.channel===filter||(filter==='world'&&m.channel==='system'));
 useEffect(()=>{const b=box.current;if(b&&b.scrollHeight-b.scrollTop-b.clientHeight<100)b.scrollTop=b.scrollHeight;},[data.messages]);
 return <div className={'r-chat r-panel r-chat-new '+(expanded?'expanded':'')}><div className="r-chat-head"><div className="r-chat-tabs">{channels.map(c=><button className={filter===c.id?'active':''} key={c.id} onClick={()=>setFilter(c.id)}>{c.name}{unread(c.id)>0&&<sup>{unread(c.id)}</sup>}</button>)}</div><button type="button" aria-label={expanded?'Thu gọn trò chuyện':'Mở rộng trò chuyện'} onClick={()=>setExpanded(!expanded)}>{expanded?'−':'+'}</button></div><div className="r-chat-messages" ref={box}>{messages.length?messages.slice(expanded?-60:-5).map((m:any)=><p key={m.id}><time>{new Date(m.created_at).toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'})}</time> <span className="r-chat-channel">{channels.find(c=>c.id===m.channel)?.name||(m.channel==='system'?'Tiên báo':'')}</span> <b>{m.name}:</b> {m.body}</p>):<p className="r-muted">Chưa có tin nhắn trong kênh này.</p>}</div><form onSubmit={async e=>{e.preventDefault();if(text.trim()&&await act('chat',{message:text}))setText('');}}><select aria-label="Kênh gửi tin" value={data.profile.chatChannel} disabled={busy} onChange={e=>void act('chatChannel',{channel:e.target.value})}>{channels.slice(1).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input aria-label="Tin nhắn" placeholder="Nói với đạo hữu... (Enter gửi)" value={text} maxLength={200} onChange={e=>setText(e.target.value)}/><button type="button" aria-label="Biểu cảm" onClick={()=>setEmoji(!emoji)}>☺</button><button disabled={busy||!text.trim()} aria-label="Gửi tin nhắn">Gửi</button></form>{emoji&&<div className="r-chat-emoji">{['☯','✨','🙏','⚔️','🌸','❤️'].map(e=><button key={e} onClick={()=>{setText(t=>(t+e).slice(0,200));setEmoji(false);}}>{e}</button>)}</div>}</div>;
}
