'use client';
import {TitleRibbon} from './title-ribbon';
import {RANKING_BOARDS,rankingTitleId} from '@/lib/rpg/ranking-defs';
import {TITLES} from '@/lib/rpg/titles';
import {useState} from 'react';
import {SECRETS,secretProgress,secretKnown} from '@/lib/rpg/secrets';
import {DHARMAS} from '@/lib/rpg/immortal';
import {MAPS,REALMS} from '@/lib/rpg/catalog';
import {DharmaPreview} from './dharma-preview';
import type {Act,GameData} from './game';
export function SecretsPanel({data,act,busy}:{data:GameData;act:Act;busy:boolean}){
 const p=data.profile,[filter,setFilter]=useState('current'),list=SECRETS.filter(s=>filter==='all'||(filter==='found'?secretKnown(p,s.id):s.map===p.mapId));
 return <><div className="r-secret-heading"><span>THIÊN CƠ · KHÔNG PHỤ NGƯỜI HỮU DUYÊN</span><h2>Cơ duyên trong sơn hà</h2><p>{p.secretsFound.length}/{SECRETS.length} dấu tích đã giải mã · Phần thưởng nhận một lần, lưu cùng nhân vật.</p></div><nav className="r-settings-tabs">{[['current','Linh địa hiện tại'],['all','Tất cả manh mối'],['found','Đã khám phá']].map(([id,label])=><button key={id} className={'r-btn '+(filter===id?'gold':'')} onClick={()=>setFilter(id)}>{label}</button>)}</nav><div className="r-secret-grid">{list.map(s=>{const found=secretKnown(p,s.id),claimed=p.claimed.includes(s.id),d=DHARMAS.find(d=>d.quest===s.id);return <article key={s.id} className={'r-secret-card '+(found?'found':'')}><div className="r-secret-art">{d?<DharmaPreview id={d.id} size={90}/>:<span>道</span>}</div><div><small>{MAPS[s.map].name} · {REALMS[s.realm]}</small><h3>{found?s.name:'Dấu tích chưa giải mã'}</h3><p>{found?s.story:s.hint}</p><p className="r-muted">Dấu tích tại {s.x}, {s.y} · Tiến độ {Math.min(s.goal,secretProgress(p,s))}/{s.goal}</p><p className="r-secret-reward">{s.stone} linh thạch · {s.essence} tinh phách · {s.relics} cổ tịch{d&&<><br/>Bí truyền: {d.name}</>}</p><div className="r-actions">{claimed?<span className="r-badge">Đã lĩnh thưởng</span>:found?<button className="r-btn gold" disabled={busy} onClick={async()=>{if(!p.accepted.includes(s.id)&&!(await act('accept',{questId:s.id})))return;await act('claimQuest',{questId:s.id});}}>Nhận cơ duyên</button>:s.map!==p.mapId?<button className="r-btn" disabled={busy||p.realm<MAPS[s.map].minRealm||!!p.dungeon} onClick={()=>act('travel',{mapId:s.map})}>Đến linh địa</button>:<span className="r-badge">Bấm dấu ✦ trên map để khám phá</span>}</div></div></article>;})}</div>{!list.length&&<p className="r-note">Chưa có dấu tích trong nhóm này. Xem tất cả manh mối để tìm linh địa tiếp theo.</p>}</>;
}
export function RankingsPanel({data,act,busy}:{data:GameData;act:Act;busy:boolean}){
 const [kind,setKind]=useState('cultivation'),[page,setPage]=useState(0),rows=data.rankingsByBoard?.[kind]||[],board=RANKING_BOARDS.find(b=>b.id===kind)!,rank=data.personalRanks?.[kind],total=Math.max(1,Math.ceil(rows.length/10)),shown=rows.slice(Math.min(page,total-1)*10,Math.min(page,total-1)*10+10);
 return <><div className="r-board-title"><span>PHONG VÂN BẢNG</span><h2>Đồng đạo tranh phong</h2><p>Thứ hạng của bạn: <b>{rank??'—'}</b> · {kind==='cultivation'?'Cảnh giới → tinh → tu vi tích lũy':board.label}</p></div><div className="r-board-controls"><nav className="r-settings-tabs">{RANKING_BOARDS.map(({id,name:label})=><button key={id} className={'r-btn '+(kind===id?'gold':'')} onClick={()=>{setKind(id);setPage(0);}}>{label}</button>)}</nav><button className="r-btn" disabled={busy} onClick={()=>act('sync',{full:true})}>Làm mới</button></div><p className="r-note">Top 100 · Top 3 nhận danh hiệu riêng, có hiệu lực trong thời gian giữ hạng. Bảng chưa có thành tích sẽ để trống. Cập nhật {data.rankingsUpdatedAt?new Date(data.rankingsUpdatedAt).toLocaleTimeString('vi-VN'):''}. Thứ hạng cá nhân tính trên toàn bộ máy chủ.</p>{!shown.length&&<p className="r-note">Chưa có đạo hữu đạt thành tích ở bảng này.</p>}{shown.map((r:any)=><article key={r.rank} className={'r-board-row '+(r.me?'me':'')}><span className={'r-board-medal top-'+r.rank}>{r.rank<=3?['♛','✦','◇'][r.rank-1]:r.rank}</span><div><h3>{r.name}{r.me?' · Bạn':''}</h3>{r.rank<=3&&<TitleRibbon title={TITLES.find(t=>t.id===rankingTitleId(kind,r.rank))!}/>}<p>{REALMS[r.realm]} · {r.star} tinh</p>{r.me&&r.rank<=3&&<button className="r-btn" disabled={busy||data.profile.titleId===rankingTitleId(kind,r.rank)} onClick={()=>act('title',{titleId:rankingTitleId(kind,r.rank)})}>{data.profile.titleId===rankingTitleId(kind,r.rank)?'Đang đeo':'Trang bị danh hiệu top '+r.rank}</button>}</div><strong>{r.score.toLocaleString('vi-VN')}<small>{board.label}</small></strong></article>)}<div className="r-pagination"><button className="r-btn" disabled={page===0} onClick={()=>setPage(page-1)}>Trang trước</button><span>Trang {Math.min(page,total-1)+1}/{total}</span><button className="r-btn" disabled={page>=total-1} onClick={()=>setPage(page+1)}>Trang sau</button></div></>;
}
