'use client';
import {drawSpellVisual} from '@/lib/rpg/skill-art';
import {TITLES as TITLE_CATALOG,equippedTitle} from '@/lib/rpg/titles';
import {drawTitleEffect,drawTitleBanner} from '@/lib/rpg/title-art';
import type {Preferences} from './preferences';
import {drawDharma} from '@/lib/rpg/dharma-art';
import {useEffect,useRef,type MutableRefObject} from 'react';
import {drawNpcGesture} from '@/lib/rpg/starter-art';
import {drawActor,drawCompanion,drawEnemy,nameSeed} from '@/lib/rpg/pixels';
import {drawScenery} from '@/lib/rpg/scenery';
import {safePosition} from '@/lib/rpg/model';
import {npcPosition,ROOTS,TITLES} from '@/lib/rpg/catalog';
function drawResource(c:CanvasRenderingContext2D,x:number,y:number,type:string,time:number,id=0){
 c.save();c.translate(x,y);c.fillStyle='#101b1855';c.beginPath();c.ellipse(0,3,17,6,0,0,Math.PI*2);c.fill();
 if(type==='ritual'){c.strokeStyle='#a6e7d9';c.lineWidth=2;const a=time?time/800:0;c.rotate(a);c.beginPath();c.moveTo(0,-17);c.lineTo(11,0);c.lineTo(0,17);c.lineTo(-11,0);c.closePath();c.stroke();c.fillStyle='#8bdfc757';c.fill();}else if(type==='herb'){c.rotate(time?Math.sin(time/750+x)*.12:0);c.strokeStyle='#305840';c.lineWidth=3;c.beginPath();c.moveTo(0,1);c.quadraticCurveTo(-4,-18,2,-34);c.stroke();for(const [sx,sy,tilt] of [[-7,-18,-.6],[7,-26,.7],[-6,-9,-.5],[8,-13,.8]]){c.save();c.translate(sx,sy);c.rotate(tilt);c.fillStyle='#629e6e';c.beginPath();c.ellipse(0,0,8,3.5,0,0,Math.PI*2);c.fill();c.strokeStyle='#bedba0';c.lineWidth=.8;c.beginPath();c.moveTo(-6,0);c.lineTo(6,0);c.stroke();c.restore();}for(let i=0;i<5;i++){const a=i*Math.PI*2/5;c.fillStyle=i%2?'#b7a0d1':'#d2c4e2';c.beginPath();c.ellipse(2+Math.cos(a)*4,-35+Math.sin(a)*4,4,2.5,a,0,Math.PI*2);c.fill();}c.fillStyle='#ffe7a7';c.fillRect(0,-37,4,4);}
 else if(type==='secret'&&id===100){c.strokeStyle='#a48b58';c.lineWidth=3;c.beginPath();c.moveTo(-22,0);c.lineTo(-22,-43);c.lineTo(22,-43);c.lineTo(22,0);c.stroke();c.fillStyle='#836f43';c.beginPath();c.moveTo(-8,-37);c.quadraticCurveTo(-10,-24,-15,-14);c.lineTo(15,-14);c.quadraticCurveTo(10,-24,8,-37);c.closePath();c.fill();c.fillStyle='#d1b879';c.fillRect(-15,-16,30,3);c.fillStyle='#ebd79a';c.fillRect(-7,-32,3,10);c.strokeStyle='#caa469';c.lineWidth=1;c.beginPath();c.moveTo(0,-14);c.lineTo(time?Math.sin(time/550)*4:0,-4);c.stroke();}
 else if(type==='secret'&&id===101){c.fillStyle='#347e7875';c.beginPath();c.ellipse(0,0,29,11,0,0,Math.PI*2);c.fill();for(let i=0;i<7;i++){const a=i*Math.PI/6;c.fillStyle=i%2?'#dcb2c5':'#edd1d0';c.beginPath();c.ellipse(Math.cos(a)*9,-8+Math.sin(a)*3,9,4,-a,0,Math.PI*2);c.fill();}c.fillStyle='#edcd87';c.fillRect(-3,-12,6,5);}
 else if(type==='secret'&&id===102){c.translate(0,time?Math.sin(time/600)*3:0);c.fillStyle='#334f48';c.fillRect(-15,-4,30,8);c.fillStyle='#6ab6a8';c.beginPath();c.moveTo(0,-34);c.lineTo(11,-19);c.lineTo(0,-9);c.lineTo(-9,-21);c.closePath();c.fill();c.strokeStyle='#d1edde';c.lineWidth=1;c.stroke();c.fillStyle='#e5d6a2';c.fillRect(-1,-25,2,6);}
 else if(type==='ore'){c.fillStyle='#455c6a';c.fillRect(-14,-9,28,12);c.fillStyle='#78adbd';c.beginPath();c.moveTo(-9,0);c.lineTo(-5,-25);c.lineTo(3,-16);c.lineTo(8,-30);c.lineTo(14,-5);c.closePath();c.fill();c.fillStyle='#d1eeea';c.fillRect(-4,-20,2,13);c.fillRect(8,-24,2,14);}
 else{c.fillStyle='#444b49';c.fillRect(-14,-35,28,36);c.fillStyle='#879086';c.fillRect(-11,-32,22,28);c.fillStyle='#e4c887';c.font='20px serif';c.textAlign='center';c.fillText('道',0,-10);}
 c.restore();
}
export type Point={x:number;y:number};
export type SceneTarget={kind:'npc'|'resource'|'enemy'|'ground';id:string|number;x:number;y:number};
export function GameCanvas({navigate,dataRef,position,paused,target,effects,preferences,onSelect,onArrive}:{navigate:MutableRefObject<SceneTarget|null>;dataRef:MutableRefObject<any>;position:MutableRefObject<Point>;paused:boolean;target:MutableRefObject<string>;effects:MutableRefObject<any[]>;preferences:Preferences;onSelect:(t:SceneTarget)=>void;onArrive:(t:SceneTarget)=>void}){
 const ref=useRef<HTMLCanvasElement>(null),prefs=useRef(preferences),pause=useRef(paused),select=useRef(onSelect),arrive=useRef(onArrive);
 prefs.current=preferences;pause.current=paused;select.current=onSelect;arrive.current=onArrive;
 useEffect(()=>{const canvas=ref.current,ctx=canvas?.getContext('2d');if(!canvas||!ctx)return;let raf=0,last=0,width=1,height=1,transform={scale:1,x:0,y:0},facing='front',moving=false;const keys=new Set<string>(),images:Record<string,HTMLImageElement>={};for(const [key,src] of Object.entries({courtyard:'/rpg/courtyard.webp',lower:'/rpg/lower.webp',immortal:'/rpg/immortal.webp',divine:'/rpg/divine.webp'})){const img=new Image();img.src=src;images[key]=img;}
 const resize=()=>{const box=canvas.getBoundingClientRect();width=box.width;height=box.height;const dpr=Math.min(devicePixelRatio,2);canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);};const observer=new ResizeObserver(resize);observer.observe(canvas);resize();
 const label=(text:string,x:number,y:number,color='#ddd5b1',size=15)=>{ctx.font=`${size}px VT323, monospace`;ctx.textAlign='center';ctx.fillStyle='#080f13e0';const tw=ctx.measureText(text).width;ctx.fillRect(Math.round(x-tw/2-4),Math.round(y-size+1),Math.round(tw+8),size+3);ctx.fillStyle=color;ctx.fillText(text,Math.round(x),Math.round(y));};
 const click=(ev:PointerEvent)=>{if(pause.current)return;const d=dataRef.current;if(!d)return;const box=canvas.getBoundingClientRect();const x=(ev.clientX-box.left-transform.x)/transform.scale,y=(ev.clientY-box.top-transform.y)/transform.scale;let hit:SceneTarget|undefined;for(const n of d.npcs){const {x:nx,y:ny}=npcPosition(n);if(Math.hypot(x-nx,y-ny+28)<48)hit={kind:'npc',id:n.id,x:nx,y:ny};}for(const r of d.resources)if(Math.hypot(x-r.x,y-r.y)<32)hit={kind:'resource',id:r.id,x:r.x,y:r.y};for(const e of [...(d.party?.phase==='active'&&d.party.mapId===d.profile.mapId&&!d.profile.dungeon?[]:d.enemies),...d.worldBosses.filter((b:any)=>b.map===d.profile.mapId),...(d.party?.raid&&d.party.mapId===d.profile.mapId?[d.party.raid]:[])])if(e.hp>0&&Math.hypot(x-e.x,y-e.y+(e.worldBoss?90:e.boss?60:30))<(e.worldBoss?105:e.boss?70:42))hit={kind:'enemy',id:e.id,x:e.x,y:e.y};hit=hit||{kind:'ground',id:'',...safePosition(x,y)};navigate.current=hit;select.current(hit);};
 const down=(e:KeyboardEvent)=>{if((e.target as HTMLElement)?.closest('input,textarea,select,[role="dialog"]')||pause.current)return;const k=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright'].includes(k)){e.preventDefault();keys.add(k);navigate.current=null;}};const up=(e:KeyboardEvent)=>keys.delete(e.key.toLowerCase());const blur=()=>keys.clear();window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);canvas.addEventListener('pointerdown',click);
 const draw=(frameTime:number)=>{const time=prefs.current.motion?frameTime:0;const d=dataRef.current;const dt=Math.min(.05,(frameTime-last)/1000||0);last=frameTime;if(d){const p=d.profile,st=d.stats,pos=position.current;let vx=0,vy=0;moving=false;if(!pause.current&&p.hp>0){vx=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0);vy=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0);if(!vx&&!vy&&navigate.current){const n=navigate.current,dx=n.x-pos.x,dy=n.y-pos.y,dist=Math.hypot(dx,dy),stop=n.kind==='enemy'?150:n.kind==='npc'?100:n.kind==='resource'?65:5;if(dist>stop){vx=dx/dist;vy=dy/dist;}else{navigate.current=null;if(n.kind==='npc'||n.kind==='resource')arrive.current(n);}}if(vx||vy){const m=Math.hypot(vx,vy);Object.assign(pos,safePosition(pos.x+vx/m*st.speed*dt,pos.y+vy/m*st.speed*dt));moving=true;facing=Math.abs(vx)>Math.abs(vy)?(vx<0?'left':'right'):(vy<0?'back':'front');}}
 const dpr=Math.min(devicePixelRatio,2);ctx.setTransform(dpr,0,0,dpr,0,0);ctx.imageSmoothingEnabled=false;ctx.fillStyle='#0b1519';ctx.fillRect(0,0,width,height);const scale=width<650?Math.max(width/870,height/1050):Math.max(width/1536,height/1024);const cx=width<650?pos.x:790,cy=width<650?pos.y:560;transform={scale,x:width/2-cx*scale,y:(width<650&&height<730?height*.62:height/2)-cy*scale};ctx.translate(transform.x,transform.y);ctx.scale(scale,scale);const image=images[p.mapId===0?(p.dungeon?'courtyard':'lower'):['lower','immortal','divine'][d.map.world]];if(image?.complete&&image.naturalWidth)ctx.drawImage(image,0,0,1536,1024);
 // Each region has its own light, weather and hand-drawn ground details.
 const filters=['','#193d2430','#dac68215','#09123055','#94cbdc25','#8c331d30','#31551b20','#54466620','#d2e6ed25','#273f242e','#b99a5435','#12132250','#364f8230','#208c9520','#3018364a','#7f18302c','#22202025','#b8d1d921'];if(p.mapId){ctx.fillStyle=filters[p.mapId%18]||'#00000000';ctx.fillRect(0,0,1536,1024);for(let i=0;i<34;i++){const x=390+(i*137+d.map.seed)%820,y=365+(i*71+d.map.seed)%400;ctx.fillStyle=['#858272','#455943','#a39e8a','#6e7175'][i%4];ctx.fillRect(x,y,4+(i%3)*2,2);if([3,8,12,14].includes(p.mapId%18)){ctx.fillStyle=p.mapId%18===8?'#e3ecdf':'#9fc4d55a';ctx.fillRect((x+time*.018*(i%3+1))%1500,(y+time*.028)%980,2,4);}}}
 if(p.mapId!==0||!p.dungeon)drawScenery(ctx,p.mapId,time);
 for(const r of d.resources){drawResource(ctx,r.x,r.y,r.type,time,r.id);label(r.type==='secret'?'✦ Dấu tích':r.type==='hidden'?'? Bia cổ':r.label,r.x,r.y+20,r.type==='hidden'?'#e2c789':'#a7c0a9',15);}
 const entities:any[]=[];for(const n of d.npcs)entities.push({y:npcPosition(n).y,draw:()=>{const {x,y}=npcPosition(n);drawNpcGesture(ctx,x,y,time,n.role==='merchant');drawActor(ctx,x,y,time,{seed:n.appearance,npc:true,female:n.female,pose:n.pose},1.85);if(prefs.current.showNames)label(n.name,x,y-131,'#e6cd8a',17);label(n.role==='elder'?'Trưởng lão · Nhiệm vụ':'Đan sư · Tiên duyên',x,y-111,'#c5c8b2',14);}});
 for(const e of [...(d.party?.phase==='active'&&d.party.mapId===p.mapId&&!p.dungeon?[]:d.enemies),...d.worldBosses.filter((b:any)=>b.map===p.mapId),...(d.party?.raid&&d.party.mapId===p.mapId?[d.party.raid]:[])]){if(e.hp<=0)continue;entities.push({y:e.y,draw:()=>{if(target.current===e.id){ctx.strokeStyle='#e4cc7f';ctx.lineWidth=2;ctx.strokeRect(e.x-27,e.y-15,54,22);}drawEnemy(ctx,e.x,e.y,time,{kind:e.kind||0,appearance:e.appearance,boss:e.boss,worldBoss:e.worldBoss});const top=e.y-(e.worldBoss?210:e.boss?145:e.elite?88:78);if(prefs.current.showNames)label(e.name.split(' · ')[0],e.x,top,e.boss?'#ecb489':'#c7cab1',e.boss?17:14);const bw=e.boss?80:40;ctx.fillStyle='#182323';ctx.fillRect(e.x-bw/2,top+5,bw,4);ctx.fillStyle=e.boss?'#c3865c':'#85985e';ctx.fillRect(e.x-bw/2,top+5,bw*e.hp/e.maxHp,4);}});}
 for(const peer of d.peers)entities.push({y:peer.y,draw:()=>{const peerTitle=TITLE_CATALOG.find(t=>t.id===peer.titleId);if(peerTitle){drawTitleEffect(ctx,peer.x,peer.y,time,peerTitle,true);if(prefs.current.showNames)drawTitleBanner(ctx,peer.x,peer.y-106,time,peerTitle);}drawDharma(ctx,peer.x,peer.y,time,peer,true);drawActor(ctx,peer.x,peer.y,time,{seed:nameSeed(peer.name),classId:peer.classId,root:peer.root},1.5);label(peer.name,peer.x,peer.y-80,'#9ccbbf',16);}});
 entities.push({y:pos.y,draw:()=>{const title=equippedTitle(p);if(p.hp>0){drawDharma(ctx,pos.x,pos.y,time,p);if(title)drawTitleEffect(ctx,pos.x,pos.y,time,title);}if(p.mountId!==null)drawCompanion(ctx,pos.x,pos.y+6,time,40+p.mountId,true,moving);if(p.petId!==null)drawCompanion(ctx,pos.x-38,pos.y+18,time,p.petId,false,moving);if(p.hp<=0){ctx.globalAlpha=.35;}drawActor(ctx,pos.x,pos.y-(p.mountId!==null?13:0),time,{seed:nameSeed(p.name),classId:p.classId,root:p.root,facing:({front:0,back:3,left:2,right:1} as Record<string,number>)[facing],moving,attack:effects.current.some(e=>e.type==='spell'&&Date.now()-e.started<330)},2.05);ctx.globalAlpha=1;if(title&&prefs.current.showNames)drawTitleBanner(ctx,pos.x,pos.y-151,time,title);label(p.name,pos.x,pos.y-135,'#f3e3b7',20);ctx.strokeStyle=['#c6ac6c','#83aa75','#7cb8ca','#d98f69','#9c977c','#b3a0e5','#aed5e9','#9edac1'][p.root];ctx.lineWidth=1.5;const pulse=Math.sin(time/300)*3;ctx.beginPath();ctx.ellipse(pos.x,pos.y+2,25+pulse,11,0,0,Math.PI*2);ctx.stroke();}});
 entities.sort((a,b)=>a.y-b.y).forEach(e=>e.draw());const now=Date.now();effects.current=effects.current.filter(e=>now-e.started<1300);for(const e of effects.current){const age=(now-e.started)/1000;if(e.type==='damage'&&prefs.current.showDamage)label((e.crit?'✦ ':'')+e.damage,e.x,e.y-40-age*55,e.crit?'#f0cc72':'#ecded0',24);else if(prefs.current.motion&&e.type==='tribulation'){ctx.strokeStyle=e.success?'#b8e7d1':'#e3a487';ctx.lineWidth=4;for(let i=0;i<8;i++){const a=i*Math.PI/4+age,rr=45+age*90;ctx.strokeRect(pos.x+Math.cos(a)*rr-6,pos.y+Math.sin(a)*rr*.5-6,12,12);}ctx.fillStyle='#c1d9ef88';ctx.fillRect(pos.x-3,pos.y-200,6,180*Math.max(0,1-age));}else if(prefs.current.motion&&e.type==='ritual'){ctx.save();ctx.strokeStyle='#b2eedb';ctx.globalAlpha=Math.max(0,1-age/1.3);for(let i=0;i<3;i++){ctx.beginPath();ctx.ellipse(e.x,e.y,30+age*70+i*20,15+age*30+i*9,0,0,Math.PI*2);ctx.stroke();}ctx.fillStyle='#bbf7e36b';ctx.fillRect(e.x-6,e.y-150,12,150);ctx.restore();}else if(e.type==='spell'){drawSpellVisual(ctx,{...e,fromX:e.fromX??pos.x,fromY:e.fromY??pos.y,classId:e.classId??p.classId},age,!prefs.current.motion);}}
 if(p.dungeon){ctx.fillStyle='#26162b35';ctx.fillRect(0,0,1536,1024);}
 }raf=requestAnimationFrame(draw);};raf=requestAnimationFrame(draw);return()=>{cancelAnimationFrame(raf);observer.disconnect();window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);canvas.removeEventListener('pointerdown',click);};},[dataRef,position,target,effects]);
 return <canvas className="realm-canvas" ref={ref} aria-label="Thế giới tu tiên. Bấm nền đất để di chuyển; bấm NPC để trò chuyện, yêu thú để chọn mục tiêu."/>;
}
