'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {GameCanvas,type Point,type SceneTarget} from './game-canvas';
import {ActorPreview} from './actor-preview';
import {Panels,PANEL_NAMES,MENU,type PanelName} from './panels';
import * as Icons from '@/components/pixel-icons';
import {PaintIcon} from './paint-icon';
import {currentDharma} from '@/lib/rpg/immortal';
import {CURRENCIES,REALMS,ROOTS,CLASSES,QUESTS,TUTORIAL,WORLD_NAMES} from '@/lib/rpg/catalog';
import {SKILLS,CLASS_SKILLS,questProgress,type Profile} from '@/lib/rpg/model';
import {nameSeed} from '@/lib/rpg/pixels';
export type GameData={profile:Profile;stats:{attack:number;hp:number;mp:number;defense:number;crit:number;speed:number;power:number};[key:string]:any};
export function combatTargets(d:GameData){return d.party?.raid&&d.party.mapId===d.profile.mapId&&!d.profile.dungeon?[d.party.raid]:[...d.enemies,...d.worldBosses.filter((b:any)=>b.map===d.profile.mapId)];}
export type Act=(action:string,args?:Record<string,any>)=>Promise<boolean>;
export function PixelIcon({name='Sparkles',...props}:{name?:string;className?:string}){const painted=['Sword','Shield','Backpack','ScrollText','MapPin','Gem','Heart','Coins','BookOpen','Leaf','Flame','Snowflake','Zap','Swords','Users','Sparkles','Wind','Crosshair','CircleHelp'];if(painted.includes(name))return <PaintIcon name={name} {...props}/>;const Icon=(Icons as any)[name]||Icons.Sparkles;return <Icon {...props}/>;}
export function Meter({value,max,color='jade'}:{value:number;max:number;color?:string}){return <div className={'r-meter '+color}><i style={{width:Math.min(100,Math.max(0,value/max*100))+'%'}}/></div>;}
export function Money({currency,amount}:{currency:string;amount:number}){const c=CURRENCIES.find(x=>x.id===currency)||CURRENCIES[0];return <span className="r-money" style={{color:c.color}} title={c.name}><b><PaintIcon index={30+CURRENCIES.findIndex(x=>x.id===c.id)}/></b> {Math.floor(amount).toLocaleString('vi-VN')} <small>{c.name}</small></span>;}
export default function RpgGame(){
 const [data,setData]=useState<GameData|null>(null),[panel,setPanel]=useState<PanelName|null>(null),[npc,setNpc]=useState<number|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[auto,setAuto]=useState(false),[selected,setSelected]=useState(''),[chat,setChat]=useState(''),[chatOpen,setChatOpen]=useState(false),[sound,setSound]=useState(false),[tick,setTick]=useState(Date.now());
 const dataRef=useRef<any>(null),position=useRef<Point>({x:720,y:630}),busyRef=useRef(false),target=useRef(''),effects=useRef<any[]>([]),panelRef=useRef<PanelName|null>(null),noticeTimer=useRef<ReturnType<typeof setTimeout>|null>(null),autoRef=useRef(false),clockOffset=useRef(0),audio=useRef<AudioContext|null>(null),polls=useRef(0);
 panelRef.current=panel;autoRef.current=auto;
 const toast=useCallback((text:string)=>{setNotice(text);if(noticeTimer.current)clearTimeout(noticeTimer.current);noticeTimer.current=setTimeout(()=>setNotice(''),5000);},[]);
 const apply=useCallback((next:GameData,action='')=>{const prev=dataRef.current;next={...prev,...next};if(!prev||prev.profile.mapId!==next.profile.mapId||['travel','revive','dungeonLeave','partyEnter'].includes(action)){position.current={x:next.profile.x,y:next.profile.y};target.current='';setSelected('');}clockOffset.current=next.time-Date.now();dataRef.current=next;setData(next);if(next.notice&&action!=='sync')toast(next.notice);for(const hit of next.hits||[])effects.current.push({...hit,type:'damage',started:Date.now()});if(next.effect)effects.current.push({...next.effect,started:Date.now()});setError('');},[toast]);
 const act:Act=useCallback(async(action,args={})=>{if(action==='sync'&&busyRef.current)return false;const waitingUntil=Date.now()+8000;while(busyRef.current&&Date.now()<waitingUntil)await new Promise(resolve=>setTimeout(resolve,40));if(busyRef.current)return false;busyRef.current=true;if(action!=='sync')setBusy(true);if(action!=='sync'){const cooldown=(dataRef.current?.profile.cooldowns.action||0)-(Date.now()+clockOffset.current);if(cooldown>0)await new Promise(resolve=>setTimeout(resolve,cooldown+25));}try{const response=await fetch('/api/rpg',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...args,x:position.current.x,y:position.current.y})});const next:any=await response.json();if(!response.ok){if(action!=='sync')toast(next.error||'Thao tác chưa thành công.');if(response.status>=500)setError(next.error);return false;}apply(next,action);return true;}catch{setError('Mất kết nối. Hệ thống sẽ tự kết nối lại.');return false;}finally{busyRef.current=false;setBusy(false);}},[apply,toast]);
 useEffect(()=>{let cancelled=false;const load=async()=>{try{const r=await fetch('/api/rpg');const d:any=await r.json();if(!cancelled){if(!r.ok)setError(d.error);else{apply(d);if(new URLSearchParams(location.search).get('party'))setPanel('party');}}}catch{if(!cancelled)setError('Chưa kết nối được. Hãy thử tải lại.');}};load();return()=>{cancelled=true;};},[apply]);
 useEffect(()=>{const id=setInterval(()=>{setTick(Date.now()+clockOffset.current);if(dataRef.current&&!busyRef.current&&document.visibilityState==='visible')void act('sync',{full:++polls.current%8===0});},1400);return()=>clearInterval(id);},[act]);
 const attack=useCallback((skill:number)=>{const d=dataRef.current;if(!d)return;if(!target.current){const nearest=combatTargets(d).filter((e:any)=>e.hp>0).sort((a:any,b:any)=>Math.hypot(a.x-position.current.x,a.y-position.current.y)-Math.hypot(b.x-position.current.x,b.y-position.current.y))[0];if(nearest){target.current=nearest.id;setSelected(nearest.id);}}if(target.current)void act('attack',{target:target.current,skill});},[act]);
 useEffect(()=>{const id=setInterval(()=>{if(!autoRef.current||panelRef.current||busyRef.current)return;const d=dataRef.current;if(!d||d.profile.hp<=0)return;let enemy=combatTargets(d).find((e:any)=>e.id===target.current&&e.hp>0);if(!enemy){enemy=combatTargets(d).filter((e:any)=>e.hp>0&&Math.hypot(e.x-position.current.x,e.y-position.current.y)<195).sort((a:any,b:any)=>Math.hypot(a.x-position.current.x,a.y-position.current.y)-Math.hypot(b.x-position.current.x,b.y-position.current.y))[0];if(enemy){target.current=enemy.id;setSelected(enemy.id);}}if(!enemy)return;const now=Date.now()+clockOffset.current;let skill=-1;for(let i=3;i>=0;i--)if((d.profile.cooldowns['skill'+i]||0)<=now&&d.profile.mp>=SKILLS[i].cost&&Math.hypot(enemy.x-position.current.x,enemy.y-position.current.y)<SKILLS[i].range+10){skill=i;break;}if(skill>=0)void act('attack',{target:enemy.id,skill});},400);return()=>clearInterval(id);},[act]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.target as HTMLElement)?.closest('input,textarea,select,[role="dialog"]')||panelRef.current)return;if(/^[1-4]$/.test(e.key)){e.preventDefault();attack(Number(e.key)-1);}if(e.key==='5')void act('dharmaCast');if(e.key.toLowerCase()==='q')setAuto(x=>!x);if(e.key.toLowerCase()==='r')void act('potion');if(e.key.toLowerCase()==='b')setPanel('inventory');if(e.key.toLowerCase()==='m')setPanel('maps');};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[act,attack]);
 const choose=(t:SceneTarget)=>{if(t.kind==='enemy'){target.current=String(t.id);setSelected(String(t.id));}else if(t.kind==='ground'){target.current='';setSelected('');}};
 const arrive=async(t:SceneTarget)=>{if(t.kind==='npc'){if(await act('talk',{npcId:t.id})){setNpc(Number(t.id));setPanel('npc');}}else if(t.kind==='resource')void act('resource',{nodeId:t.id});};
 const beep=()=>{if(!sound)return;try{audio.current=audio.current||new AudioContext();const o=audio.current.createOscillator(),g=audio.current.createGain();o.type='triangle';o.frequency.value=420;g.gain.setValueAtTime(.04,audio.current.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.current.currentTime+.08);o.connect(g);g.connect(audio.current.destination);o.start();o.stop(audio.current.currentTime+.09);}catch{}};
 if(!data)return <main className="r-loading"><div className="r-logo">VÂN THIÊN KÝ</div><p>Đang mở cổng tiên giới...</p>{error&&<><p>{error}</p><button className="r-btn" onClick={()=>location.reload()}>Thử lại</button></>}<span>Tu tiên pixel · Tam giới</span></main>;
 const p=data.profile,st=data.stats,active=QUESTS.filter(q=>p.accepted.includes(q.id)).slice(0,2),nextTutorial=TUTORIAL.find(t=>!p.tutorial.includes(t.id)),enemy=[...data.enemies,...data.worldBosses,...(data.party?.raid?[data.party.raid]:[])].find(e=>e.id===selected&&e.hp>0),classDef=CLASSES.find(c=>c.id===p.classId)!,dharma=currentDharma(p);
 return <main className={'r-game '+(enemy?'has-target':'')} onClick={beep}>
  <GameCanvas dataRef={dataRef} position={position} paused={!!panel} target={target} effects={effects} onSelect={choose} onArrive={arrive}/>
  <header className="r-top"><div className="r-wallet">{CURRENCIES.map(c=><Money key={c.id} currency={c.id} amount={p.coins[c.id]}/>)}</div><div className="r-top-actions"><button title="Âm thanh" aria-label="Âm thanh" onClick={()=>setSound(!sound)}><PixelIcon name={sound?'Volume2':'VolumeX'}/></button><button title="Toàn màn hình" aria-label="Toàn màn hình" onClick={()=>{if(document.fullscreenElement)void document.exitFullscreen();else void document.documentElement.requestFullscreen().catch(()=>toast('Trình duyệt này chưa hỗ trợ toàn màn hình.'));}}><PixelIcon name="Maximize"/></button><button title="Hướng dẫn" aria-label="Hướng dẫn" onClick={()=>setPanel('tutorial')}><PixelIcon name="CircleHelp"/></button></div></header>
  <button className="r-player r-panel" onClick={()=>setPanel('character')}><div className="r-portrait"><ActorPreview size={76} spec={{seed:nameSeed(p.name),classId:p.classId,root:p.root}} animate={false}/><span>{p.realm+1}</span></div><div><strong>{p.name}</strong><p>{classDef.name} · {REALMS[p.realm]} {p.star} tinh</p><Meter value={p.hp} max={st.hp} color="red"/><div className="r-meter-label">Khí huyết {Math.ceil(p.hp)} / {st.hp}</div><Meter value={p.mp} max={st.mp} color="blue"/><Meter value={p.xp} max={data.nextXp} color="gold"/><div className="r-power">Lực chiến <b>{st.power.toLocaleString('vi-VN')}</b><span>{ROOTS[p.root]} linh căn</span></div></div></button>
  <div className="r-zone"><h1>{data.map.name}</h1><span>{WORLD_NAMES[data.map.world]} · {p.dungeon?`Cổ cảnh ${p.dungeon.wave}/3`:data.party?.phase==='active'?'Cổ cảnh tổ đội':'Linh địa bình hòa'}</span></div>
  <button className="r-minimap r-panel" onClick={()=>setPanel('maps')} aria-label="Mở bản đồ"><div className="r-mini-ground"><span>BẮC</span>{data.npcs.map((n:any)=><i key={'n'+n.id} className="npc" style={{left:'36%',top:n.role==='elder'?'51%':'69%'}}/>)}{data.enemies.filter((e:any)=>e.hp>0).map((e:any)=><i key={e.id} className={e.boss?'boss':'enemy'} style={{left:e.x/1536*100+'%',top:e.y/1024*100+'%'}}/>)}<i className="me" style={{left:position.current.x/1536*100+'%',top:position.current.y/1024*100+'%'}}/></div><div><b>{data.map.name}</b><p>{WORLD_NAMES[data.map.world]}</p><small>{Math.round(position.current.x)}, {Math.round(position.current.y)}</small><em>{data.online} đạo hữu online</em></div></button>
  <nav className="r-nav" aria-label="Chức năng">{[{id:'quests',icon:16,name:'Nhiệm vụ'},{id:'inventory',icon:17,name:'Hành trang'},{id:'character',icon:2,name:'Nhân vật'},{id:'dharma',icon:39,name:'Pháp thân'},{id:'cultivation',icon:28,name:'Cảnh giới'},{id:'party',icon:23,name:'Tổ đội'},{id:'library',icon:35,name:'Bí tịch'},{id:'alchemy',icon:20,name:'Luyện đan'},{id:'guilds',icon:22,name:'Tông môn'},{id:'daily',icon:16,name:'Ủy thác'},{id:'market',icon:30,name:'Chợ'},{id:'menu',icon:18,name:'Thiên thư'}].map(m=><button key={m.id} onClick={()=>setPanel(m.id as PanelName)}><PaintIcon index={m.icon}/><span>{m.name}</span></button>)}</nav>
  <div className="r-left-tools"><button onClick={()=>setPanel('party')}>☷ {data.party?data.party.name:'Lập tổ đội'} <span>{data.party?data.party.members.length+'/5':'Đồng đạo'}</span></button><button onClick={()=>setPanel('practice')}>☯ Đạo tâm <span>Luyện thể · Thần thức</span></button>{dharma&&<button onClick={()=>setPanel('dharma')} style={{color:dharma.color}}>✦ {dharma.name} <span>Tầng {p.dharmaLevel}</span></button>}</div>
  {data.party&&<div className="r-party-hud r-panel">{data.party.members.map((m:any)=><div key={m.key}><span className={m.online?'online':''}>{m.leader?'♛':'◇'}</span><b>{m.name}{m.me?' · Bạn':''}</b><small>{m.online?Math.ceil(m.hp)+' HP':'Ngoại tuyến'}</small></div>)}<button onClick={()=>setPanel('party')}>Tổ đội · {data.party.code}</button></div>}
  <aside className="r-journal r-panel"><div className="r-eyebrow">TIÊN LỘ <span>{p.questCount} đã hoàn thành</span></div>{active.length?active.map(q=><div key={q.id} className="r-hud-quest"><b>{q.name.split(' · ')[1]}</b><p>{q.description}</p><span>{Math.min(q.count,questProgress(p,q))}/{q.count}</span>{questProgress(p,q)>=q.count?<button className="r-link" onClick={()=>act('claimQuest',{questId:q.id})}>Nhận thưởng →</button>:<button className="r-link" onClick={()=>setPanel('quests')}>Theo dõi →</button>}</div>):<><h2>Khởi hành tiên lộ</h2><p>Gặp trưởng lão phía tây hoặc mở Nhật ký để nhận nhiệm vụ.</p><button className="r-link" onClick={()=>setPanel('quests')}>Mở nhật ký →</button></>}{nextTutorial&&<button className="r-guide-link" onClick={()=>setPanel('tutorial')}>✦ Tân thủ: {nextTutorial.name}</button>}</aside>
  {enemy&&<div className="r-target r-panel"><b>{enemy.name}</b><Meter value={enemy.hp} max={enemy.maxHp} color="red"/><small>{Math.ceil(enemy.hp)} / {enemy.maxHp}</small></div>}
  <div className={'r-chat r-panel '+(chatOpen?'expanded':'')}><div className="r-chat-head"><div className="r-chat-tabs">{[{id:'world',name:'Thế giới'},{id:'party',name:'Tổ đội'},{id:'sect',name:'Tông môn'}].map(c=><button className={p.chatChannel===c.id?'active':''} key={c.id} onClick={()=>{setChatOpen(true);void act('chatChannel',{channel:c.id});}}>{c.name}</button>)}</div><button aria-label="Thu gọn trò chuyện" onClick={()=>setChatOpen(!chatOpen)}>{chatOpen?'−':'+'}</button></div><div className="r-chat-messages">{!data.messages.length?<p className="r-muted">Linh giới yên tĩnh. Hãy chào các đạo hữu.</p>:data.messages.slice(-5).map((m:any)=><p key={m.id}><b>{m.name}:</b> {m.body}</p>)}</div><form onSubmit={async e=>{e.preventDefault();if(chat.trim()&&await act('chat',{message:chat}))setChat('');}}><input aria-label="Tin nhắn" placeholder="Nói với đạo hữu..." value={chat} onChange={e=>setChat(e.target.value)} maxLength={200}/><button aria-label="Gửi tin nhắn" disabled={busy||!chat.trim()}><PixelIcon name="Send"/></button></form></div>
  <div className="r-combat"><div className="r-combat-tools"><button onClick={()=>act('cultivate')} disabled={busy||p.x>=740}>☯ Điều tức</button><button onClick={()=>setPanel('dungeons')}>⌘ Phụ bản</button><button onClick={()=>setPanel('events')}>✦ Hoạt động</button></div><div className="r-hotbar r-panel">{SKILLS.map((s,i)=>{const cd=Math.max(0,(p.cooldowns['skill'+i]||0)-tick);return <button key={i} className={'r-skill s'+i} title={CLASS_SKILLS[p.classId][i]+` · ${s.cost} linh lực · hồi ${s.cd/1000}s`} disabled={busy||p.hp<=0||cd>0||p.mp<s.cost} onClick={()=>attack(i)}><span className="r-skill-icon"><PaintIcon index={24+i}/>{cd>0&&<i>{Math.ceil(cd/1000)}</i>}</span><span>{CLASS_SKILLS[p.classId][i]}</span><kbd>{i+1}</kbd></button>;})}<button className={'r-skill r-dharma-skill '+((p.cooldowns.dharmaActive||0)>tick?'awakened':'')} disabled={busy||!dharma||p.hp<=0||p.mp<30||(p.cooldowns.dharma||0)>tick} title={dharma?dharma.name+' · tăng 25% sát thương trong 8 giây':'Mở pháp thân tại Trúc Cơ'} onClick={()=>act('dharmaCast')}><span className="r-skill-icon"><PaintIcon index={39}/>{(p.cooldowns.dharma||0)>tick&&<i>{Math.ceil((p.cooldowns.dharma-tick)/1000)}</i>}</span><span>Pháp thân</span><kbd>5</kbd></button><button className={'r-auto '+(auto?'active':'')} onClick={()=>setAuto(!auto)}><PixelIcon name={auto?'Pause':'Play'}/><span>{auto?'Đang tự chiến':'Tự chiến'}</span><kbd>Q</kbd></button><button className="r-potion" title="Hồi khí huyết và linh lực" onClick={()=>act('potion')} disabled={busy||!p.potions||p.hp<=0}><PaintIcon index={20}/><b>{p.potions}</b><span>Linh đan</span><kbd>R</kbd></button></div></div>
  <footer className="r-foot"><strong>VÂN THIÊN KÝ</strong><span>WASD / Bấm đất: di chuyển · 1–4: xuất chiêu</span><span>{p.dungeon?'Cổ cảnh riêng':'Vùng an toàn phía tây · Yêu thú phía đông'}</span><button onClick={()=>setPanel('codex')}>Vạn vật đồ giám</button></footer>
  {notice&&<div role="status" className="r-toast">{notice}</div>}{error&&<div role="alert" className="r-connection">{error}</div>}{p.hp<=0&&<div className="r-dead r-panel"><h2>Thân vẫn, đạo tâm còn</h2><p>Hồi sinh tại vùng an toàn để tiếp tục tiên lộ.</p><button className="r-btn gold" onClick={()=>{setAuto(false);void act('revive');}}>Hồi sinh</button></div>}
  <Dialog open={!!panel} onOpenChange={open=>{if(!open)setPanel(null);}}><DialogContent className="r-dialog"><DialogTitle className="r-dialog-title">{panel?PANEL_NAMES[panel]:''}</DialogTitle><DialogDescription className="r-dialog-description">{p.name} · {REALMS[p.realm]} {p.star} tinh · Lực chiến {st.power.toLocaleString('vi-VN')}</DialogDescription><div className="r-dialog-wallet">{CURRENCIES.map(c=><Money key={c.id} currency={c.id} amount={p.coins[c.id]}/>)}</div>{panel&&<Panels panel={panel} data={data} act={act} busy={busy} open={setPanel} npc={npc} tick={tick}/>}</DialogContent></Dialog>
 </main>;
}
