'use client';
import {useContext,useState,type ReactNode} from 'react';
import {QUESTS,STORY_IDS,MAPS,questUnlocked,type QuestDef} from '@/lib/rpg/catalog';
import {questProgress} from '@/lib/rpg/model';
import {Meter,type GameData,type Act} from './game';
import {NavigationContext} from './navigation';
import {questDestination} from './quest-target';
export function QuestJournal({data,act,busy,side,events,daily,open}:{data:GameData;act:Act;busy:boolean;side:ReactNode;events:ReactNode;daily:ReactNode;open:()=>void}){
 const [tab,setTab]=useState('story'),[selected,setSelected]=useState(STORY_IDS.find(id=>!data.profile.claimed.includes(id))||STORY_IDS[0]),navigate=useContext(NavigationContext),p=data.profile,q=QUESTS.find(q=>q.id===selected)!,progress=questProgress(p,q),done=p.claimed.includes(q.id),accepted=p.accepted.includes(q.id),completed=STORY_IDS.filter(id=>p.claimed.includes(id)).length,target=questDestination(data,q);
 return <><nav className="r-dialog-tabs" aria-label="Nhóm nhiệm vụ">{[['story','Chính tuyến'],['side','Phụ tuyến'],['events','Sự kiện'],['daily','Hằng ngày']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</nav>{tab==='side'?side:tab==='events'?events:tab==='daily'?daily:<div className="r-quest-journal-layout"><aside className="r-quest-chapter"><span className="r-eyebrow">CHƯƠNG 01 · THANH VÂN MÔN</span><h3>Mảnh ngọc và lời thề</h3><p>{completed}/{STORY_IDS.length} bước hoàn thành</p><Meter value={completed} max={STORY_IDS.length}/><p>Một niệm cứu người, một kiếm hộ sơn. Khám phá thân thế qua phong ấn Cửu U.</p></aside><section className="r-quest-chapter-detail"><span className="r-eyebrow">{done?'ĐÃ HOÀN THÀNH':accepted?'ĐANG LÀM':'TIÊN LỘ ĐANG CHỜ'}</span><h2>{q.name.split(' · ')[1]}</h2><p>{q.description}</p><Meter value={Math.min(progress,q.count)} max={q.count}/><p>{Math.min(progress,q.count)}/{q.count} mục tiêu · {MAPS[q.map].name}</p><ol className="r-quest-steps">{STORY_IDS.map((id,i)=>{const step=QUESTS.find(q=>q.id===id)!,cleared=p.claimed.includes(id),unlocked=questUnlocked(p.claimed,step);return <li key={id}><button className={selected===id?'active':''} onClick={()=>setSelected(id)}><span>{i+1}</span><b>{step.name.split(' · ')[1]}</b><small>{cleared?'✓ Xong':!unlocked?'Chưa mở':p.accepted.includes(id)?'Đang làm':'Có thể nhận'}</small></button></li>;})}</ol><div className="r-quest-reward"><span className="r-eyebrow">PHẦN THƯỞNG</span><p>✦ Tu vi +{q.rewardXp}　◈ Linh thạch +{q.rewardStone}　☯ Kinh nghiệm động khiếu +8</p><small>Phần thưởng chỉ nhận một lần khi đạt đủ mục tiêu.</small></div><div className="r-actions">{!done&&(!accepted?<button className="r-btn gold" disabled={busy||!questUnlocked(p.claimed,q)} onClick={()=>act('accept',{questId:q.id})}>Nhận nhiệm vụ</button>:<><button className="r-btn gold" disabled={busy||progress<q.count} onClick={async()=>{if(await act('claimQuest',{questId:q.id})){const next=STORY_IDS[STORY_IDS.indexOf(q.id)+1];if(next)setSelected(next);}}}>Nhận thưởng</button><button className="r-btn" disabled={busy} onClick={()=>act('trackQuest',{questId:p.trackedQuestId===q.id?null:q.id})}>{p.trackedQuestId===q.id?'Bỏ theo dõi':'Theo dõi nhiệm vụ'}</button></>)}<button className="r-btn" onClick={open}>Xem bản đồ</button>{target&&accepted&&progress<q.count&&<button className="r-btn gold" onClick={()=>navigate(target)}>Tự tìm đường · {Math.round(Math.hypot(target.x-p.x,target.y-p.y))} bước</button>}</div>{!target&&!done&&progress<q.count&&<p className="r-note">Mục tiêu chưa xuất hiện tại linh địa hiện tại. Hoàn thành bước trước hoặc chờ yêu thú hồi sinh.</p>}</section></div>}</>;
}
