'use client';
import {useContext,useRef,useState,type ReactNode} from 'react';
import {npcPosition} from '@/lib/rpg/catalog';
import {NavigationContext} from './navigation';
import type {GameData} from './game';
export function RegionMap({data,world}:{data:GameData;world:ReactNode}){
 const [tab,setTab]=useState('region'),[zoom,setZoom]=useState(1),[selected,setSelected]=useState<any>(null),viewport=useRef<HTMLDivElement>(null),navigate=useContext(NavigationContext);
 const p=data.profile,markers=[...data.npcs.map((n:any)=>({...n,...npcPosition(n),kind:'npc',symbol:'◆'})),...data.resources.map((r:any)=>({...r,name:r.label||(r.type==='herb'?'Linh thảo':r.type==='ore'?'Linh khoáng':r.type==='secret'?'Dấu vết cơ duyên':'Bia cổ'),kind:'resource',symbol:'✦'})),...(data.party?.phase==='active'&&data.party.mapId===p.mapId&&!p.dungeon?[]:data.enemies).filter((e:any)=>e.hp>0).map((e:any)=>({...e,kind:'enemy',symbol:e.boss?'♜':'●'})),...data.worldBosses.filter((e:any)=>e.map===p.mapId&&e.hp>0).map((e:any)=>({...e,kind:'enemy',symbol:'♜'})),...(data.party?.raid&&data.party.mapId===p.mapId?[{...data.party.raid,kind:'enemy',symbol:'♜'}]:[]),...data.peers.map((e:any)=>({...e,kind:'peer',symbol:'◇'})),{id:'me',kind:'me',symbol:'▲',name:p.name,x:p.x,y:p.y}];
 function center(point:any){const v=viewport.current;if(v)v.scrollTo({left:point.x/1536*v.scrollWidth-v.clientWidth/2,top:point.y/1024*v.scrollHeight-v.clientHeight/2,behavior:'smooth'});}
 return <><div className="r-actions"><button className="r-btn" onClick={()=>setTab('world')}>Giang hồ</button><button className="r-btn" onClick={()=>setTab('region')}>Khu vực · {data.map.name}</button></div>{tab==='world'?world:<div className="r-region"><section><div className="r-actions"><button className="r-btn" aria-label="Thu nhỏ bản đồ" onClick={()=>setZoom(z=>Math.max(1,z-.25))}>−</button><button className="r-btn" aria-label="Phóng to bản đồ" onClick={()=>setZoom(z=>Math.min(3,z+.25))}>+</button><button className="r-btn" onClick={()=>center(p)}>Vị trí tôi</button><button className="r-btn" disabled={!selected} onClick={()=>center(selected)}>Mục tiêu</button><button className="r-btn" onClick={()=>{setZoom(1);viewport.current?.scrollTo(0,0);}}>Toàn cảnh</button></div><div className="r-region-scroll" ref={viewport}><div className="r-region-board" style={{width:zoom*100+'%',backgroundImage:`url(/rpg/${p.mapId===0?'lower':['lower','immortal','divine'][data.map.world]}.webp)`}}>{markers.map((m:any)=><button key={m.kind+m.id} className={'r-region-marker '+m.kind+(selected?.kind===m.kind&&selected?.id===m.id?' selected':'')} style={{left:m.x/1536*100+'%',top:m.y/1024*100+'%'}} title={m.name} aria-label={m.name} onClick={()=>setSelected(m)}>{m.symbol}<small>{m.kind==='npc'||m.kind==='me'?m.name:''}</small></button>)}</div></div><p className="r-note">▲ Bạn · ◆ NPC · ● Yêu thú · ♜ Boss · ✦ Tài nguyên / cơ duyên · ◇ Đạo hữu</p></section><aside><span className="r-eyebrow">VỊ TRÍ</span><h3>{Math.round(p.x)}, {Math.round(p.y)}</h3><p>{p.dungeon?'Cổ cảnh riêng':p.x<740?'Đang trong vùng an toàn':'Đang ở vùng yêu thú'}</p><h3>{selected?.name||'Chọn một dấu trên bản đồ'}</h3>{selected&&<><p>{Math.round(selected.x)}, {Math.round(selected.y)}</p>{selected.hp!==undefined&&<p>Khí huyết {Math.ceil(selected.hp)}</p>}{['npc','resource','enemy'].includes(selected.kind)&&<button className="r-btn gold" onClick={()=>navigate(selected)}>Đi tới mục tiêu</button>}</>}<h3>Cổ cảnh</h3><p>{p.dungeon?'Đang ở đợt '+p.dungeon.wave+'/3':'Ba cửa vấn đạo · đã vượt '+(p.cleared[String(p.mapId)]||0)+' lần'}</p><h3>Đạo hữu quanh đây · {data.peers.length}</h3>{data.peers.map((peer:any)=><p key={peer.id}>{peer.name}</p>)}<p className="r-note">Các dấu yêu thú cập nhật theo tiến độ cốt truyện và trạng thái hồi sinh.</p></aside></div>}</>;
}
