'use client';
import {useContext,useEffect,useRef,useState} from 'react';
import {TITLES,TITLE_EFFECTS,TITLE_METRICS,titleProgress,titleUnlocked,type TitleDef} from '@/lib/rpg/titles';
import {drawTitleEffect,drawTitleBanner} from '@/lib/rpg/title-art';
import {drawActor,nameSeed} from '@/lib/rpg/pixels';
import {PreferencesContext} from './preferences';
import type {Act,GameData} from './game';
function TitlePreview({title,data}:{title:TitleDef;data:GameData}){
 const ref=useRef<HTMLCanvasElement>(null),motion=useContext(PreferencesContext).preferences.motion;
 useEffect(()=>{const canvas=ref.current,c=canvas?.getContext('2d');if(!canvas||!c)return;let frame=0;const paint=(t:number)=>{c.clearRect(0,0,320,240);drawTitleEffect(c,160,211,t,title);drawActor(c,160,207,t,{seed:nameSeed(data.profile.name),classId:data.profile.classId,root:data.profile.root},1.65);drawTitleBanner(c,160,60,t,title);if(motion)frame=requestAnimationFrame(paint);};const repaint=()=>paint(0);if(!motion)window.addEventListener('rpg-atlas-ready',repaint);paint(0);return()=>{cancelAnimationFrame(frame);window.removeEventListener('rpg-atlas-ready',repaint);};},[title.id,motion,data.profile.name,data.profile.classId,data.profile.root]);
 return <canvas ref={ref} width={320} height={240} className="r-title-preview" aria-label={'Xem hiệu ứng '+title.name}/>;
}
export function TitlePanel({data,act,busy}:{data:GameData;act:Act;busy:boolean}){
 const [search,setSearch]=useState(''),[group,setGroup]=useState('all'),[state,setState]=useState('all'),[selected,setSelected]=useState(data.profile.titleId),[page,setPage]=useState(0),p=data.profile;
 const normalize=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[đĐ]/g,'d').toLowerCase();
 const rows=TITLES.filter(t=>(group==='all'||t.group===group)&&normalize(t.name).includes(normalize(search))&&(state==='all'||titleUnlocked(p,t)===(state==='unlocked'))),total=Math.max(1,Math.ceil(rows.length/12)),title=TITLES.find(t=>t.id===selected)||TITLES[0],unlocked=titleUnlocked(p,title),owned=TITLES.filter(t=>titleUnlocked(p,t)).length;
 return <><div className="r-title-summary"><h2>Vạn danh tiên lộ · {TITLES.length}</h2><p>Đã mở {owned}/{TITLES.length} · Một danh hiệu trang bị có hiệu lực.</p></div><div className="r-title-filters"><input aria-label="Tìm danh hiệu" placeholder="Tìm danh hiệu..." value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}}/><select aria-label="Nhóm danh hiệu" value={group} onChange={e=>{setGroup(e.target.value);setPage(0);}}><option value="all">Mọi con đường</option>{[...new Set(TITLES.map(t=>t.group))].map(g=><option key={g}>{g}</option>)}</select><select aria-label="Trạng thái danh hiệu" value={state} onChange={e=>{setState(e.target.value);setPage(0);}}><option value="all">Tất cả</option><option value="unlocked">Đã mở</option><option value="locked">Chưa mở</option></select></div><div className="r-title-layout"><section><div className="r-title-list">{rows.slice(Math.min(page,total-1)*12,Math.min(page,total-1)*12+12).map(t=><button key={t.id} className={'r-title-choice '+(t.id===title.id?'selected':'')+(titleUnlocked(p,t)?' unlocked':'')} onClick={()=>setSelected(t.id)} style={{'--title-color':t.color} as React.CSSProperties}><span className="r-title-seal">{['◇','✦','❖','♛','☯'][t.tier-1]}</span><div><strong>{t.name}</strong><small>{p.titleId===t.id&&titleUnlocked(p,t)?'Đang đeo':titleUnlocked(p,t)?'Đã mở':t.ranking?'Top '+t.ranking.place+' · '+t.group:titleProgress(p,t.type)+'/'+t.requirement+' · '+TITLE_METRICS[t.type]}</small></div></button>)}</div>{!rows.length&&<p className="r-note">Không có danh hiệu phù hợp.</p>}<div className="r-pagination"><button className="r-btn" disabled={page===0} onClick={()=>setPage(n=>n-1)}>Trang trước</button><span>{Math.min(page,total-1)+1}/{total}</span><button className="r-btn" disabled={page>=total-1} onClick={()=>setPage(n=>n+1)}>Trang sau</button></div></section><aside className="r-title-details"><h3 style={{color:title.color}}>{title.name}</h3><TitlePreview title={title} data={data}/><p>{TITLE_EFFECTS[title.effect]} · Bậc {title.tier}/5</p><p>{title.ranking?'Danh hiệu vinh danh · Không cộng chỉ số':'Công cơ bản +'+title.bonus}</p><p>{title.ranking?'Giữ vị trí '+title.ranking.place+' trên bảng '+title.group.replace('Phong Vân · ','')+'. Danh hiệu tạm thời theo thứ hạng hiện tại.':TITLE_METRICS[title.type]+': '+Math.min(title.requirement,titleProgress(p,title.type))+'/'+title.requirement}</p><button className="r-btn gold" disabled={busy||!unlocked||p.titleId===title.id} onClick={()=>act('title',{titleId:title.id})}>{p.titleId===title.id&&unlocked?'Đang đeo':unlocked?'Trang bị danh hiệu':'Chưa đạt điều kiện'}</button></aside></div></>;
}
