'use client';
import {useRef,useState} from 'react';
import {MAPS,ENEMIES,NPCS,REALMS,WORLD_NAMES} from '@/lib/rpg/catalog';
import {PaintIcon} from './paint-icon';
import type {Act,GameData} from './game';
export function WorldAtlas({data,act,busy,close}:{data:GameData;act:Act;busy:boolean;close:()=>void}){
 const p=data.profile,[world,setWorld]=useState(data.map.world),[selected,setSelected]=useState(p.mapId),[search,setSearch]=useState(''),[zoom,setZoom]=useState(1),viewport=useRef<HTMLDivElement>(null);
 const places=MAPS.filter(m=>m.world===world),matches=places.filter(m=>!search||[m.name,...ENEMIES.filter(e=>e.map===m.id).map(e=>e.name)].some(name=>name.toLocaleLowerCase('vi').includes(search.toLocaleLowerCase('vi')))),map=MAPS[selected],monsters=map.id===p.mapId?data.enemies:ENEMIES.filter(e=>e.map===map.id),available=p.realm>=map.minRealm;
 function locate(){setWorld(data.map.world);setSelected(p.mapId);setSearch('');setZoom(1);viewport.current?.scrollTo(0,0);}
 return <><nav className="r-settings-tabs" aria-label="Cõi trên sơn hà đồ">{WORLD_NAMES.map((name,i)=><button key={name} className={'r-btn '+(world===i?'gold':'')} onClick={()=>{setWorld(i);setSelected(i*18);setSearch('');}}>{name}</button>)}</nav><div className="r-world-atlas"><section><div className="r-actions"><button className="r-btn" aria-label="Thu nhỏ giang hồ" onClick={()=>setZoom(z=>Math.max(1,z-.25))}>−</button><button className="r-btn" aria-label="Phóng to giang hồ" onClick={()=>setZoom(z=>Math.min(2,z+.25))}>+</button><button className="r-btn" onClick={()=>{setZoom(1);viewport.current?.scrollTo(0,0);}}>Toàn cảnh</button><button className="r-btn" onClick={locate}>Vị trí tôi</button></div><div className="r-atlas-scroll" ref={viewport}><div className="r-atlas-paper" style={{width:zoom*100+'%',backgroundImage:`linear-gradient(#d8c79299,#bba46d77),url(/rpg/${['lower','immortal','divine'][world]}.webp)`}}><span className="r-atlas-compass">北<br/>✥</span><div className="r-atlas-places">{places.map(m=><button aria-label={'Chọn linh địa '+m.name} aria-pressed={selected===m.id} key={m.id} className={(selected===m.id?'selected ':'')+(p.mapId===m.id?'current ':'')+(p.realm<m.minRealm?'locked ':'')+(!matches.includes(m)?'filtered':'')} onClick={()=>setSelected(m.id)}><PaintIcon index={m.dungeon?27:18}/><span><strong>{m.name}</strong><small>{REALMS[m.minRealm]}{p.mapId===m.id?' · Bạn ở đây':p.visited.includes(m.id)?' · Đã đến':''}</small></span></button>)}</div><span className="r-atlas-seal">山 河</span></div></div><p className="r-note">{places.length} linh địa · Đã đến {places.filter(m=>p.visited.includes(m.id)).length} nơi · Viền xanh: bạn ở đây · Viền đỏ: đang chọn</p></section><aside><input aria-label="Tìm địa danh hoặc quái" placeholder="Tìm địa danh hoặc quái…" value={search} onChange={e=>setSearch(e.target.value)}/><div className="r-atlas-results">{matches.map(m=><button key={m.id} className={selected===m.id?'selected':''} onClick={()=>setSelected(m.id)}>{m.name}</button>)}{!matches.length&&<p>Không tìm thấy linh địa.</p>}</div><h3>{map.name}</h3><p>{map.description}</p><p>Cần {REALMS[map.minRealm]} · {p.visited.includes(map.id)?'Đã đặt chân đến':'Chưa khám phá'}</p><h4>Đồng đạo tại linh địa</h4>{NPCS.filter(n=>n.map===map.id).map(n=><p key={n.id}>◆ {n.name}</p>)}<h4>Yêu thú và trấn thủ · {monsters.length}</h4><p>{[...new Set(monsters.map((e:{name:string})=>e.name))].slice(0,6).join(' · ')||'Linh địa đang yên bình.'}</p><button className="r-btn gold" disabled={busy||!available||map.id===p.mapId||!!p.dungeon||(p.cooldowns.travel||0)>data.time} onClick={async()=>{if(await act('travel',{mapId:map.id}))close();}}>{map.id===p.mapId?'Đang ở đây':!available?'Cảnh giới chưa đủ':'Qua cổng dịch chuyển'}</button></aside></div></>;
}
