import {requestOrigin,secureRequest} from '@/lib/request-origin';
import {ensurePlayable} from '@/lib/rpg/server-settings';
import {AdminError} from '@/lib/rpg/admin-auth';
import {db,session,actor,hydrate,save,GameError} from '@/lib/rpg/database';
import {act} from '@/lib/rpg/actions';
import {world} from '@/lib/rpg/world';
export const dynamic='force-dynamic';
const json=(value:unknown,status=200,cookie='')=>Response.json(value,{status,headers:{'Cache-Control':'no-store',...(cookie?{'Set-Cookie':cookie}:{})}});
export async function GET(req:Request){try{await ensurePlayable(req);const s=await session(req);return json(await world(s),200,s.cookie);}catch(e){if(e instanceof AdminError)return json({error:e.message},e.status);console.error('RPG load failure',e);return json({error:'Không tải được tiên giới. Hãy thử lại.'},503);}}
export async function POST(req:Request){let lockedId='';try{const origin=req.headers.get('origin');if(origin&&origin!==requestOrigin(req))return json({error:'Yêu cầu không hợp lệ.'},403);const body:any=await req.json();if(!body||typeof body!=='object')throw new GameError('Yêu cầu không hợp lệ.');const settings=await ensurePlayable(req,body.action==='chat');const identity=await actor(req);const now=Date.now();let row:any=await db().prepare('UPDATE rpg_profiles SET locked_until=? WHERE id=? AND locked_until<? RETURNING *').bind(now+15000,identity.id,now).first();if(!row){const exists=await db().prepare('SELECT id FROM rpg_profiles WHERE id=?').bind(identity.id).first();if(exists)return json({error:'Thao tác đang được xử lý, hãy thử lại.'},429);await session(new Request(req.url,{headers:{...Object.fromEntries(req.headers),cookie:'vt_session='+identity.id}}));row=await db().prepare('UPDATE rpg_profiles SET locked_until=? WHERE id=? AND locked_until<? RETURNING *').bind(now+15000,identity.id,now).first();if(!row)return json({error:'Thao tác đang được xử lý, hãy thử lại.'},429);}lockedId=identity.id;const s={id:identity.id,cookie:identity.cookie,profile:await hydrate(identity.id,JSON.parse(row.data)),version:row.version,lastSeen:row.last_seen};const before=structuredClone(s.profile);const result=await act(s,before,body,s.lastSeen);if(s.profile.xp>before.xp){s.profile.xp=before.xp+Math.floor((s.profile.xp-before.xp)*settings.xpMultiplier);if(settings.xpMultiplier!==1&&result.notice)result.notice+=' · Tu vi ×'+settings.xpMultiplier;}try{await save(s,before,result.statements);}catch(error){if(body.action==='redeemCode'){const code=String(body.code||'').trim().toUpperCase(),gift:any=await db().prepare('SELECT uses_remaining,active,expires_at FROM rpg_giftcodes WHERE code=?').bind(code).first(),claimed=await db().prepare('SELECT code FROM rpg_gift_claims WHERE code=? AND owner=?').bind(code,s.id).first();if(claimed||!gift||!gift.active||gift.uses_remaining<=0||gift.expires_at<=Date.now())throw new GameError('Giftcode đã nhận, đã đóng hoặc hết lượt.');}throw error;}const payload=await world(s,{notice:result.notice,hits:result.hits,effect:result.effect},body.action==='sync'&&!body.full);return json(payload,200,s.cookie);}catch(e){if(e instanceof AdminError)return json({error:e.message},e.status);if(e instanceof GameError)return json({error:e.message},400);console.error('RPG action failure',e);return json({error:'Máy chủ đang gián đoạn. Tiến trình đã lưu vẫn được giữ. Hãy tải lại.'},503);}finally{if(lockedId)await db().prepare('UPDATE rpg_profiles SET locked_until=0 WHERE id=?').bind(lockedId).run();}}
