import type { SVGProps } from 'react';

type PixelProps=SVGProps<SVGSVGElement>&{size?:number|string};
// Every icon is drawn on a 16×16 pixel grid. No strokes or smoothing.
const palette:Record<string,string>={x:'currentColor',o:'#15212b',g:'#c5a264',h:'#ffe9ae',b:'#75523b',s:'#adcbd3',w:'#e9f6ea',t:'#62bcad',d:'#31747c',r:'#d96365',v:'#b496e8',p:'#6455a5',i:'#90d9ed'};
const art:Record<string,string[]>={
 Sword:[
 '............oooo','...........oswho','..........oswwho','.........oswwho.','........oswwho..','.......oswwho...','......oswwho....','..o..oswwho.....','..ogoswwho......','...ghswho.......','....ghho........','....ohgo........','...ogoghgo......','..oggo.ogo......','.ohgo...o.......','..oo............'],
 Swords:[
 'oo............oo','ogoo........oogo','.ghso......oshg.','..ghso....oshg..','...ghso..oshg...','....ghsooshg....','.....ghsswg.....','......ghwg......','......owwo......','.....ohssho.....','..ooohs..sho oo.','..gghs....shgg..','...ghgo..oghg...','..ogogo..ogogo..','.ohg.o....o.gho.','..oo........oo..'],
 Snowflake:[
 '.......ii.......','...i...ii...i...','....i..ww..i....','.....i.ww.i.....','.i....iwwi....i.','..i....ww....i..','...i...ww...i...','iiwwwwwwwwwwwwii','iiwwwwwwwwwwwwii','...i...ww...i...','..i....ww....i..','.i....iwwi....i.','.....i.ww.i.....','....i..ww..i....','...i...ii...i...','.......ii.......'],
 Zap:[
 '.........vvvo...','........vvvpo...','.......vvwpo....','......vvwpo.....','.....vvwpo......','....vvwpo.......','...vvwwwvvvvvo..','..vvwwwvvvppo...','...opppvvwpo....','......vvwpo.....','.....vvwpo......','....vvwpo.......','...vvwpo........','..vvwpo.........','..vppo..........','..oo............'],
 Heart:[
 '.....oooooo.....','.....ohhhho.....','......oggo......','......oggo......','.....owwwoo.....','....owwwttoo....','...owwtttddoo...','...owtttttddo...','...ottttttddo...','...ottttttddo...','...ottttttddo...','...ottttttddo...','...odttttdddo...','....oddddddo....','.....oooooo.....','................'],
 Gem:[
 '................','.....oooooo.....','....ottwwtto....','...ottwwwdtto...','..ottwwwwddtto..','.ottwwwwwdddtdo.','.otttwwwddddddo.','..otttwwdddddo..','...otttwddddo...','....ottwdddo....','.....otwddo.....','......otdo......','.......oo.......','................','................','................'],
 Backpack:[
 '.....oooooo.....','....oghhhngo....','....ogooooho....','...oooooooooo...','..oghhhhhhhhgo..','..oggggggggggo..','..ogggghhggggo..','..obggghhgggbo..','..obggggggggbo..','..oboooooooooo..','..obohhhhhhgbo..','..obogggggggbo..','..obogggggggbo..','..obbbbbbbbbbo..','...oooooooooo...','................'],
 ScrollText:[
 '..oooooooooooo..','.oghhhhhhhhhhgo.','.oggoooooooohgo.','..obhhhhhhoobbo.','..ohhhhhhhgooo..','..ohbbbbbhgo....','..ohhhhhhhgo....','..ohbbbbbhgo....','..ohhhhhhhgo....','..ohbbbbhhgo....','..ohhhhhhhgo....','..oghhhhhhgo....','..ogoooooogoo...','.oggggggggbbo...','..oooooooooo....','................'],
 BookOpen:[
 '................','.oooooo..oooooo.','.oghhhhoohhhhgo.','.oghbghoohgbhgo.','.oghbghoohgbhgo.','.oghbghoohgbhgo.','.oghhhhoohhhhgo.','.oghbghoohgbhgo.','.oghbghoohgbhgo.','.oghhhhoohhhhgo.','.oghbghoohgbhgo.','.oghhhhoohhhhgo.','.obbbbboobbbbbo.','.oooooo..oooooo.','................','................'],
 Shield:[
 '.......oo.......','.....ooggoo.....','...oohhhhgggo...','..ohhhhhhggggo..','..ohhhhwwggggo..','..ohhhwwwggggo..','..oghhhwwggggo..','..oggggwwgggbo..','...oggggggbbo...','...ogggggbbbo...','....ogggbbbo....','.....ogbbbo.....','......obbo......','.......oo.......','................','................'],
 Sparkles:['.......x........','.......x........','......xxx.......','.....xxxxx......','..xxxxxxxxxxx...','.....xxxxx......','......xxx.......','.......x........','.......x........','............x...','...........xxx..','..........xxxxx.','...........xxx..','............x...','................','................'],
 Play:['................','...xx...........','...xxxx.........','...xxxxxx.......','...xxxxxxxx.....','...xxxxxxxxxx...','...xxxxxxxxxxxx.','...xxxxxxxxxx...','...xxxxxxxx.....','...xxxxxx.......','...xxxx.........','...xx...........','................','................','................','................'],
 Pause:['................','..xxxx....xxxx..','..xxxx....xxxx..','..xxxx....xxxx..','..xxxx....xxxx..','..xxxx....xxxx..','..xxxx....xxxx..','..xxxx....xxxx..','..xxxx....xxxx..','..xxxx....xxxx..','..xxxx....xxxx..','..xxxx....xxxx..','................','................','................','................'],
 ChevronRight:['................','.....xx.........','......xx........','.......xx.......','........xx......','.........xx.....','..........xx....','...........xx...','..........xx....','.........xx.....','........xx......','.......xx.......','......xx........','.....xx.........','................','................'],
 Send:['................','..xxxxxxxxxxxx..','..xx......xxx...','...xx....xxx....','....xx..xxx.....','.....xxxxx......','......xxx.......','.....xxxx.......','....xx.xx.......','...xx..xx.......','..xx...xx.......','.......xx.......','.......xx.......','.......xx.......','................','................'],
 MessageSquare:['................','.xxxxxxxxxxxxxx.','.xx..........xx.','.xx..........xx.','.xx.xxxxxx...xx.','.xx..........xx.','.xx.xxxx.....xx.','.xx..........xx.','.xx..........xx.','.xxxxxxxxxxxxxx.','......xxxx......','.....xxxx.......','....xxxx........','...xxxx.........','................','................'],
 Wind:['................','..........xxx...','.........xx.xx..','............xx..','..xxxxxxxxxxx...','................','................','....xxxxxxxxxx..','............xxx.','.............xx.','...........xxxx.','................','...xxxxxx.......','.......xxx......','......xxx.......','................'],
 CircleHelp:['.....xxxxxx.....','...xxx....xxx...','..xx........xx..','.xx...xxxx...xx.','.xx..xx..xx..xx.','.xx......xx..xx.','.xx.....xx...xx.','.xx....xx....xx.','.xx....xx....xx.','.xx..........xx.','.xx....xx....xx.','.xx....xx....xx.','..xx........xx..','...xxx....xxx...','.....xxxxxx.....','................'],
 Maximize:['.xxxxx....xxxxx.','.xx..........xx.','.xx..........xx.','.xx..........xx.','.xx..........xx.','................','................','................','................','................','.xx..........xx.','.xx..........xx.','.xx..........xx.','.xx..........xx.','.xxxxx....xxxxx.','................'],
 Volume2:['................','.......xx.......','......xxx..xx...','.....xxxx...xx..','..xxxxxxx.x..xx.','..xxxxxxx..x.xx.','..xxxxxxx..x.xx.','..xxxxxxx..x.xx.','..xxxxxxx..x.xx.','..xxxxxxx..x.xx.','..xxxxxxx.x..xx.','.....xxxx...xx..','......xxx..xx...','.......xx.......','................','................'],
 VolumeX:['................','.......xx.......','......xxx.......','.....xxxx.......','..xxxxxxx.xx.xx.','..xxxxxxx..xxx..','..xxxxxxx...x...','..xxxxxxx..xxx..','..xxxxxxx.xx.xx.','..xxxxxxx.......','..xxxxxxx.......','.....xxxx.......','......xxx.......','.......xx.......','................','................'],
 Settings2:['................','....xx..........','..xxxxxx........','....xx..........','....xx..........','....xx...xx.....','....xx..xxxx....','....xx.xxxxxx...','....xx..xxxx....','....xx...xx.....','...xxxx..xx.....','..xxxxxx.xx.....','...xxxx..xx.....','....xx...xx.....','................','................'],
 MapPin:['................','.....xxxxxx.....','....xxxxxxxx....','...xxx....xxx...','...xx..xx..xx...','...xx.xxxx.xx...','...xx..xx..xx...','...xxx....xxx...','....xxxxxxxx....','.....xxxxxx.....','......xxxx......','.......xx.......','.......xx.......','................','................','................'],
 Users:['................','....xxxx........','...xxxxxx..xxx..','...xxxxxx.xxxxx.','....xxxx..xxxxx.','...........xxx..','..xxxxxxxx......','.xxxxxxxxxx.xxx.','.xxxxxxxxxxxxxxx','.xxxxxxxxxxxxxxx','..xxxxxxxx.xxxx.','................','................','................','................','................'],
 Crosshair:['.......xx.......','.......xx.......','....xxxxxxxx....','...xx..xx..xx...','..xx...xx...xx..','..x..........x..','..x....xx....x..','xxxxx.xxxx.xxxxx','xxxxx.xxxx.xxxxx','..x....xx....x..','..x..........x..','..xx...xx...xx..','...xx..xx..xx...','....xxxxxxxx....','.......xx.......','.......xx.......'],
};
function makeIcon(name:string){return function PixelIcon({size=24,...props}:PixelProps){const rows=art[name]||art.Sparkles;const paths:Record<string,string>={};rows.forEach((row,y)=>[...row].forEach((pixel,x)=>{if(pixel==='.'||pixel===' ')return;const color=palette[pixel]||palette.g;paths[color]=(paths[color]||'')+`M${x} ${y}h1v1h-1z`;}));return <svg width={size} height={size} viewBox="0 0 16 16" fill="none" aria-hidden="true" shapeRendering="crispEdges" {...props}>{Object.entries(paths).map(([color,path])=><path key={color} fill={color} d={path}/>)}</svg>;};}
export const Sword=makeIcon('Sword'),Swords=makeIcon('Swords'),Backpack=makeIcon('Backpack'),ScrollText=makeIcon('ScrollText'),BookOpen=makeIcon('BookOpen'),Volume2=makeIcon('Volume2'),VolumeX=makeIcon('VolumeX'),Maximize=makeIcon('Maximize'),Settings2=makeIcon('Settings2'),CircleHelp=makeIcon('CircleHelp'),Coins=makeIcon('Gem'),Gem=makeIcon('Gem'),Sparkles=makeIcon('Sparkles'),ChevronRight=makeIcon('ChevronRight'),Wind=makeIcon('Wind'),Zap=makeIcon('Zap'),Snowflake=makeIcon('Snowflake'),Flame=makeIcon('Zap'),Send=makeIcon('Send'),MessageSquare=makeIcon('MessageSquare'),Shield=makeIcon('Shield'),MapPin=makeIcon('MapPin'),Play=makeIcon('Play'),Pause=makeIcon('Pause'),Leaf=makeIcon('Sparkles'),Heart=makeIcon('Heart'),Users=makeIcon('Users'),Crosshair=makeIcon('Crosshair');
