import {rankingHolders} from './leaderboard';
import {SECRETS,secretProgress,secretKnown} from './secrets';
import {immortalAction} from './immortal-actions';
import {partyHit,partyFor} from './parties';
import {currentDharma,DHARMAS} from './immortal';
import {db,GameError,buyListing,type Session} from './database';
import {REALMS,MAPS,NPCS,QUESTS,STORY_IDS,questUnlocked,npcPosition,QUALITIES,SLOTS,PETS,MOUNTS,BOOKS,TITLES,ACHIEVEMENTS,CURRENCIES,WORLD_BOSSES,CLASSES,RACES,ROOTS,type Currency} from './catalog';
import {stats,rank,nextXp,successChance,makeItem,metric,availableTitles,enemiesFor,questProgress,resourceNodes,SKILLS,safePosition,tideActive,insightActive,type Profile,type Item} from './model';
export const random=()=>crypto.getRandomValues(new Uint32Array(1))[0]/4294967296;
const requireRule=(condition:unknown,message:string)=>{if(!condition)throw new GameError(message);};
const charge=(p:Profile,currency:Currency,amount:number)=>{requireRule(Number.isSafeInteger(amount)&&amount>=0,'Giá không hợp lệ.');requireRule(p.coins[currency]>=amount,'Không đủ '+(CURRENCIES.find(x=>x.id===currency)?.name||'tiền tệ')+'.');p.coins[currency]-=amount;};
const touch=(p:Profile,step:number)=>{if(!p.tutorial.includes(step))p.tutorial.push(step);};
const ownItem=(p:Profile,uid:string)=>{const i=p.inventory.find(x=>x.uid===uid);requireRule(i,'Vật phẩm không còn trong hành trang.');return i!;};
export type ActionResult={notice:string;hits:any[];effect?:any;statements:D1PreparedStatement[]};
export async function act(s:Session,before:Profile,body:any,lastSeen:number):Promise<ActionResult>{
 const p=s.profile,now=Date.now(),out:ActionResult={notice:'',hits:[],statements:[]},st=stats(p),action=String(body.action||'');
 const announce=(message:string)=>out.statements.push(db().prepare('INSERT INTO rpg_messages(owner,name,map_id,body,created_at,channel,scope) VALUES(?,?,?,?,?,?,?)').bind('system','Tiên báo',p.mapId,message,now,'system',null));
 const elapsed=Math.min(3,Math.max(0,(now-lastSeen)/1000));const next=safePosition(Number.isFinite(body.x)?body.x:p.x,Number.isFinite(body.y)?body.y:p.y),distance=Math.hypot(next.x-p.x,next.y-p.y),limit=st.speed*Math.max(.12,elapsed)+25;if(distance>limit){next.x=p.x+(next.x-p.x)*limit/distance;next.y=p.y+(next.y-p.y)*limit/distance;}p.x=next.x;p.y=next.y;
 p.mp=Math.min(st.mp,p.mp+Math.floor(elapsed*(8+p.realm*2)));
 if(action==='sync'){
 const near=enemiesFor(p,now).filter(e=>e.hp>0&&Math.hypot(e.x-p.x,e.y-p.y)<85);const damage=Math.max(0,near.reduce((sum,e)=>sum+e.attack,0)-st.defense*.08)*elapsed;p.hp=Math.max(0,p.hp-Math.floor(damage));if(p.hp>0&&p.x<740&&!p.dungeon)p.hp=Math.min(st.hp,p.hp+Math.floor(elapsed*st.hp*.035));return out;
 }
 requireRule((p.cooldowns.action||0)<now,'Thao tác quá nhanh.');p.cooldowns.action=now+220;
 if(await immortalAction(s,body,out))return out;
 if(action==='name'){const name=String(body.name||'').trim();requireRule(name.length>=2&&name.length<=22,'Đạo danh dài từ 2 đến 22 ký tự.');p.name=name;out.notice='Đạo danh đã được lưu.';}
 else if(action==='chat'){const message=String(body.message||'').trim();requireRule(message.length>0&&message.length<=200,'Tin nhắn dài từ 1 đến 200 ký tự.');requireRule((p.cooldowns.chat||0)<now,'Chờ một chút trước khi gửi tiếp.');p.cooldowns.chat=now+1800;let scope:string|null=null;const channel=p.chatChannel;if(channel==='party'){const team=await partyFor(s.id);requireRule(team,'Hãy gia nhập tổ đội trước.');scope=team.id;}else if(channel==='sect'){const member:any=await db().prepare("SELECT guild_id FROM rpg_members WHERE owner=? AND kind='sect'").bind(s.id).first();requireRule(member,'Hãy gia nhập tông môn trước.');scope=member.guild_id;}out.statements.push(db().prepare('INSERT INTO rpg_messages(owner,name,map_id,body,created_at,channel,scope) VALUES(?,?,?,?,?,?,?)').bind(s.id,p.name,p.mapId,message,now,channel,scope),db().prepare('DELETE FROM rpg_messages WHERE id<(SELECT MAX(id)-300 FROM rpg_messages)'));}
 else if(action==='class'){requireRule(CLASSES.some(c=>c.id===body.classId),'Đạo phái không hợp lệ.');if(p.kills>0)charge(p,'stone',50);p.classId=body.classId;p.hp=stats(p).hp;p.mp=stats(p).mp;out.notice='Đã chọn '+CLASSES.find(c=>c.id===p.classId)?.name+'.';}
 else if(action==='race'){requireRule(Number.isInteger(body.race)&&RACES[body.race],'Tộc không hợp lệ.');charge(p,'stone',60);p.race=body.race;out.notice='Huyết mạch '+RACES[p.race]+' đã thức tỉnh.';}
 else if(action==='root'){charge(p,'stone',80);p.root=Math.floor(random()*ROOTS.length);const roll=random();p.rootGrade=roll<.02?5:roll<.12?4:roll<.38?3:roll<.7?2:1;out.notice=`Thức tỉnh ${ROOTS[p.root]} linh căn · phẩm ${p.rootGrade}/5.`;}
 else if(action==='travel'){const map=MAPS[Number(body.mapId)];requireRule(map,'Linh địa không tồn tại.');requireRule(p.realm>=map.minRealm,'Cảnh giới chưa đủ để đến linh địa này.');requireRule(!p.dungeon,'Hãy rời phụ bản trước khi dịch chuyển.');requireRule((p.cooldowns.travel||0)<now,'Cổng dịch chuyển đang hồi.');p.mapId=map.id;p.x=620;p.y=550;p.encounters={};p.cooldowns.travel=now+3000;if(!p.visited.includes(map.id))p.visited.push(map.id);if(map.id!==0)touch(p,5);out.notice='Đã đến '+map.name;out.effect={type:'travel'};}
 else if(action==='talk'){const n=NPCS[Number(body.npcId)];requireRule(n&&n.map===p.mapId,'NPC ở linh địa khác.');requireRule(Math.hypot(npcPosition(n).x-p.x,npcPosition(n).y-p.y)<200,'Hãy đến gần NPC.');if(!p.talked.includes(n.id))p.talked.push(n.id);touch(p,0);const next=QUESTS.find(q=>q.id===STORY_IDS.find(id=>!p.claimed.includes(id)));if(n.id===0&&next&&!p.accepted.includes(next.id)&&p.accepted.length<30)p.accepted.push(next.id);const clue=SECRETS.find(secret=>secret.map===p.mapId&&!secretKnown(p,secret.id));out.notice=n.name+': '+n.dialogue+(clue?' Manh mối: '+clue.hint:'');}
 else if(action==='resource'){requireRule(p.hp>0,'Hãy hồi sinh trước.');const node=resourceNodes(p.mapId).find(n=>n.id===Number(body.nodeId));requireRule(node,'Tài nguyên không tồn tại.');requireRule(Math.hypot(node!.x-p.x,node!.y-p.y)<120,'Hãy đến gần tài nguyên.');requireRule((p.cooldowns.resource||0)<now,'Đợi linh khí ngưng tụ thêm.');p.cooldowns.resource=now+4000;if(node!.type==='secret'){const secret=SECRETS[Number(node!.id)-100];requireRule(secret&&secret.map===p.mapId,'Dấu tích không tồn tại.');requireRule(p.realm>=secret.realm,'Cần đạt cảnh giới của linh địa này.');requireRule(!secretKnown(p,secret.id),'Đã giải mã dấu tích này; xem nhật ký cơ duyên.');requireRule(secretProgress(p,secret)>=secret.goal,secret.hint);requireRule(p.accepted.length<30,'Nhật ký đang đầy.');p.secretsFound.push(secret.id);if(!p.accepted.includes(secret.id))p.accepted.push(secret.id);out.notice=secret.story;}else if(node!.type==='hidden'){requireRule(!p.discovered.includes(p.mapId),'Bí mật này đã được khám phá.');p.discovered.push(p.mapId);p.relics++;p.materials.essence+=2;touch(p,6);out.notice='Phát hiện cơ duyên ẩn: '+QUESTS.find(q=>q.map===p.mapId&&q.hidden)?.name;}else{const key=`${p.mapId}:${node!.type}`;p.gathered[key]=(p.gathered[key]||0)+1;p.daily.gather++;if(node!.type==='herb')p.materials.herb++;else p.materials.ore++;p.xp+=6*(p.realm+1);p.coins.silver+=10;p.relics+=random()<.08?1:0;out.notice='+1 '+node!.label+' · +'+6*(p.realm+1)+' tu vi';}}
 else if(action==='accept'){const q=QUESTS.find(q=>q.id===body.questId);requireRule(q,'Nhiệm vụ không tồn tại.');requireRule(questUnlocked(p.claimed,q!),'Hãy hoàn thành chương cốt truyện trước.');requireRule(MAPS[q!.map].minRealm<=p.realm,'Cảnh giới chưa đạt yêu cầu.');requireRule(!q!.hidden||(q!.type==='secret'?secretKnown(p,q!.id):p.discovered.includes(q!.map)),'Chưa khám phá cơ duyên ẩn này.');requireRule(!p.claimed.includes(q!.id),'Nhiệm vụ đã hoàn thành.');requireRule(p.accepted.length<30,'Nhật ký đang đầy (30 nhiệm vụ).');if(!p.accepted.includes(q!.id))p.accepted.push(q!.id);touch(p,1);out.notice='Đã nhận nhiệm vụ: '+q!.name;}
 else if(action==='claimQuest'){const q=QUESTS.find(q=>q.id===body.questId);requireRule(q&&p.accepted.includes(q.id)&&!p.claimed.includes(q.id),'Nhiệm vụ chưa nhận hoặc đã lĩnh thưởng.');requireRule(questProgress(p,q!)>=q!.count,'Chưa đạt yêu cầu nhiệm vụ.');p.accepted=p.accepted.filter(id=>id!==q!.id);p.claimed.push(q!.id);if(p.trackedQuestId===q!.id)p.trackedQuestId=null;const chapter=STORY_IDS.indexOf(q!.id);if(chapter>=0&&chapter<STORY_IDS.length-1&&!p.claimed.includes(STORY_IDS[chapter+1])&&!p.accepted.includes(STORY_IDS[chapter+1])&&p.accepted.length<30)p.accepted.push(STORY_IDS[chapter+1]);const secret=SECRETS.find(s=>s.id===q!.id);if(secret){p.materials.essence+=secret.essence;p.relics+=secret.relics;}p.questCount++;p.daily.quests++;p.meridianXp+=q!.hidden?15:8;p.xp+=q!.rewardXp;p.coins.stone+=q!.rewardStone;p.coins.silver+=50+q!.map*5;p.coins.merit+=q!.hidden?15:5;if(q!.type==='boss'||q!.hidden)p.coins.jade+=2;if(q!.map>=36)p.coins.divine+=5;const partnerNpc=q!.map*2+1;p.bond[String(partnerNpc)]=(p.bond[String(partnerNpc)]||0)+3;out.notice=`Hoàn thành · +${q!.rewardXp} tu vi · +${q!.rewardStone} linh thạch`;if(secret){const unlocked=DHARMAS.find(d=>d.quest===secret.id);out.notice+=' · +'+secret.essence+' tinh phách · +'+secret.relics+' cổ tịch'+(unlocked?' · Mở '+unlocked.name:'');}
 }
 else if(action==='trackQuest'){const id=body.questId;requireRule(id===null||(typeof id==='string'&&p.accepted.includes(id)&&QUESTS.some(q=>q.id===id)),'Chỉ theo dõi nhiệm vụ đã nhận.');p.trackedQuestId=id;out.notice=id?'Đã theo dõi nhiệm vụ.':'Đã bỏ theo dõi.';}
 else if(action==='abandon'){p.accepted=p.accepted.filter(id=>id!==body.questId);if(p.trackedQuestId===body.questId)p.trackedQuestId=null;out.notice='Đã bỏ nhiệm vụ; có thể nhận lại.';}
 else if(action==='cultivate'){requireRule(p.hp>0,'Hãy hồi sinh trước.');requireRule(p.x<740&&!p.dungeon,'Về vùng an toàn để điều tức.');requireRule((p.cooldowns.cultivate||0)<now,'Điều tức đang hồi 5 giây.');p.cooldowns.cultivate=now+5000;const xp=(12+rank(p)*2)*(insightActive(now)?2:1);p.xp+=xp;p.daily.meditate++;p.meditations++;p.meridianXp+=8;p.hp=st.hp;p.mp=st.mp;out.notice='Điều tức hoàn tất · +'+xp+' tu vi';out.effect={type:'cultivate'};}
 else if(action==='breakthrough'){requireRule(p.hp>0,'Hãy hồi sinh trước.');requireRule(p.realm<44||p.star<10,'Đã đạt Hồng Mông thập tinh.');const needed=nextXp(p);requireRule(p.xp>=needed,'Tu vi chưa đủ để đột phá.');charge(p,'stone',5+p.realm*3);let chance=Math.min(.99,successChance(p)+Math.min(.16,(p.cooldowns.pity||0)*.02));if(body.protect){requireRule(p.shieldDan>0,'Đã hết Hộ Kiếp Đan.');p.shieldDan--;chance=Math.min(.99,chance+.12);}const rolled=random(),success=rolled<chance,tribulation=p.star===10;p.breakAttempts++;if(tribulation)p.trials++;if(success){p.xp-=needed;p.breakSuccess++;p.cooldowns.pity=0;if(tribulation){p.realm++;p.star=1;announce(p.name+' đã vượt thiên kiếp, bước vào '+REALMS[p.realm]+'.');p.coins.jade+=3;p.relics++;}else p.star++;p.hp=stats(p).hp;p.mp=stats(p).mp;touch(p,4);out.notice=tribulation?'ĐỘ KIẾP THÀNH CÔNG · cảnh giới mới!':'Đột phá thành công · '+p.star+' tinh';}else{if(!body.protect)p.xp-=Math.ceil(needed*.2);p.hp=Math.max(1,p.hp-Math.round(st.hp*.18));p.cooldowns.pity=(p.cooldowns.pity||0)+1;out.notice='Đột phá thất bại · '+(body.protect?'Hộ Kiếp Đan giữ lại tu vi.':'mất 20% lượng tu vi yêu cầu.');}out.effect={type:'tribulation',success,tribulation,chance,roll:rolled};}
 else if(action==='potion'){requireRule(p.hp>0,'Hãy hồi sinh trước.');requireRule(p.potions>0,'Đã hết Hồi Linh Đan.');p.potions--;p.hp=Math.min(st.hp,p.hp+Math.round(st.hp*.55));p.mp=Math.min(st.mp,p.mp+Math.round(st.mp*.6));out.notice='Hồi phục 55% khí huyết, 60% linh lực.';}
 else if(action==='buyPotion'){charge(p,'silver',80);p.potions+=3;out.notice='Đã mua 3 Hồi Linh Đan.';}
 else if(action==='buyShield'){charge(p,'stone',120);p.shieldDan++;out.notice='Đã mua Hộ Kiếp Đan.';}
 else if(action==='equip'){const item=ownItem(p,String(body.uid));const listed=await db().prepare("SELECT id FROM rpg_listings WHERE item_uid=? AND status='open'").bind(item.uid).first();requireRule(!listed,'Hãy hủy tin rao trước khi trang bị.');p.equipped[item.slot]=item.uid;out.statements.push(db().prepare('UPDATE rpg_items SET equipped_slot=NULL WHERE owner=? AND equipped_slot=?').bind(s.id,item.slot),db().prepare('UPDATE rpg_items SET equipped_slot=? WHERE uid=? AND owner=?').bind(item.slot,item.uid,s.id));touch(p,3);out.notice='Đã trang bị '+item.name;}
 else if(action==='unequip'){const item=ownItem(p,String(body.uid));delete p.equipped[item.slot];out.statements.push(db().prepare('UPDATE rpg_items SET equipped_slot=NULL WHERE uid=? AND owner=?').bind(item.uid,s.id));out.notice='Đã tháo trang bị.';}
 else if(action==='enhance'){const item=ownItem(p,String(body.uid));requireRule(item.enhance<10,'Đã cường hóa +10.');const listed=await db().prepare("SELECT id FROM rpg_listings WHERE item_uid=? AND status='open'").bind(item.uid).first();requireRule(!listed,'Hãy hủy tin rao trước khi cường hóa.');charge(p,'stone',15*(item.enhance+1)*(item.quality+1));item.enhance++;out.statements.push(db().prepare('UPDATE rpg_items SET data=? WHERE uid=? AND owner=?').bind(JSON.stringify(item),item.uid,s.id));out.notice='Cường hóa thành công · +'+item.enhance;}
 else if(action==='craft'){const slot=SLOTS.find(x=>x.id===body.slot),q=Number(body.quality);requireRule(slot&&Number.isInteger(q)&&QUALITIES[q],'Công thức không hợp lệ.');requireRule(p.realm>=q*5,'Cảnh giới chưa đủ để rèn phẩm này.');const price=(40+rank(p)*8)*(q+1)*(q+1);charge(p,q>=6?'divine':q>=4?'jade':q>=1?'stone':'silver',q>=4?Math.max(5,Math.ceil(price/20)):price);const item=makeItem(slot!.id,q,rank(p));requireRule(p.inventory.length<300,'Hành trang tối đa 300 vật phẩm.');p.inventory.push(item);out.statements.push(db().prepare('INSERT INTO rpg_items(uid,owner,data) VALUES(?,?,?)').bind(item.uid,s.id,JSON.stringify(item)));out.notice='Rèn thành công: '+item.name;}
 else if(action==='sellNpc'){const item=ownItem(p,String(body.uid));requireRule(!Object.values(p.equipped).includes(item.uid),'Hãy tháo trang bị trước.');const listed=await db().prepare("SELECT id FROM rpg_listings WHERE item_uid=? AND status='open'").bind(item.uid).first();requireRule(!listed,'Vật phẩm đang được rao bán.');p.coins.silver+=Math.round(item.stat*4);p.inventory=p.inventory.filter(i=>i.uid!==item.uid);out.statements.push(db().prepare('DELETE FROM rpg_items WHERE uid=? AND owner=?').bind(item.uid,s.id));out.notice='Đã bán · +'+Math.round(item.stat*4)+' ngân lượng';}
 else if(action==='pet'||action==='mount'){const catalog=action==='pet'?PETS:MOUNTS,entry=catalog[Number(body.id)];requireRule(entry,'Linh thú không tồn tại.');requireRule(p.realm>=entry.minRealm,'Cảnh giới chưa đủ để thu phục.');const collection=action==='pet'?p.pets:p.mounts;requireRule(!collection.some(x=>x.id===entry.id),'Đạo hữu đã có linh thú này.');charge(p,'stone',entry.price);collection.push({id:entry.id,level:1});if(action==='pet')p.petId=entry.id;else p.mountId=entry.id;touch(p,7);out.notice='Đã thu phục '+entry.name;}
 else if(action==='companionSelect'){const isPet=body.kind==='pet',collection=isPet?p.pets:p.mounts;const id=body.id===null?null:Number(body.id);requireRule(id===null||collection.some(x=>x.id===id),'Chưa sở hữu linh thú này.');if(isPet)p.petId=id;else p.mountId=id;out.notice=id===null?'Đã cất linh thú.':'Linh thú đã đồng hành.';}
 else if(action==='companionTrain'){const isPet=body.kind==='pet',collection=isPet?p.pets:p.mounts,entry=collection.find(x=>x.id===Number(body.id));requireRule(entry,'Chưa sở hữu linh thú này.');requireRule(entry!.level<25,'Linh thú đã đạt cấp 25.');charge(p,'stone',entry!.level*30);entry!.level++;out.notice='Linh thú tăng lên cấp '+entry!.level;}
 else if(action==='learn'){const book=BOOKS[Number(body.bookId)];requireRule(book,'Bí tịch không tồn tại.');requireRule(p.realm>=book.minRealm,'Cảnh giới chưa đủ để lĩnh ngộ.');requireRule(!p.books.includes(book.id),'Đã lĩnh ngộ bí tịch này.');charge(p,book.kind==='Bí tịch'?'merit':'stone',book.price);if(book.kind==='Truyền thừa'){requireRule(p.heritage<30,'Truyền thừa đã đạt 30 tầng.');requireRule(p.relics>=2,'Cần 2 mảnh truyền thừa.');p.relics-=2;p.heritage++;}p.books.push(book.id);out.notice='Lĩnh ngộ '+book.name+' · lực chiến tăng';}
 else if(action==='heritage'){requireRule(p.relics>=5,'Cần 5 mảnh cổ tịch.');requireRule(p.heritage<30,'Truyền thừa đã đạt 30 tầng.');p.relics-=5;p.heritage++;out.notice='Truyền thừa tăng đến tầng '+p.heritage;}
 else if(action==='title'){p.rankingTitles=(await rankingHolders(true)).get(s.id)||[];requireRule(availableTitles(p).some(t=>t.id===body.titleId),'Chưa đạt yêu cầu danh hiệu.');p.titleId=body.titleId;out.notice='Đã chọn danh hiệu '+TITLES.find(t=>t.id===p.titleId)?.name;}
 else if(action==='achievement'){const a=ACHIEVEMENTS[Number(body.id)];requireRule(a,'Thành tích không tồn tại.');requireRule(!p.achievements.includes(a.id),'Đã nhận thưởng thành tích.');requireRule(metric(p,a.type)>=a.target,'Chưa đạt yêu cầu thành tích.');p.achievements.push(a.id);p.coins.stone+=a.reward;p.coins.jade++;out.notice='Nhận thưởng thành tích · +'+a.reward+' linh thạch';}
 else if(action==='tutorialReward'){const done=p.tutorial.includes(Number(body.step));requireRule(done,'Hãy hoàn thành bước hướng dẫn.');const key='tutorial-'+Number(body.step);requireRule(!p.eventClaims.includes(key),'Đã nhận thưởng bước này.');p.eventClaims.push(key);p.coins.stone+=40;p.coins.silver+=120;out.notice='Thưởng tân thủ · +40 linh thạch · +120 ngân lượng';}
 else if(action==='guildCreate'){const kind=body.kind==='clan'?'clan':'sect';const name=String(body.name||'').trim();requireRule(name.length>=3&&name.length<=24,'Tên từ 3 đến 24 ký tự.');const member=await db().prepare('SELECT id FROM rpg_members WHERE owner=? AND kind=?').bind(s.id,kind).first();requireRule(!member,'Đã có '+(kind==='sect'?'tông môn':'gia tộc')+'.');const exists=await db().prepare('SELECT id FROM rpg_guilds WHERE name=? AND kind=?').bind(name,kind).first();requireRule(!exists,'Tên đã được dùng.');charge(p,'stone',kind==='clan'?300:500);const id=crypto.randomUUID();out.statements.push(db().prepare('INSERT INTO rpg_guilds(id,kind,name,leader,created_at) VALUES(?,?,?,?,?)').bind(id,kind,name,s.id,now),db().prepare('INSERT INTO rpg_members(id,owner,kind,guild_id) VALUES(?,?,?,?)').bind(s.id+':'+kind,s.id,kind,id));out.notice='Đã thành lập '+name;}
 else if(action==='guildJoin'){const guild:any=await db().prepare('SELECT * FROM rpg_guilds WHERE id=?').bind(String(body.guildId)).first();requireRule(guild,'Không tìm thấy cộng đồng.');const member=await db().prepare('SELECT id FROM rpg_members WHERE owner=? AND kind=?').bind(s.id,guild.kind).first();requireRule(!member,'Đã thuộc một cộng đồng cùng loại.');out.statements.push(db().prepare('INSERT INTO rpg_members(id,owner,kind,guild_id) VALUES(?,?,?,?)').bind(s.id+':'+guild.kind,s.id,guild.kind,guild.id));out.notice='Gia nhập '+guild.name;}
 else if(action==='guildDonate'){const member:any=await db().prepare('SELECT * FROM rpg_members WHERE owner=? AND guild_id=?').bind(s.id,String(body.guildId)).first();requireRule(member,'Chưa gia nhập cộng đồng này.');charge(p,'stone',100);p.coins.merit+=80;out.statements.push(db().prepare('UPDATE rpg_guilds SET treasury=treasury+100 WHERE id=?').bind(member.guild_id),db().prepare('UPDATE rpg_members SET contribution=contribution+100 WHERE id=?').bind(member.id));out.notice='Cống hiến 100 linh thạch · +80 công trạng';}
 else if(action==='gift'){const n=NPCS[Number(body.npcId)];requireRule(n?.female,'Chỉ có thể kết duyên với nữ đạo hữu trưởng thành.');requireRule(n.map===p.mapId&&p.talked.includes(n.id),'Hãy gặp và trò chuyện với đạo hữu này trước.');charge(p,'silver',100);p.bond[String(n.id)]=Math.min(200,(p.bond[String(n.id)]||0)+10);out.notice=n.name+' nhận quà · thiện cảm '+p.bond[String(n.id)]+'/100';}
 else if(action==='bond'){const n=NPCS[Number(body.npcId)];requireRule(n?.female&&p.talked.includes(n.id),'Hãy gặp nữ đạo hữu trước.');requireRule(p.partner===null,'Đạo hữu đã có đạo lữ.');requireRule(p.realm>=2,'Đạt Kết Đan để kết đạo lữ.');requireRule((p.bond[String(n.id)]||0)>=100,'Thiện cảm cần đạt 100.');p.partner=n.id;out.notice=n.name+' đồng ý kết đạo lữ · lực chiến tăng 5%';}
 else if(action==='dualCultivate'){requireRule(p.partner!==null,'Chưa kết đạo lữ.');requireRule((p.cooldowns.dual||0)<now,'Song tu hồi sau 60 giây.');p.cooldowns.dual=now+60000;p.xp+=nextXp(p)*.15;p.xp=Math.floor(p.xp);p.hp=st.hp;p.mp=st.mp;out.notice='Song tu cùng đạo lữ · hồi phục và tăng tu vi';}
 else if(action==='dungeonEnter'){requireRule(!p.dungeon,'Đang ở trong phụ bản.');requireRule(p.hp>0,'Hãy hồi sinh trước.');requireRule((p.cooldowns.dungeon||0)<now,'Cổ cảnh đang ổn định, chờ 30 giây.');charge(p,'silver',60);p.dungeon={mapId:p.mapId,wave:1,kills:0,enteredAt:now};p.encounters={};out.notice='Vào cổ cảnh · đợt 1/3';out.effect={type:'dungeon'};}
 else if(action==='dungeonLeave'){requireRule(p.dungeon,'Không ở trong phụ bản.');p.dungeon=null;p.encounters={};p.x=620;p.y=550;out.notice='Đã rời phụ bản.';}
 else if(action==='eventClaim'){const event=String(body.eventId),active=event==='tide'?tideActive(now):event==='insight'?insightActive(now):false;requireRule(active,'Hoạt động chưa mở.');const key=event+'-'+Math.floor(now/(event==='tide'?600000:900000));requireRule(!p.eventClaims.includes(key),'Đã nhận quà trong lượt hoạt động này.');requireRule(p.kills>=3,'Diệt ít nhất 3 yêu thú để nhận quà hoạt động.');p.eventClaims=[...p.eventClaims.filter(k=>k.startsWith('tutorial-')),...p.eventClaims.filter(k=>!k.startsWith('tutorial-')).slice(-90)];p.eventClaims.push(key);p.coins.jade+=3;p.coins.stone+=60;out.notice='Quà hoạt động · +3 tiên ngọc · +60 linh thạch';}
 else if(action==='list'){const item=ownItem(p,String(body.uid));requireRule(!Object.values(p.equipped).includes(item.uid),'Tháo trang bị trước khi rao bán.');requireRule(CURRENCIES.some(c=>c.id===body.currency),'Loại tiền không hợp lệ.');const price=Number(body.price);requireRule(Number.isSafeInteger(price)&&price>0&&price<=100000000,'Giá từ 1 đến 100.000.000.');const exists=await db().prepare("SELECT id FROM rpg_listings WHERE item_uid=? AND status='open'").bind(item.uid).first();requireRule(!exists,'Vật phẩm đã có tin rao.');out.statements.push(db().prepare('INSERT INTO rpg_listings(id,item_uid,owner,seller_name,item_data,currency,price,created_at) VALUES(?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),item.uid,s.id,p.name,JSON.stringify(item),body.currency,price,now));out.notice='Đã đăng vật phẩm lên chợ giao dịch.';}
 else if(action==='cancelListing'){const l:any=await db().prepare('SELECT * FROM rpg_listings WHERE id=?').bind(String(body.listingId)).first();requireRule(l&&l.owner===s.id&&l.status==='open','Tin rao không thuộc đạo hữu hoặc đã bán.');out.statements.push(db().prepare("UPDATE rpg_listings SET status='cancelled' WHERE id=? AND owner=? AND status='open'").bind(l.id,s.id));out.notice='Đã hủy tin rao.';}
 else if(action==='buyListing'){requireRule(p.inventory.length<300,'Hành trang đã đầy.');await buyListing(s,String(body.listingId));before.coins={...s.profile.coins};out.notice='Giao dịch thành công · vật phẩm đã vào hành trang';}
 else if(action==='bossReward'){const boss=WORLD_BOSSES.find(b=>b.id===body.bossId);const reward:any=await db().prepare('SELECT d.* FROM rpg_boss_damage d JOIN rpg_world_bosses b ON b.id=d.boss_id WHERE d.owner=? AND d.boss_id=? AND d.cycle=? AND d.claimed=0 AND (b.hp=0 OR b.cycle>d.cycle)').bind(s.id,String(body.bossId),Number(body.cycle)).first();requireRule(boss&&reward,'Chưa có thưởng hoặc đã nhận.');p.bosses++;p.daily.boss++;p.dharmaXp+=50;p.materials.essence+=5;p.bossCounts[String(boss!.map)]=(p.bossCounts[String(boss!.map)]||0)+1;p.coins.stone+=200*(boss!.world+1);p.coins.jade+=10*(boss!.world+1);p.coins.divine+=boss!.world+1;p.xp+=500*(boss!.world+1);p.relics+=3;out.statements.push(db().prepare('UPDATE rpg_boss_damage SET claimed=1 WHERE id=? AND owner=? AND claimed=0').bind(reward.id,s.id));out.notice='Nhận thưởng boss thế giới · có Thần tinh!';}
 else if(action==='revive'){requireRule(p.hp<=0,'Đạo hữu vẫn còn khí huyết.');p.hp=st.hp;p.mp=st.mp;p.x=620;p.y=550;p.dungeon=null;p.encounters={};out.notice='Thân vẫn, đạo tâm còn · đã hồi sinh';out.effect={type:'travel'};}
 else if(action==='attack'){
 requireRule(p.hp>0,'Hãy hồi sinh trước khi xuất chiêu.');const skillId=Number(body.skill),skill=SKILLS[skillId];requireRule(skill,'Chiêu thức không hợp lệ.');requireRule((p.cooldowns['skill'+skillId]||0)<=now,'Chiêu thức đang hồi.');requireRule(p.mp>=skill.cost,'Không đủ linh lực.');const teamTarget=body.target==='party-raid',raid=teamTarget?await partyFor(s.id):null;requireRule(!teamTarget||(raid&&raid.phase==='active'&&raid.map_id===p.mapId&&!p.dungeon),'Tổ đội chưa có mục tiêu tại đây.');const target=enemiesFor(p,now).find(e=>e.id===body.target&&e.hp>0),wb=WORLD_BOSSES.find(b=>b.id===body.target&&b.map===p.mapId);requireRule(target||wb||teamTarget,'Chọn mục tiêu còn sống.');const tx=teamTarget?950:target?.x||1110,ty=teamTarget?570:target?.y||550;requireRule(Math.hypot(tx-p.x,ty-p.y)<=skill.range+15,'Mục tiêu quá xa.');p.mp-=skill.cost;p.cooldowns['skill'+skillId]=now+skill.cd;const crit=random()*100<st.crit;const damage=Math.round(st.attack*skill.mult*(crit?1.6:1)*((p.cooldowns.dharmaActive||0)>now&&currentDharma(p)?1.25:1));
 if(teamTarget){await partyHit(s,damage,out);}
 else if(wb){const boss:any=await db().prepare('SELECT * FROM rpg_world_bosses WHERE id=?').bind(wb.id).first();requireRule(boss&&boss.hp>0,'Boss đã bị đánh bại; hãy chờ hồi sinh.');const contribution=s.id+':'+wb.id+':'+boss.cycle;out.statements.push(db().prepare('INSERT INTO rpg_boss_damage(id,boss_id,cycle,owner,damage) SELECT ?,id,cycle,?,MIN(hp,?) FROM rpg_world_bosses WHERE id=? AND hp>0 ON CONFLICT(id) DO UPDATE SET damage=damage+excluded.damage').bind(contribution,s.id,damage,wb.id),db().prepare('UPDATE rpg_world_bosses SET hp=MAX(0,hp-?),respawn_at=CASE WHEN hp<=? THEN ? ELSE 0 END WHERE id=? AND hp>0').bind(damage,damage,now+600000,wb.id));p.hp=Math.max(0,p.hp-Math.max(1,Math.round(wb.rank*.5-st.defense*.15)));out.hits.push({id:wb.id,x:1110,y:550,damage,crit});}
 else{p.hp=Math.max(0,p.hp-Math.max(1,Math.round(target!.attack*.7-st.defense*.18)));const candidates=enemiesFor(p,now).filter(e=>e.hp>0&&(skillId===0?e.id===target!.id:Math.hypot(e.x-target!.x,e.y-target!.y)<(skillId===3?240:150)));for(const e of candidates){const hp=Math.max(0,e.hp-damage);p.encounters[e.id]={hp,respawnAt:hp===0?now+18000:0};out.hits.push({id:e.id,x:e.x,y:e.y,damage,crit,dead:hp===0});if(hp===0){p.kills++;p.daily.kills++;p.meridianXp+=e.boss?18:3;p.dharmaXp+=e.boss?35:5;p.materials.essence+=e.boss?3:random()<.18?1:0;p.killCounts[e.id]=(p.killCounts[e.id]||0)+1;const multiplier=tideActive(now)?1.5:1;p.xp+=Math.floor(e.xp*multiplier);p.coins.stone+=Math.floor((e.boss?65:8)*(1+p.realm)*multiplier);p.coins.silver+=Math.floor((e.boss?180:20)*(1+p.realm));if(e.boss){if(p.killCounts[e.id]===1)announce('Vinh danh '+p.name+' lần đầu chinh phục '+e.name+'.');p.bosses++;p.daily.boss++;p.bossCounts[String(p.mapId)]=(p.bossCounts[String(p.mapId)]||0)+1;p.coins.jade+=1+MAPS[p.mapId].world;p.relics++;if(MAPS[p.mapId].world===2)p.coins.divine++;}
 if((e.boss||random()<.32)&&p.inventory.length<300){const maxQuality=Math.min(7,1+Math.floor(p.realm/5)),quality=Math.max(0,Math.min(maxQuality,Math.floor(random()*random()*(maxQuality+1)))),item=makeItem(SLOTS[Math.floor(random()*SLOTS.length)].id,quality,rank(p));p.inventory.push(item);out.statements.push(db().prepare('INSERT INTO rpg_items(uid,owner,data) VALUES(?,?,?)').bind(item.uid,s.id,JSON.stringify(item)));}
 touch(p,2);
 if(p.dungeon){p.dungeon.kills++;if(e.boss)p.dungeon.bossSlain=true;}
 }}
 if(p.dungeon&&p.dungeon.kills>=3){if(p.dungeon.wave<3){p.dungeon.wave++;p.dungeon.kills=0;p.dungeon.bossSlain=false;p.encounters={};out.notice='Cổ cảnh · đợt '+p.dungeon.wave+'/3';}else if(p.dungeon.bossSlain){const map=p.dungeon.mapId;p.cleared[String(map)]=(p.cleared[String(map)]||0)+1;p.dungeon=null;p.encounters={};p.coins.stone+=120*(1+p.realm);p.coins.jade+=3;p.relics+=2;p.xp+=Math.floor(nextXp(p)*.4);p.cooldowns.dungeon=now+30000;out.notice='PHỤ BẢN HOÀN THÀNH · nhận tiên ngọc và cổ tịch';}}
 if(!out.notice&&out.hits.some(h=>h.dead))out.notice='Đã diệt yêu thú · nhận tu vi và vật phẩm';}
 out.effect={type:'spell',skill:skillId,x:tx,y:ty,fromX:p.x,fromY:p.y,classId:p.classId,root:p.root};
 }
 else throw new GameError('Thao tác không hợp lệ.');
 return out;
}
