import {db,GameError} from './database';
import {requireAdmin,sameOrigin,AdminError} from './admin-auth';
import {commerceConfig,creditOrder,validCode} from './commerce';
import {payosConfigured} from './payos';
function check(ok:unknown,message:string):asserts ok{if(!ok)throw new AdminError(message);}
const audit=(action:string,reason:string,details:unknown)=>db().prepare('INSERT INTO rpg_admin_audit(action,target,reason,details,created_at) VALUES(?,NULL,?,?,?)').bind(action,reason,JSON.stringify(details),Date.now());
export async function adminCommerceView(req:Request){await requireAdmin(req);const [gifts,orders]=await Promise.all([db().prepare('SELECT * FROM rpg_giftcodes ORDER BY created_at DESC LIMIT 100').all(),db().prepare("SELECT o.*,p.name FROM rpg_payment_orders o JOIN rpg_profiles p ON p.id=o.owner ORDER BY CASE WHEN o.status='pending' THEN 0 ELSE 1 END,o.created_at DESC LIMIT 100").all()]);return{gifts:gifts.results.map((r:any)=>({...r,rewards:JSON.parse(r.rewards)})),orders:orders.results,config:await commerceConfig(),payosEnabled:payosConfigured()};}
export async function adminCommerceAction(req:Request,body:any){sameOrigin(req);await requireAdmin(req);check(body&&typeof body==='object','Yêu cầu không hợp lệ.');const why=String(body.reason||'').trim();check(why.length>=3&&why.length<=200,'Ghi lý do từ 3 đến 200 ký tự.');
 if(body.action==='giftCreate'){let code;try{code=validCode(body.code);}catch(e){throw new AdminError((e as Error).message);}const rewards=body.rewards;check(rewards&&typeof rewards==='object'&&!Array.isArray(rewards)&&Object.keys(rewards).every(k=>['silver','stone','jade','merit','divine','potions','shieldDan','herb','ore','essence'].includes(k)),'Quà tặng không hợp lệ.');check(Object.values(rewards).every(n=>typeof n==='number'&&Number.isSafeInteger(n)&&n>=0&&n<=1000000)&&Object.values(rewards).some(n=>Number(n)>0),'Quà từ 0 đến 1.000.000, cần ít nhất một phần thưởng.');check(Number.isSafeInteger(body.maxUses)&&body.maxUses>=1&&body.maxUses<=1000000,'Số lượt từ 1 đến 1.000.000.');check(Number.isSafeInteger(body.expiresAt)&&body.expiresAt>Date.now()&&body.expiresAt<=Date.now()+366*86400000,'Hạn dùng trong vòng 366 ngày.');if(await db().prepare('SELECT code FROM rpg_giftcodes WHERE code=?').bind(code).first())throw new AdminError('Giftcode đã tồn tại, hãy dùng mã mới.');await db().batch([db().prepare('INSERT INTO rpg_giftcodes(code,rewards,uses_remaining,max_uses,expires_at,created_at) VALUES(?,?,?,?,?,?)').bind(code,JSON.stringify(rewards),body.maxUses,body.maxUses,body.expiresAt,Date.now()),audit('giftCreate',why,{code,rewards,maxUses:body.maxUses,expiresAt:body.expiresAt})]);return{notice:'Đã tạo giftcode '+code+'.'};}
 if(body.action==='giftDisable'){const code=validCode(body.code);check(await db().prepare('SELECT code FROM rpg_giftcodes WHERE code=?').bind(code).first(),'Giftcode không tồn tại.');await db().batch([db().prepare('UPDATE rpg_giftcodes SET active=0 WHERE code=?').bind(code),audit('giftDisable',why,{code})]);return{notice:'Đã đóng giftcode.'};}
 if(body.action==='paymentConfig'){const c=body.config;check(c&&typeof c.manualEnabled==='boolean'&&['bankName','bankAccount','bankHolder','instructions'].every(k=>typeof c[k]==='string'&&c[k].length<=(k==='instructions'?500:100)),'Thông tin ngân hàng không hợp lệ.');check(!c.manualEnabled||[c.bankName,c.bankAccount,c.bankHolder].every(v=>v.trim()),'Nhập đủ ngân hàng, số tài khoản và chủ tài khoản.');const after={manualEnabled:c.manualEnabled,bankName:c.bankName.trim(),bankAccount:c.bankAccount.trim(),bankHolder:c.bankHolder.trim(),instructions:c.instructions.trim()};await db().batch([db().prepare("INSERT INTO rpg_commerce_config(id,data) VALUES('main',?) ON CONFLICT(id) DO UPDATE SET data=excluded.data").bind(JSON.stringify(after)),audit('paymentConfig',why,{before:await commerceConfig(),after})]);return{notice:'Đã lưu thông tin chuyển khoản.'};}
 if(body.action==='topupApprove'){const reference=String(body.reference||'').trim().toUpperCase();check(/^[A-Z0-9_-]{4,100}$/.test(reference),'Nhập mã giao dịch ngân hàng thật (4–100 chữ hoặc số).');try{return await creditOrder(String(body.orderId),'manual','bank:'+reference,why);}catch(e){if(e instanceof GameError)throw new AdminError(e.message);throw e;}}
 if(body.action==='topupReject'){const order:any=await db().prepare('SELECT * FROM rpg_payment_orders WHERE id=?').bind(String(body.orderId)).first();check(order?.method==='manual'&&order.status==='pending','Chỉ từ chối yêu cầu chuyển khoản đang chờ.');const token=crypto.randomUUID(),now=Date.now();await db().batch([db().prepare("UPDATE rpg_payment_orders SET status='rejected',review_note=?,resolved_at=?,decision_token=? WHERE id=? AND status='pending'").bind(why,now,token,order.id),db().prepare("INSERT INTO rpg_admin_audit(action,target,reason,details,created_at) SELECT 'topupReject',NULL,?,?,? WHERE EXISTS(SELECT 1 FROM rpg_payment_orders WHERE id=? AND status='rejected' AND decision_token=?)").bind(why,JSON.stringify({orderId:order.id}),now,order.id,token)]);const result:any=await db().prepare('SELECT decision_token FROM rpg_payment_orders WHERE id=?').bind(order.id).first();if(result.decision_token!==token)throw new AdminError('Yêu cầu vừa được xử lý. Làm mới danh sách.',409);return{notice:'Đã từ chối yêu cầu.'};}
 throw new AdminError('Thao tác giao dịch không hợp lệ.');
}
