import {db,hydrate,save,type Session} from './database';
import {stats,makeItem} from './model';
import {MAPS,CLASSES,CURRENCIES,SLOTS,QUALITIES,BOOKS,PETS,MOUNTS} from './catalog';
import {AdminError,requireAdmin,sameOrigin} from './admin-auth';
import {serverSettings,clearSettingsCache} from './server-settings';
import {rankingHolders} from './leaderboard';
function rule(condition:unknown,message:string):asserts condition{if(!condition)throw new AdminError(message);}
function integer(value:unknown,min:number,max:number,label:string){rule(typeof value==='number'&&Number.isSafeInteger(value)&&value>=min&&value<=max,label+' ngoài giới hạn.');return value as number;}
function reason(body:any){rule(typeof body.reason==='string'&&body.reason.trim().length>=3&&body.reason.length<=200,'Ghi lý do từ 3 đến 200 ký tự.');return body.reason.trim();}
function audit(action:string,target:string|null,why:string,details:unknown){return db().prepare('INSERT INTO rpg_admin_audit(action,target,reason,details,created_at) VALUES(?,?,?,?,?)').bind(action,target,why,JSON.stringify(details),Date.now());}
export async function adminView(req:Request){await requireAdmin(req);const url=new URL(req.url),id=url.searchParams.get('player');if(id){const row:any=await db().prepare('SELECT * FROM rpg_profiles WHERE id=?').bind(id).first();rule(row,'Không tìm thấy nhân vật.');return{player:{id:row.id,profile:await hydrate(id,JSON.parse(row.data)),version:row.version},control:await db().prepare('SELECT * FROM rpg_admin_controls WHERE owner=?').bind(id).first()};}
 const search=(url.searchParams.get('search')||'').slice(0,80),page=integer(Number(url.searchParams.get('page')||0),0,100000,'Trang');
 const [players,total,logs]=await Promise.all([db().prepare('SELECT p.id,p.name,p.realm,p.power,p.map_id,p.last_seen,COALESCE(c.banned_until,0) AS banned_until FROM rpg_profiles p LEFT JOIN rpg_admin_controls c ON c.owner=p.id WHERE LOWER(p.name) LIKE ? ORDER BY p.last_seen DESC,p.id LIMIT 30 OFFSET ?').bind('%'+search.toLowerCase()+'%',page*30).all(),db().prepare('SELECT COUNT(*) AS count FROM rpg_profiles WHERE LOWER(name) LIKE ?').bind('%'+search.toLowerCase()+'%').first<any>(),db().prepare('SELECT id,action,target,reason,details,created_at FROM rpg_admin_audit ORDER BY id DESC LIMIT 50').all()]);
 return{players:players.results,total:total?.count||0,page,logs:logs.results,settings:await serverSettings(),catalog:{maps:MAPS,classes:CLASSES,currencies:CURRENCIES,slots:SLOTS,qualities:QUALITIES,books:BOOKS,pets:PETS,mounts:MOUNTS}};
}
export async function adminAction(req:Request,body:any){sameOrigin(req);await requireAdmin(req);rule(body&&typeof body==='object'&&!Array.isArray(body),'Yêu cầu không hợp lệ.');const why=reason(body),action=String(body.action||'');
 if(action==='settings'){const p=body.settings;rule(p&&typeof p==='object'&&Object.keys(p).every(k=>['maintenance','announcement','xpMultiplier'].includes(k)),'Thiết lập không hợp lệ.');rule(typeof p.maintenance==='boolean'&&typeof p.announcement==='string'&&p.announcement.length<=300&&typeof p.xpMultiplier==='number'&&Number.isFinite(p.xpMultiplier)&&p.xpMultiplier>=.1&&p.xpMultiplier<=10,'Thông báo tối đa 300 ký tự, hệ số tu vi từ 0.1 đến 10.');const before=await serverSettings();await db().batch([db().prepare("INSERT INTO rpg_server_settings(id,data) VALUES('main',?) ON CONFLICT(id) DO UPDATE SET data=excluded.data").bind(JSON.stringify(p)),audit(action,null,why,{before,after:p})]);clearSettingsCache();return{notice:'Đã lưu thiết lập máy chủ.'};}
 rule(['edit','grantItem','heal','ban','unban','mute','unmute'].includes(action),'Thao tác quản trị không hợp lệ.');const id=String(body.playerId||''),now=Date.now();rule(/^[\w-]{1,80}$/.test(id),'ID nhân vật không hợp lệ.');
 const row:any=await db().prepare('UPDATE rpg_profiles SET locked_until=? WHERE id=? AND locked_until<? RETURNING *').bind(now+15000,id,now).first();if(!row){const exists=await db().prepare('SELECT id FROM rpg_profiles WHERE id=?').bind(id).first();throw new AdminError(exists?'Nhân vật đang thao tác. Thử lại sau.':'Không tìm thấy nhân vật.',exists?409:404);}
 try{
  if(['ban','unban','mute','unmute'].includes(action)){const duration=action==='ban'||action==='mute'?integer(body.hours,1,8760,'Số giờ'):0;const old:any=await db().prepare('SELECT * FROM rpg_admin_controls WHERE owner=?').bind(id).first();const ban=action==='ban'?now+duration*3600000:action==='unban'?0:old?.banned_until||0,mute=action==='mute'?now+duration*3600000:action==='unmute'?0:old?.muted_until||0;await db().batch([db().prepare('INSERT INTO rpg_admin_controls(owner,banned_until,muted_until,reason) VALUES(?,?,?,?) ON CONFLICT(owner) DO UPDATE SET banned_until=excluded.banned_until,muted_until=excluded.muted_until,reason=excluded.reason').bind(id,ban,mute,why),audit(action,id,why,{bannedUntil:ban,mutedUntil:mute})]);return{notice:'Đã cập nhật hạn chế nhân vật.'};}
  const s:Session={id,cookie:'',version:row.version,lastSeen:row.last_seen,profile:await hydrate(id,JSON.parse(row.data))},p=s.profile,before=structuredClone(p),statements:D1PreparedStatement[]=[];
  if(action==='edit'){const patch=body.patch;rule(patch&&typeof patch==='object'&&!Array.isArray(patch),'Thiếu dữ liệu chỉnh sửa.');rule(Object.keys(patch).every(k=>['name','classId','realm','star','xp','mapId','potions','shieldDan','coins','books','petId','mountId'].includes(k)),'Có trường không được phép chỉnh.');
   if(patch.name!==undefined){rule(typeof patch.name==='string'&&patch.name.trim().length>=2&&patch.name.length<=22,'Đạo danh dài từ 2 đến 22 ký tự.');p.name=patch.name.trim();}
   if(patch.classId!==undefined){rule(CLASSES.some(c=>c.id===patch.classId),'Môn phái không hợp lệ.');p.classId=patch.classId;}
   for(const [key,min,max] of [['realm',0,44],['star',1,10],['xp',0,1000000000],['potions',0,99999],['shieldDan',0,99999]] as const)if(patch[key]!==undefined)(p as any)[key]=integer(patch[key],min,max,key);
   if(patch.mapId!==undefined){const map=MAPS[integer(patch.mapId,0,53,'Map')];rule(p.realm>=map.minRealm,'Cảnh giới chưa đủ cho map đã chọn.');if(p.mapId!==map.id){p.mapId=map.id;p.x=620;p.y=550;p.dungeon=null;p.encounters={};}if(!p.visited.includes(map.id))p.visited.push(map.id);}
   rule(p.realm>=MAPS[p.mapId].minRealm,'Chọn map phù hợp với cảnh giới mới.');
   if(patch.coins!==undefined){rule(patch.coins&&typeof patch.coins==='object'&&Object.keys(patch.coins).every(k=>CURRENCIES.some(c=>c.id===k)),'Loại tiền không hợp lệ.');for(const c of CURRENCIES)if(patch.coins[c.id]!==undefined)p.coins[c.id]=integer(patch.coins[c.id],0,1000000000,c.name);}
   if(patch.books!==undefined){rule(Array.isArray(patch.books)&&patch.books.length<=BOOKS.length&&patch.books.every((id:unknown)=>Number.isInteger(id)&&BOOKS.some(b=>b.id===id)),'Bí tịch không hợp lệ.');p.books=[...new Set<number>(patch.books)];}
   for(const [key,list,owned] of [['petId',PETS,'pets'],['mountId',MOUNTS,'mounts']] as const)if(patch[key]!==undefined){rule(patch[key]===null||Number.isInteger(patch[key])&&list.some(d=>d.id===patch[key]),'Đồng hành không hợp lệ.');p[key]=patch[key];if(patch[key]!==null&&!p[owned].some(c=>c.id===patch[key]))p[owned].push({id:patch[key],level:1});}
   statements.push(audit(action,id,why,{before:{name:before.name,classId:before.classId,realm:before.realm,star:before.star,xp:before.xp,mapId:before.mapId,coins:before.coins},after:patch}));
  }else if(action==='grantItem'){rule(p.inventory.length<300,'Hành trang đã đủ 300 vật phẩm.');rule(SLOTS.some(s=>s.id===body.slot),'Ô trang bị không hợp lệ.');const item=makeItem(body.slot,integer(body.quality,0,7,'Phẩm chất'),integer(body.rank,1,450,'Cấp vật phẩm'));statements.push(db().prepare('INSERT INTO rpg_items(uid,owner,data) VALUES(?,?,?)').bind(item.uid,id,JSON.stringify(item)),audit(action,id,why,{name:item.name,quality:item.quality,rank:item.rank}));
  }else statements.push(audit('heal',id,why,{hp:p.hp,mp:p.mp}));
  if(action==='heal'){const st=stats(p);p.hp=st.hp;p.mp=st.mp;}
  await save(s,before,statements);await rankingHolders(true);return{notice:'Đã cập nhật nhân vật và ghi nhật ký.'};
 }finally{await db().prepare('UPDATE rpg_profiles SET locked_until=0 WHERE id=?').bind(id).run();}
}
