import {enemyPosition,monsterCamps} from './map-layout';
import {SECRETS} from './secrets';
export const REALMS=['Luyện Khí','Trúc Cơ','Kết Đan','Kim Đan','Nguyên Anh','Hóa Thần','Luyện Hư','Hợp Thể','Đại Thừa','Độ Kiếp','Bán Tiên','Địa Tiên','Thiên Tiên','Chân Tiên','Huyền Tiên','Kim Tiên','Thái Ất Kim Tiên','Đại La Kim Tiên','Tiên Quân','Tiên Vương','Tiên Hoàng','Tiên Đế','Tiên Tôn','Tiên Thánh','Chuẩn Đạo','Đạo Quân','Đạo Vương','Đạo Tôn','Đạo Tổ','Bán Thần','Hạ Thần','Trung Thần','Thượng Thần','Thiên Thần','Chân Thần','Thần Quân','Thần Vương','Thần Hoàng','Thần Đế','Thần Tôn','Thần Thánh','Cổ Thần','Sáng Thế','Vô Cực','Hồng Mông'];
export const WORLD_NAMES=['Hạ giới','Tiên giới','Thần giới'];
export const CLASSES=[{id:'sword',name:'Kiếm tu',attack:1.15,hp:1,icon:'Sword',description:'Kiếm ý sắc bén, cân bằng công thủ.'},{id:'body',name:'Thể tu',attack:.95,hp:1.4,icon:'Shield',description:'Khí huyết bền bỉ, phòng ngự cao.'},{id:'fist',name:'Quyền tu',attack:1.3,hp:1.1,icon:'Swords',description:'Quyền kình mạnh, bạo kích cao.'},{id:'spell',name:'Pháp tu',attack:1.2,hp:.9,icon:'Zap',description:'Pháp thuật diện rộng, linh lực dồi dào.'},{id:'spear',name:'Thương tu',attack:1.1,hp:1.15,icon:'Sword',description:'Thương lực vững, công thủ cân bằng.'},{id:'healer',name:'Y tu',attack:.9,hp:1.2,icon:'Heart',description:'Khí huyết dồi dào, bền bỉ khi tu hành.'}];
export const ROOTS=['Kim','Mộc','Thủy','Hỏa','Thổ','Lôi','Băng','Phong'];
export const RACES=['Nhân tộc','Yêu tộc','Linh tộc','Long tộc','Vu tộc','Thần duệ'];
export const CURRENCIES=[{id:'silver',name:'Ngân lượng',symbol:'銀',color:'#dfdfda'},{id:'stone',name:'Linh thạch',symbol:'◈',color:'#8cd4c7'},{id:'jade',name:'Tiên ngọc',symbol:'玉',color:'#c6a4e6'},{id:'merit',name:'Cống hiến',symbol:'宗',color:'#d4be81'},{id:'divine',name:'Thần tinh',symbol:'神',color:'#eb9f7d'}] as const;
export type Currency=typeof CURRENCIES[number]['id'];
export const QUALITIES=[{name:'Phàm',color:'#aab8b5',mult:1},{name:'Linh',color:'#85bd91',mult:1.35},{name:'Huyền',color:'#77b7e5',mult:1.8},{name:'Địa',color:'#ac8bd4',mult:2.4},{name:'Thiên',color:'#e5bf72',mult:3.1},{name:'Tiên',color:'#ed9574',mult:4},{name:'Thần',color:'#e17590',mult:5.2},{name:'Hỗn Độn',color:'#b9e9ed',mult:7}];
export const SLOTS=[{id:'weapon',name:'Vũ khí',icon:'Sword'},{id:'head',name:'Mũ',icon:'Shield'},{id:'chest',name:'Áo',icon:'Shield'},{id:'shoulder',name:'Hộ vai',icon:'Shield'},{id:'arms',name:'Hộ tay',icon:'Shield'},{id:'gloves',name:'Găng',icon:'Swords'},{id:'belt',name:'Đai',icon:'Gem'},{id:'pants',name:'Quần',icon:'Shield'},{id:'boots',name:'Giày',icon:'Shield'},{id:'neck',name:'Dây chuyền',icon:'Gem'},{id:'ring1',name:'Nhẫn trái',icon:'Gem'},{id:'ring2',name:'Nhẫn phải',icon:'Gem'},{id:'cloak',name:'Áo choàng',icon:'Shield'},{id:'charm',name:'Ngọc bội',icon:'Gem'},{id:'artifact',name:'Pháp bảo',icon:'Sparkles'},{id:'instrument',name:'Pháp khí',icon:'BookOpen'}] as const;
const lower=['Thanh Vân Môn','Trúc Lâm Sơn','Linh Khê Thôn','Hắc Phong Cốc','Hàn Đàm','Xích Viêm Sơn','Bạch Lộc Lâm','Cổ Kiếm Trủng','Tuyết Nguyệt Thành','Vạn Độc Đầm','Hoàng Sa Quan','Tử Vân Động','Thiên Lôi Phong','Lạc Tinh Hồ','U Minh Vực','Long Huyết Trì','Cửu U Thành','Thông Thiên Đài'];
const immortal=['Vân Hải Tiên Môn','Dao Trì','Bích Lạc Cung','Nguyệt Quang Lâm','Bạch Ngọc Thành','Thiên Hà Cổ Lộ','Thái Hư Đảo','Huyền Băng Tiên Cốc','Kim Ô Điện','Vạn Kiếm Tiên Sơn','Bồng Lai','Tử Vi Tinh Cung','Côn Lôn Tiên Cảnh','Thái Ất Linh Trì','Đại La Thánh Địa','Tiên Đế Lăng','Thiên Mệnh Đài','Quy Khư Tiên Môn'];
const divine=['Thần Khải Điện','Tinh Hà Thần Vực','Hỗn Nguyên Cốc','Vĩnh Dạ Thành','Long Thần Cung','Phượng Hoàng Đài','Thần Mộc Chi Lâm','Hư Không Cổ Lộ','Chân Thần Chi Mộ','Thiên Mệnh Thần Sơn','Vạn Thần Điện','Cổ Thần Di Tích','Sáng Thế Linh Hải','Luân Hồi Thần Vực','Hỗn Độn Biên Cảnh','Vô Cực Thánh Điện','Thiên Ngoại Thiên','Đại Đạo Chi Đỉnh'];
export type MapDef={id:number;name:string;world:number;minRealm:number;biome:string;seed:number;description:string;dungeon:boolean};
const biomes=['courtyard','bamboo','village','night','ice','volcano','forest','ruins','snow','swamp','desert','cave','storm','lake','underworld','blood','fortress','summit'];
export const MAPS:MapDef[]=[...lower,...immortal,...divine].map((name,id)=>({id,name,world:Math.floor(id/18),minRealm:id===0?0:Math.floor(id/18)*15+Math.min(14,Math.floor((id%18)*.84)),biome:biomes[id%18],seed:id*7919+113,description:Math.floor(id/18)===0?'Linh sơn, cổ lộ và dấu tích phàm trần.':Math.floor(id/18)===1?'Mây tiên vạn dặm, cơ duyên và tiên thú.':'Thần vực cổ xưa, thiên mệnh và đại đạo.',dungeon:id%3===2}));
const surnames=['Lâm','Diệp','Tô','Mộ','Tần','Bạch','Tiêu','Lục','Hàn','Vân','Ninh','Dương'];
const names=['Thanh Huyền','Linh Nhi','Vân Phong','Nguyệt Chi','Huyền Trạch','Tử Yên','Thiên Hành','Mộng Ly','Trường An','Hàn Sương','Mặc Vũ','Dao Hoa'];
export type NpcDef={id:number;map:number;name:string;role:'elder'|'merchant';female:boolean;appearance:number;pose:number;dialogue:string};
export const NPCS:NpcDef[]=Array.from({length:108},(_,id)=>({id,map:Math.floor(id/2),name:`${surnames[Math.floor(id/12)]} ${names[id%12]}`,role:id%2===0?'elder':'merchant',female:id%2===1,appearance:id,pose:id%8,dialogue:id%2===0?'Tiên lộ không chỉ nằm ở kiếm lực. Hãy giúp dân chúng, tìm cổ tịch và giữ vững đạo tâm.':'Đạo hữu đi đường xa, hãy mang theo linh đan. Nếu có cơ duyên, chúng ta lại gặp nhau.'}));
const species=['Linh Hồ','Ảnh Lang','Sơn Trư','Thạch Yêu','Độc Chu','Hàn Xà','Ma Ưng','Hỏa Linh','Lôi Thú','Mộc Tinh','Huyết Ngưu','U Hồn','Long Vệ','Ma Quân'];
const prefixes=['Thanh','Hắc','Bạch','Xích','Tử','U','Kim','Ngân','Huyền','Lôi','Băng','Huyết','Tinh','Cổ'];
export type EnemyDef={id:string;map:number;index:number;name:string;kind:number;rank:number;elite:boolean;boss:boolean;appearance:number;x:number;y:number;campId:number;spawnOf?:string;maxHp:number;attack:number;xp:number};
export const ENEMIES:EnemyDef[]=MAPS.flatMap(map=>Array.from({length:14},(_,index)=>{const boss=index===13,rank=map.minRealm*10+Math.max(1,index%5+1),scale=1+rank*.24;return{id:`m${map.id}-${index}`,map:map.id,index,name:`${prefixes[(map.id+index)%14]} ${species[index]}${boss?' · Trấn thủ':index>=10?' · Tinh anh':''}`,kind:index%6,rank,elite:index>=10,boss,appearance:map.id*14+index,...enemyPosition(map.id,index),maxHp:Math.round((boss?2200:index>=10?440:150)*scale),attack:Math.round((boss?32:10)*scale),xp:Math.round((boss?170:index>=10?40:22)*scale)};}));
// Keep each original species ID as the quest target; extra bodies respawn independently.
for(const map of MAPS){for(const camp of monsterCamps(map.id)){const originals=ENEMIES.filter(e=>e.map===map.id&&e.campId===camp.id);for(let seat=originals.length;seat<5;seat++){const source=originals.find(e=>!e.boss)||originals[0];ENEMIES.push({...source,id:source.id+'-camp-'+seat,spawnOf:source.id,boss:false,elite:camp.boss||source.elite,name:source.name.replace(' · Trấn thủ',' · Hộ vệ'),...enemyPosition(map.id,source.index,seat),maxHp:source.boss?Math.round(source.maxHp/5):source.maxHp,attack:source.boss?Math.round(source.attack/3):source.attack,xp:source.boss?Math.round(source.xp/5):source.xp});}}}
export const WORLD_BOSSES=[{id:'wb-lower',name:'Cửu U Ma Long',map:12,world:0,maxHp:18000,rank:100,appearance:810},{id:'wb-immortal',name:'Thái Cổ Kim Ô',map:30,world:1,maxHp:95000,rank:260,appearance:811},{id:'wb-divine',name:'Hỗn Độn Thần Tôn',map:48,world:2,maxHp:320000,rank:420,appearance:812}];
export type QuestDef={id:string;map:number;name:string;hidden:boolean;type:'kill'|'boss'|'gather'|'talk'|'visit'|'dungeon'|'discover'|'secret'|'ritual';target:string;count:number;rewardXp:number;rewardStone:number;rewardBook?:number;rewardPotions?:number;description:string};
export const QUESTS:QuestDef[]=MAPS.flatMap(map=>Array.from({length:13},(_,i)=>{const type:QuestDef['type']=i<6?'kill':i<8?'gather':i===8?'talk':i===9?'visit':i===10?'boss':i===11?'dungeon':'discover';const count=type==='kill'?3+i:type==='gather'?4+i:1;const target=type==='kill'?`m${map.id}-${i}`:type==='gather'?`${map.id}:${i===6?'herb':'ore'}`:type==='talk'?String(map.id*2):String(map.id);const label=type==='kill'?`Trấn áp ${species[i]}`:type==='gather'?['Thu thập linh thảo','Tìm linh khoáng'][i-6]:type==='talk'?'Lời nhắn trưởng lão':type==='visit'?'Khảo sát linh địa':type==='boss'?'Bình định ma khí':type==='dungeon'?'Thử thách cổ cảnh':'Bí mật dưới cổ thụ';return {id:`q${map.id}-${i}`,map:map.id,name:`${map.name} · ${label}`,hidden:i===12,type,target,count,rewardXp:Math.round((35+i*8)*(1+map.minRealm)),rewardStone:30+i*10+map.minRealm*15,description:i===12?'Bia đá vô danh bên cây cổ thụ dường như đang phát sáng.':type==='kill'?`Tiêu diệt ${count} ${species[i]} tại ${map.name}.`:type==='gather'?`Thu thập ${count} tài nguyên tại linh địa.`:type==='talk'?'Tìm trưởng lão tại bản đồ này và trò chuyện.':type==='visit'?`Đặt chân đến ${map.name}.`:type==='boss'?'Đánh bại boss trấn thủ bản đồ.':'Hoàn thành 3 đợt thử thách phụ bản ở bản đồ này.'};}));
// A hand-written opening chapter reuses stable quest IDs for existing saves.
export const STORY_IDS=['q0-8','q0-6','q0-12','q0-0','q0-10','story-seal','story-bamboo','story-message'];
export function npcPosition(n: Pick<NpcDef,'role'>){return n.role==='elder'?{x:660,y:520}:{x:660,y:740};}
Object.assign(NPCS[0],{name:'Lâm Thanh Huyền',dialogue:'Phong ấn Thanh Vân đang suy yếu. Trước khi cầm kiếm, hãy học cứu người. Tìm Linh Nhi ở vườn thuốc, rồi mang linh thảo đến bia cổ để nghe lời tiên nhân.'});
Object.assign(NPCS[1],{name:'Lâm Linh Nhi',dialogue:'Ba nhánh Thanh Tâm Thảo có thể làm dịu linh mạch. Hái thảo trong vườn rồi đến bia cổ. Chớ vội bước sang phía đông khi chưa hiểu lời trưởng lão.'});
const opening:Partial<QuestDef>[]=[
 {name:'Thanh Vân Môn · I. Một niệm nhập đạo',description:'Bạn tỉnh dậy dưới chân Thanh Vân Môn, mang một mảnh ngọc vỡ. Gặp trưởng lão Lâm Thanh Huyền ở sân giữa để hỏi về tiếng gọi trong ngọc.',hidden:false},
 {name:'Thanh Vân Môn · II. Thanh Tâm cứu thế',count:3,description:'Linh Nhi phát hiện linh mạch nhiễm ma khí. Thu thập 3 nhánh Thanh Tâm Thảo trong vườn thuốc; cứu người là bước đầu của tiên đạo.'},
 {name:'Thanh Vân Môn · III. Lời thề dưới bia cổ',hidden:false,description:'Chạm vào bia cổ phía tây. Tàn niệm tổ sư kể rằng mảnh ngọc của bạn là chìa khóa phong ấn Cửu U. Giữ đạo tâm, đừng để sức mạnh che mắt.'},
 {name:'Thanh Vân Môn · IV. Kiếm đầu hộ sơn',count:3,description:'Bia cổ thức tỉnh, ma khí hóa thành Thanh Linh Hồ ở rìa phía đông. Đánh bại 3 con để bảo vệ vườn thuốc và ổn định linh mạch.'},
 {name:'Thanh Vân Môn · V. Phong ấn hồi sinh',description:'Cổ Ma Quân đã lộ diện phía đông. Tu luyện, chuẩn bị linh đan rồi đánh bại hắn để khôi phục phong ấn. Tiên lộ của bạn từ đây mới thực sự bắt đầu.'},
];
STORY_IDS.slice(0,5).forEach((id,i)=>Object.assign(QUESTS.find(q=>q.id===id)!,opening[i]));
QUESTS.push(
 {id:'story-seal',map:0,name:'Thanh Vân Môn · VI. Ngọc ấn hồi quang',hidden:false,type:'ritual',target:'0:seal',count:1,rewardXp:160,rewardStone:90,rewardPotions:2,description:'Cổ Ma Quân đã tan nhưng ngọc ấn vẫn rạn nứt. Đến Tụ Linh Đài giữa sân, đặt mảnh ngọc vào pháp trận để phục hồi phong ấn. Ánh sao sẽ chỉ đường đến người giữ mảnh ngọc thứ hai.'},
 {id:'story-bamboo',map:1,name:'Thanh Vân Môn · VII. Tiếng gọi từ Trúc Lâm',hidden:false,type:'visit',target:'1',count:1,rewardXp:190,rewardStone:110,description:'Trong ngọc ấn vang lên một khúc tiêu. Qua cổng đến Trúc Lâm Sơn, tìm nguồn linh khí mang cùng dấu ấn của tổ sư. Cổng mở cho mọi đệ tử vừa nhập đạo.'},
 {id:'story-message',map:1,name:'Thanh Vân Môn · VIII. Một lời hẹn ngàn năm',hidden:false,type:'talk',target:'2',count:1,rewardXp:230,rewardStone:140,rewardBook:0,description:'Tìm Diệp Vân Phong giữa Trúc Lâm. Ông nhận ra mảnh ngọc và kể về người đã phong ấn Cửu U bằng sinh mệnh. Nhận Thanh Vân Kiếm Quyết và lời hẹn: khi đạo tâm vững vàng, trở lại để nối tiếp truyền thừa.'},
);
Object.assign(MAPS[0],{name:'Thanh Vân Tân Thôn',biome:'village',description:'Khu tân thủ yên bình dưới Thanh Vân Môn. Gặp trưởng lão, học hái linh thảo và luyện kiếm; yêu thú chỉ xuất hiện ở rìa đông khi cốt truyện mở khóa.'});
Object.assign(NPCS[2],{name:'Diệp Vân Phong',dialogue:'Ta đã chờ mảnh ngọc này ngàn năm. Tổ sư hy sinh để khép Cửu U, nhưng phong ấn cần một người giữ đạo tâm. Mang Thanh Vân Kiếm Quyết mà tu học; mạnh lên để bảo vệ, chứ đừng để linh lực nuốt mất lòng mình.'});
export function questUnlocked(claimed:string[],q:QuestDef){const i=STORY_IDS.indexOf(q.id);return i<=0||claimed.includes(STORY_IDS[i-1]);}
QUESTS.push(...SECRETS.map(s=>({id:s.id,map:s.map,name:`${MAPS[s.map].name} · ${s.name}`,hidden:true,type:'secret' as const,target:s.id,count:1,rewardXp:80*(s.realm+1),rewardStone:s.stone,description:s.story})));
export const BOOKS=Array.from({length:72},(_,id)=>({id,name:`${['Thanh Vân','Huyền Thiên','Thái Hư','Cửu Chuyển','Đại La','Hỗn Nguyên','Vạn Tượng','Vô Cực','Bích Lạc'][Math.floor(id/8)]} ${['Kiếm Quyết','Tâm Kinh','Lôi Pháp','Kim Thân','Quyền Kinh','Thần Hành','Băng Chú','Đan Kinh'][id%8]}`,kind:id%3===0?'Bí tịch':id%3===1?'Cổ tịch':'Truyền thừa',minRealm:Math.floor(id/8)*5,price:90+id*35,bonus:4+id,description:'Lĩnh ngộ tăng kiếm lực, khí huyết và lực chiến. Có thể tu học một lần.'}));
export const PETS=Array.from({length:24},(_,id)=>({id,name:`${['Linh','Nguyệt','Hỏa','Huyền','Tinh','Thần'][Math.floor(id/4)]} ${['Hồ','Miêu','Điểu','Quy'][id%4]}`,price:120+id*65,minRealm:Math.floor(id/4)*6,appearance:id,bonus:10+id*4}));
export const MOUNTS=Array.from({length:18},(_,id)=>({id,name:`${['Bạch','Thanh','Xích','Kim','Tử','Cổ'][Math.floor(id/3)]} ${['Lộc','Long','Hạc'][id%3]}`,price:180+id*90,minRealm:Math.floor(id/3)*7,appearance:40+id,bonus:12+id*5}));
export {TITLES} from './titles';
export const ACHIEVEMENTS=Array.from({length:60},(_,id)=>({id,name:`${['Trảm Yêu','Du Hành','Bình Ma','Vấn Đạo','Tàng Kinh','Tiên Duyên'][Math.floor(id/10)]} · ${id%10+1}`,type:['kill','visit','boss','realm','book','quest'][Math.floor(id/10)],target:(id%10+1)*[20,5,2,4,6,30][Math.floor(id/10)],reward:30+id*8}));
export const TUTORIAL=[{id:0,name:'Gặp trưởng lão',description:'Bấm trưởng lão cạnh sân môn phái để trò chuyện.'},{id:1,name:'Nhận nhiệm vụ',description:'Nhận nhiệm vụ từ trưởng lão hoặc mở Nhật ký.'},{id:2,name:'Tiêu diệt yêu thú',description:'Chọn yêu thú rồi bấm 1–4, hoặc bật Tự chiến.'},{id:3,name:'Trang bị đầu tiên',description:'Mở Hành trang, bấm đồ và chọn Trang bị.'},{id:4,name:'Điều tức và đột phá',description:'Tu luyện ở vùng an toàn, sau đó thử đột phá.'},{id:5,name:'Khám phá tam giới',description:'Mở Bản đồ, dịch chuyển đến Trúc Lâm Sơn.'},{id:6,name:'Cơ duyên ẩn',description:'Tìm Bia cổ có dấu ? để khám phá nhiệm vụ ẩn.'},{id:7,name:'Đồng hành',description:'Đến Linh thú các để thu nhận pet hoặc thú cưỡi.'}];
export const EVENTS=[{id:'tide',name:'Thú triều',period:600,duration:180,description:'Mỗi 10 phút, yêu thú mạnh hơn 15%; tu vi và linh thạch tăng 50%.'},{id:'insight',name:'Tiên vận',period:900,duration:240,description:'Mỗi 15 phút, điều tức nhận gấp đôi tu vi.'},{id:'boss',name:'Boss thế giới',period:600,duration:600,description:'Ma Long, Kim Ô và Thần Tôn hồi sinh 10 phút sau khi bị hạ.'}];
export const CATALOG_COUNTS={maps:MAPS.length,npcs:NPCS.length,quests:QUESTS.length,enemies:ENEMIES.length+WORLD_BOSSES.length,realms:REALMS.length,stars:10};
