import {requestOrigin,secureRequest} from '@/lib/request-origin';
import {upgrade} from './immortal';
import {gameDb} from '@/lib/game-db';
import {newProfile,makeItem,stats,type Profile,type Item} from './model';
import {CURRENCIES,WORLD_BOSSES} from './catalog';
export class GameError extends Error {}
export const db=()=>gameDb();
export type Session={id:string;cookie:string;profile:Profile;version:number;lastSeen:number};
export async function actor(req:Request){let id=req.headers.get('cookie')?.match(/(?:^|;\s*)vt_session=([a-f0-9-]{36})/)?.[1];let cookie='';if(!id){id=crypto.randomUUID();cookie=`vt_session=${id}; Path=/; HttpOnly; SameSite=Lax; Max-Age=31536000${secureRequest(req)?'; Secure':''}`;}return{id,cookie};}
async function hashKey(value:string){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,'0')).join('').slice(0,32);}
export async function session(req:Request):Promise<Session>{const {id,cookie}=await actor(req);let row:any=await db().prepare('SELECT * FROM rpg_profiles WHERE id=?').bind(id).first();if(!row){const old:any=await db().prepare('SELECT * FROM players WHERE id=?').bind(id).first();const p=newProfile(old||{});const uid=await hashKey(id+':weapon'),chest=await hashKey(id+':chest'),head=await hashKey(id+':head');const items=[makeItem('weapon',old?.equipment?1:0,1,uid),makeItem('chest',0,1,chest),makeItem('head',0,1,head)];p.inventory=items;p.equipped={weapon:uid,chest};const st=stats(p);p.hp=st.hp;p.mp=st.mp;await db().batch([db().prepare('INSERT OR IGNORE INTO rpg_profiles(id,data,name,power,realm,map_id,last_seen) VALUES(?,?,?,?,?,?,?)').bind(id,JSON.stringify(p),p.name,st.power,p.realm,p.mapId,Date.now()),...CURRENCIES.map(c=>db().prepare('INSERT OR IGNORE INTO rpg_wallets(id,owner,currency,balance) VALUES(?,?,?,?)').bind(id+':'+c.id,id,c.id,p.coins[c.id])),...items.map(item=>db().prepare('INSERT OR IGNORE INTO rpg_items(uid,owner,data,equipped_slot) VALUES(?,?,?,?)').bind(item.uid,id,JSON.stringify(item),item.slot==='head'?null:item.slot))]);row=await db().prepare('SELECT * FROM rpg_profiles WHERE id=?').bind(id).first();}
 const profile=await hydrate(id,JSON.parse(row.data));return{id,cookie,profile,version:row.version,lastSeen:row.last_seen};}
export async function hydrate(id:string,p:Profile){upgrade(p);const [wallet,items]=await Promise.all([db().prepare('SELECT currency,balance FROM rpg_wallets WHERE owner=?').bind(id).all(),db().prepare('SELECT uid,data,equipped_slot FROM rpg_items WHERE owner=?').bind(id).all()]);p.coins={silver:0,stone:0,jade:0,merit:0,divine:0};for(const w of wallet.results as any[])p.coins[w.currency as keyof typeof p.coins]=w.balance;p.inventory=(items.results as any[]).map(i=>JSON.parse(i.data));p.equipped={};for(const i of items.results as any[])if(i.equipped_slot)p.equipped[i.equipped_slot]=i.uid;return p;}
export function persisted(p:Profile){const {coins,inventory,equipped,...data}=p;return JSON.stringify(data);}
let seededAt=0;
export async function initBosses(){if(Date.now()-seededAt>60000){await db().batch(['Thanh Vân Môn','Bích Lạc Cung','Thiên Cương Tông'].map((name,i)=>db().prepare('INSERT OR IGNORE INTO rpg_guilds(id,kind,name,leader,created_at) VALUES(?,?,?,?,?)').bind('sect-'+i,'sect',name,'world',i)));await db().batch(WORLD_BOSSES.map(b=>db().prepare('INSERT OR IGNORE INTO rpg_world_bosses(id,hp,max_hp) VALUES(?,?,?)').bind(b.id,b.maxHp,b.maxHp)));seededAt=Date.now();}await db().prepare('UPDATE rpg_world_bosses SET hp=max_hp,cycle=cycle+1,respawn_at=0 WHERE hp=0 AND respawn_at<=?').bind(Date.now()).run();}
export async function save(s:Session,before:Profile,statements:D1PreparedStatement[]=[]){const p=s.profile,st=stats(p);p.hp=Math.min(p.hp,st.hp);p.mp=Math.min(p.mp,st.mp);await db().batch([db().prepare('UPDATE rpg_profiles SET data=?,version=version+1,name=?,power=?,realm=?,map_id=?,last_seen=? WHERE id=? AND version=?').bind(persisted(p),p.name,st.power,p.realm,p.mapId,Date.now(),s.id,s.version),...CURRENCIES.filter(c=>p.coins[c.id]!==before.coins[c.id]).map(c=>db().prepare('UPDATE rpg_wallets SET balance=balance+? WHERE owner=? AND currency=?').bind(p.coins[c.id]-before.coins[c.id],s.id,c.id)),...statements]);s.profile=await hydrate(s.id,p);s.version++;}
export async function buyListing(s:Session,listingId:string){const listing:any=await db().prepare('SELECT * FROM rpg_listings WHERE id=?').bind(listingId).first();if(!listing||listing.status!=='open')throw new GameError('Tin rao đã hết hiệu lực.');if(listing.owner===s.id)throw new GameError('Không thể mua đồ của chính mình.');if(s.profile.coins[listing.currency as keyof Profile['coins']]<listing.price)throw new GameError('Không đủ tiền để mua vật phẩm.');const now=Date.now(),won='id=? AND buyer_id=? AND sold_at=? AND settled=0';await db().batch([
 db().prepare('UPDATE rpg_listings SET status=\'sold\',buyer_id=?,sold_at=? WHERE id=? AND status=\'open\' AND EXISTS(SELECT 1 FROM rpg_wallets WHERE owner=? AND currency=rpg_listings.currency AND balance>=rpg_listings.price)').bind(s.id,now,listingId,s.id),
 db().prepare(`UPDATE rpg_wallets SET balance=balance-? WHERE owner=? AND currency=? AND EXISTS(SELECT 1 FROM rpg_listings WHERE ${won})`).bind(listing.price,s.id,listing.currency,listingId,s.id,now),
 db().prepare(`UPDATE rpg_wallets SET balance=balance+? WHERE owner=? AND currency=? AND EXISTS(SELECT 1 FROM rpg_listings WHERE ${won})`).bind(listing.price,listing.owner,listing.currency,listingId,s.id,now),
 db().prepare(`UPDATE rpg_items SET owner=?,equipped_slot=NULL WHERE uid=? AND owner=? AND EXISTS(SELECT 1 FROM rpg_listings WHERE ${won})`).bind(s.id,listing.item_uid,listing.owner,listingId,s.id,now),
 db().prepare(`UPDATE rpg_listings SET settled=1 WHERE ${won}`).bind(listingId,s.id,now),
 ]);const result:any=await db().prepare('SELECT buyer_id,sold_at,settled FROM rpg_listings WHERE id=?').bind(listingId).first();if(result.buyer_id!==s.id||result.sold_at!==now||result.settled!==1)throw new GameError('Một đạo hữu khác đã mua món này.');s.profile=await hydrate(s.id,s.profile);return listing;}

export async function reload(s:Session){const row:any=await db().prepare("SELECT * FROM rpg_profiles WHERE id=?").bind(s.id).first();return {...s,profile:await hydrate(s.id,JSON.parse(row.data)),version:row.version,lastSeen:row.last_seen};}
