import {NPCS,ENEMIES,WORLD_BOSSES,MAPS,BOOKS,SLOTS,TUTORIAL,REALMS,CLASSES} from './catalog';
import {RECIPES,DHARMAS,dharmaUnlocked} from './immortal';
import {SECRETS,secretKnown} from './secrets';
import type {Profile} from './model';
export type CodexCategory='npc'|'enemy'|'map'|'item'|'book'|'faction'|'secret'|'guide';
export const CODEX_CATEGORIES=[{id:'npc',name:'Nhân vật'},{id:'enemy',name:'Quái vật'},{id:'map',name:'Vùng đất'},{id:'item',name:'Vật phẩm'},{id:'book',name:'Võ học'},{id:'faction',name:'Thế lực'},{id:'secret',name:'Bí ẩn'},{id:'guide',name:'Chỉ dẫn'}] as const;
export type CodexEntry={id:string;category:CodexCategory;name:string;description:string;known:boolean;map?:number;art?:{npc?:number;enemy?:number;dharma?:number;icon?:string};facts:[string,string][];links:{label:string;panel:'quests'|'secrets'|'dharma'|'library'|'inventory'|'alchemy'|'guilds'|'cultivation'|'meridians'|'party'|'maps'|'tutorial'|'bosses'|'character'}[]};
export function normalizeCodexText(text:string){return text.normalize('NFD').toLowerCase().replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d');}
export function codexEntries(p:Profile):CodexEntry[]{return [
 ...NPCS.map(n=>({id:'npc-'+n.id,category:'npc' as const,name:n.name,description:n.dialogue,known:p.talked.includes(n.id),map:n.map,art:{npc:n.id},facts:[['Gốc gác',MAPS[n.map].name],['Vai trò',n.role==='elder'?'Trưởng lão · truyền nhiệm vụ':'Đan sư · tiên duyên'],['Gặp mặt',n.role==='elder'?'Sân giữa · 660, 520':'Vườn thuốc · 660, 740']] as [string,string][],links:[{label:'Nhật ký nhiệm vụ',panel:'quests' as const},{label:'Cơ duyên trong vùng',panel:'secrets' as const},...(n.role==='merchant'?[{label:'Đan phòng',panel:'alchemy' as const}]:[])]})),
 ...ENEMIES.map(e=>({id:e.id,category:'enemy' as const,name:e.name,description:e.boss?'Ma khí hội tụ thành trấn thủ linh địa. Chuẩn bị trang bị và linh đan trước khi khiêu chiến.':e.elite?'Yêu thú đã hấp thụ ma khí, mạnh hơn đồng loại.':'Yêu thú sinh sống ở rìa phía đông linh địa.',known:(p.killCounts[e.id]||0)>0,map:e.map,art:{enemy:e.appearance},facts:[['Linh địa',MAPS[e.map].name],['Khí huyết cơ bản',String(e.maxHp)],['Công kích cơ bản',String(e.attack)],['Tu vi cơ bản',String(e.xp)],['Vị trí',`${e.x}, ${e.y}`],['Đã hạ',String(p.killCounts[e.id]||0)]] as [string,string][],links:[{label:'Nhiệm vụ trảm yêu',panel:'quests' as const},{label:'Chuẩn bị trang bị',panel:'inventory' as const}]})),
 ...WORLD_BOSSES.map((e,i)=>({id:e.id,category:'enemy' as const,name:e.name,description:'Boss thế giới có khí huyết và đóng góp dùng chung. Cần gây sát thương và nhận thưởng sau khi boss bị hạ.',known:(p.bossCounts[String(e.map)]||0)>0,map:e.map,art:{enemy:810+i},facts:[['Linh địa',MAPS[e.map].name],['Khí huyết',String(e.maxHp)],['Hồi sinh','10 phút sau khi bị hạ']] as [string,string][],links:[{label:'Khiêu chiến boss thế giới',panel:'bosses' as const},{label:'Tìm đồng đạo',panel:'party' as const}]})),
 ...MAPS.map(m=>({id:'map-'+m.id,category:'map' as const,name:m.name,description:m.description,known:p.visited.includes(m.id),map:m.id,art:{icon:'MapPin'},facts:[['Cảnh giới cần',REALMS[m.minRealm]],['NPC',NPCS.filter(n=>n.map===m.id).map(n=>n.name).join(', ')],['Tài nguyên','Linh thảo · Linh khoáng · Bia cổ'],['Cơ duyên riêng',String(SECRETS.filter(s=>s.map===m.id).length)]] as [string,string][],links:[{label:'Sơn hà đồ',panel:'maps' as const},{label:'Cơ duyên ẩn',panel:'secrets' as const}]})),
 ...RECIPES.map(r=>({id:'recipe-'+r.id,category:'item' as const,name:r.name,description:r.description,known:p.realm>=r.realm,art:{icon:'Heart'},facts:[['Mở tại',REALMS[r.realm]],['Nguyên liệu',`${r.herb} thảo · ${r.ore} khoáng · ${r.essence} tinh phách`],['Chi phí',r.cost+' '+r.currency]] as [string,string][],links:[{label:'Luyện đan',panel:'alchemy' as const}]})),
 ...SLOTS.map(s=>({id:'slot-'+s.id,category:'item' as const,name:s.name,description:'Trang bị có 8 phẩm; thuộc tính phụ thuộc bậc và phẩm. Cường hóa tối đa +10, có thể giao dịch giữa đạo hữu.',known:p.inventory.some(i=>i.slot===s.id),art:{icon:s.icon},facts:[['Đang sở hữu',String(p.inventory.filter(i=>i.slot===s.id).length)],['Nguồn','Rèn tại Hành trang hoặc chiến lợi phẩm từ yêu thú']] as [string,string][],links:[{label:'Hành trang & luyện khí',panel:'inventory' as const}]})),
 ...BOOKS.map(book=>({id:'book-'+book.id,category:'book' as const,name:book.name,description:book.description,known:p.books.includes(book.id),art:{icon:'BookOpen'},facts:[['Loại',book.kind],['Mở tại',REALMS[book.minRealm]],['Hiệu ứng',`Công +${book.bonus} · khí huyết +${book.bonus*3}`],['Giá',String(book.price)]] as [string,string][],links:[{label:'Tu học tại Tàng kinh các',panel:'library' as const}]})),
 ...['Thanh Vân Môn','Bích Lạc Cung','Thiên Cương Tông'].map((name,i)=>({id:'faction-'+i,category:'faction' as const,name,description:'Tông môn đón nhận đồng đạo. Gia nhập, cống hiến linh thạch để đổi công trạng và tu học bí tịch.',known:true,art:{icon:'Shield'},facts:[['Hoạt động','Gia nhập · cống hiến · trò chuyện tông môn']] as [string,string][],links:[{label:'Tông môn & gia tộc',panel:'guilds' as const}]})),
 ...SECRETS.map(s=>({id:s.id,category:'secret' as const,name:secretKnown(p,s.id)?s.name:'Dấu tích ở '+MAPS[s.map].name,description:secretKnown(p,s.id)?s.story:s.hint,known:secretKnown(p,s.id),map:s.map,art:{icon:'Sparkles'},facts:[['Vị trí',`${s.x}, ${s.y}`],['Trạng thái',p.claimed.includes(s.id)?'Đã lĩnh thưởng':secretKnown(p,s.id)?'Đã giải mã':'Chưa khám phá'],['Phần thưởng',`${s.essence} tinh phách · ${s.relics} cổ tịch`]] as [string,string][],links:[{label:'Theo dõi cơ duyên',panel:'secrets' as const}]})),
 ...DHARMAS.map(d=>({id:'dharma-'+d.id,category:'guide' as const,name:d.name,description:d.description,known:dharmaUnlocked(p,d),art:{dharma:d.id},facts:[['Mở tại',REALMS[d.realm]],['Bí truyền',d.quest?'Hoàn thành cơ duyên tương ứng':'Theo cảnh giới'],['Thức tỉnh','+25% sát thương trong 8 giây']] as [string,string][],links:[{label:'Pháp thân',panel:'dharma' as const},...(d.quest?[{label:'Tìm cơ duyên bí truyền',panel:'secrets' as const}]:[])]})),
 ...TUTORIAL.map(t=>({id:'guide-'+t.id,category:'guide' as const,name:t.name,description:t.description,known:p.tutorial.includes(t.id),art:{icon:'ScrollText'},facts:[['Bước tân thủ',String(t.id+1)]] as [string,string][],links:[{label:'Hướng dẫn tân thủ',panel:'tutorial' as const}]})),
 {id:'guide-meridians',category:'guide',name:'Động Khiếu · Chu Thiên',description:'Sáu nhánh kinh mạch, mỗi nhánh 18 khiếu. Điều tức và chiến đấu tích kinh nghiệm riêng; 24 khiếu mở một tuyến chủ đạo.',known:true,art:{icon:'Sparkles'},facts:[['Tổng khiếu','108'],['Tuyến chủ đạo','Kiếm Ý · Kim Thân · Tụ Linh']],links:[{label:'Khai khiếu',panel:'meridians'}]},
 ...CLASSES.map(c=>({id:'class-'+c.id,category:'guide' as const,name:c.name,description:c.description,known:p.classId===c.id,art:{icon:c.icon},facts:[['Hệ công',String(c.attack)],['Hệ khí huyết',String(c.hp)]] as [string,string][],links:[{label:'Chọn con đường tu',panel:'character' as const}]})),
];}
