import {advanceMeridian,totalMeridians,MERIDIAN_ROUTES} from './meridians';
import {db,GameError,type Session} from './database';
import {DHARMAS,dharmaUnlocked,RECIPES,COMMISSIONS,commissionProgress,currentDharma,PRACTICES} from './immortal';
import {nextXp,type Profile} from './model';
import type {ActionResult} from './actions';
import {partyAction} from './parties';
function check(ok:unknown,message:string){if(!ok)throw new GameError(message);}
export async function immortalAction(s:Session,body:any,out:ActionResult){const p=s.profile,action=body.action,now=Date.now();
 if(action==='meridian'){const result=advanceMeridian(p,String(body.id));check(result.ok,result.error);out.notice='Khai khiếu thành công · '+totalMeridians(p)+'/108 khiếu đã thông.';}
 else if(action==='meridianRoute'){check(totalMeridians(p)>=24,'Liên mạch đủ 24 khiếu để vận hành chu thiên.');check(MERIDIAN_ROUTES.some(r=>r.id===body.id),'Tuyến chu thiên không tồn tại.');p.meridianRoute=body.id;out.notice='Đã vận hành '+MERIDIAN_ROUTES.find(r=>r.id===body.id)!.name;}
 else if(action==='dharmaSelect'){const id=body.id===null?null:Number(body.id);check(id===null||id===-1||DHARMAS.some(d=>d.id===id&&dharmaUnlocked(p,d)),'Cần đủ cảnh giới và hoàn thành cơ duyên bí truyền.');p.dharmaId=id;out.notice=id===null?'Đã thu hồi pháp thân.':id===-1?'Pháp thân sẽ tự tiến hóa theo cảnh giới.':'Đã hiện '+DHARMAS[id!].name;}
 else if(action==='dharmaTrain'){check(currentDharma(p),'Đạt Trúc Cơ để thức tỉnh pháp thân.');check(p.dharmaLevel<30,'Pháp thân đã đạt 30 tầng.');const xp=40+p.dharmaLevel*20,essence=p.dharmaLevel;check(p.dharmaXp>=xp&&p.materials.essence>=essence,'Chưa đủ lĩnh ngộ hoặc tinh phách.');p.dharmaXp-=xp;p.materials.essence-=essence;p.dharmaLevel++;out.notice='Pháp thân tăng đến tầng '+p.dharmaLevel;}
 else if(action==='dharmaCast'){const d=currentDharma(p);check(d,'Pháp thân chưa thức tỉnh.');check(p.hp>0,'Hãy hồi sinh trước.');check((p.cooldowns.dharma||0)<=now,'Pháp thân đang hồi phục.');check(p.mp>=30,'Cần 30 linh lực.');p.mp-=30;p.cooldowns.dharma=now+30000;p.cooldowns.dharmaActive=now+8000;out.effect={type:'dharma',x:p.x,y:p.y};out.notice=d!.name+' · sát thương tăng 25% trong 8 giây';}
 else if(action==='alchemy'){const r=RECIPES.find(r=>r.id===body.recipe);check(r,'Đan phương không tồn tại.');check(p.realm>=r!.realm,'Cảnh giới chưa đủ lĩnh ngộ đan phương.');check(p.hp>0,'Hãy hồi sinh trước.');check(p.coins[r!.currency]>=r!.cost&&p.materials.herb>=r!.herb&&p.materials.ore>=r!.ore&&p.materials.essence>=r!.essence,'Chưa đủ nguyên liệu luyện đan.');if(r!.id==='root')check(p.rootGrade<5,'Linh căn đã đạt phẩm 5.');if(r!.id==='soul')check(currentDharma(p),'Đạt Trúc Cơ để dưỡng pháp thân.');p.coins[r!.currency]-=r!.cost;p.materials.herb-=r!.herb;p.materials.ore-=r!.ore;p.materials.essence-=r!.essence;if(r!.id==='heal')p.potions+=3;if(r!.id==='shield')p.shieldDan++;if(r!.id==='insight')p.xp+=Math.round(nextXp(p)*.4);if(r!.id==='soul')p.dharmaXp+=100;if(r!.id==='root')p.rootGrade++;out.notice='Luyện thành '+r!.name;}
 else if(action==='practice'){const key=body.kind as keyof Profile['practice'];check(PRACTICES.some(e=>e.id===key),'Không có đạo pháp này.');check(p.practice[key]<50,'Đạo pháp đã đạt 50 tầng.');const cost=20*(p.practice[key]+1);check(p.coins.stone>=cost,'Không đủ linh thạch.');p.coins.stone-=cost;p.practice[key]++;out.notice=PRACTICES.find(e=>e.id===key)!.name+' tăng đến tầng '+p.practice[key];}
 else if(action==='commission'){const c=COMMISSIONS.find(c=>c.id===body.id);check(c,'Ủy thác không tồn tại.');check(!p.daily.claimed.includes(c!.id),'Đã nhận thưởng ủy thác hôm nay.');check(commissionProgress(p,c!)>=c!.goal,'Ủy thác chưa hoàn thành.');p.daily.claimed.push(c!.id);p.coins.stone+=c!.stone;p.coins.jade+=c!.jade;p.materials.essence+=c!.essence;out.notice='Ủy thác hoàn thành · +'+c!.essence+' tinh phách';}
 else if(action==='chatChannel'){check(['world','party','sect'].includes(body.channel),'Kênh không hợp lệ.');p.chatChannel=body.channel;}
 else return partyAction(s,body,out);return true;
}
