import {worldSize,arenaEnemyPosition} from './map-layout';
import {titleUnlocked} from './titles';
import {meridianBonuses,type MeridianId,type MeridianRoute} from './meridians';
import {SECRETS,secretKnown} from './secrets';
import {currentDharma,dharmaBonus as bonusForDharma,upgrade,dailyState,type ImmortalState} from './immortal';
import {CLASSES,ROOTS,SLOTS,QUALITIES,PETS,MOUNTS,BOOKS,TITLES,MAPS,ENEMIES,WORLD_BOSSES,QUESTS,STORY_IDS,type Currency,type QuestDef} from './catalog';
export type Item={uid:string;slot:string;name:string;quality:number;rank:number;stat:number;enhance:number};
export type Companion={id:number;level:number};
export type Profile=ImmortalState & {meridians:Record<MeridianId,number>;rankingTitles?:string[];skillLevels?:number[];trackedQuestId?:string|null;storyRituals?:string[];meridianXp:number;meridianRoute:MeridianRoute;secretsFound:string[];meditations:number;raidCompletions:number;name:string;classId:string;race:number;root:number;rootGrade:number;realm:number;star:number;xp:number;mapId:number;x:number;y:number;hp:number;mp:number;coins:Record<Currency,number>;inventory:Item[];equipped:Record<string,string>;kills:number;bosses:number;questCount:number;killCounts:Record<string,number>;bossCounts:Record<string,number>;gathered:Record<string,number>;visited:number[];talked:number[];discovered:number[];accepted:string[];claimed:string[];books:number[];pets:Companion[];petId:number|null;mounts:Companion[];mountId:number|null;titleId:string;achievements:number[];tutorial:number[];bond:Record<string,number>;partner:number|null;heritage:number;relics:number;shieldDan:number;potions:number;cooldowns:Record<string,number>;encounters:Record<string,{hp:number;respawnAt:number}>;dungeon:{mapId:number;wave:number;kills:number;bossSlain?:boolean;enteredAt:number}|null;cleared:Record<string,number>;eventClaims:string[];startedAt:number;breakAttempts:number;breakSuccess:number;trials:number};
export function newProfile(old:any={}):Profile{return upgrade({meridians:{qihai:0,vessels:0,limbs:0,organs:0,mind:0,gate:0},meridianXp:0,meridianRoute:'none',secretsFound:[],meditations:0,raidCompletions:0,dharmaId:-1,dharmaLevel:1,dharmaXp:0,materials:{herb:0,ore:0,essence:0},practice:{body:0,soul:0,intent:0},daily:dailyState(),chatChannel:'world',name:old.name||'Thanh Vân',classId:'sword',race:0,root:2,rootGrade:2,realm:Math.max(0,Math.min(44,(old.level||1)-1)),star:1,xp:old.xp||0,mapId:0,x:620,y:600,hp:360,mp:180,coins:{silver:600,stone:old.stones??180,jade:10,merit:0,divine:0},inventory:[],equipped:{},kills:old.kills||0,bosses:old.bosses||0,questCount:0,killCounts:{},bossCounts:{},gathered:{},visited:[0],talked:[],discovered:[],accepted:[STORY_IDS[0]],trackedQuestId:STORY_IDS[0],storyRituals:[],claimed:[],books:[],pets:[],petId:null,mounts:[],mountId:null,titleId:'novice',achievements:[],tutorial:[],bond:{},partner:null,heritage:0,relics:0,shieldDan:2,potions:old.potions??8,cooldowns:{},encounters:{},dungeon:null,cleared:{},eventClaims:[],startedAt:Date.now(),breakAttempts:0,breakSuccess:0,trials:0});}
export function rank(p:Profile){return p.realm*10+p.star;}
export function nextXp(p:Profile){return Math.round(45+rank(p)*12+Math.pow(p.realm,1.6)*18);}
export function makeItem(slot:string,quality=0,itemRank=1,uid=crypto.randomUUID()):Item{const part=SLOTS.find(s=>s.id===slot);const stat=Math.round((12+itemRank*3)*QUALITIES[quality].mult);return{uid,slot,name:`${['Thanh Vân','Bích Lạc','Huyền Thiên','Thái Hư','Cửu Chuyển','Đại La','Thần Uy','Hỗn Nguyên'][quality]} ${part?.name||'Linh khí'}`,quality,rank:itemRank,stat,enhance:0};}
export function metric(p:Profile,type:string){return type==='kill'?p.kills:type==='visit'?p.visited.length:type==='boss'?p.bosses:type==='realm'?p.realm:type==='book'?p.books.length:type==='quest'?p.questCount:0;}
export function availableTitles(p:Profile){return TITLES.filter(t=>titleUnlocked(p,t));}
export function stats(p:Profile){upgrade(p);const meridian=meridianBonuses(p),dharma=currentDharma(p),dharmaBonus=dharma?bonusForDharma(dharma,p.dharmaLevel):0;const build=CLASSES.find(c=>c.id===p.classId)||CLASSES[0],r=rank(p),gear=Object.values(p.equipped).map(uid=>p.inventory.find(i=>i.uid===uid)).filter(Boolean) as Item[],total=gear.reduce((a,i)=>a+i.stat*(1+i.enhance*.15),0),weapons=gear.filter(i=>['weapon','artifact','instrument'].includes(i.slot)).reduce((a,i)=>a+i.stat*(1+i.enhance*.15),0),knowledge=p.books.reduce((a,id)=>a+(BOOKS[id]?.bonus||0),0),pet=p.pets.find(x=>x.id===p.petId),mount=p.mounts.find(x=>x.id===p.mountId),petBonus=pet?(PETS[pet.id].bonus*pet.level):0,mountBonus=mount?(MOUNTS[mount.id].bonus*mount.level):0,title=availableTitles(p).find(x=>x.id===p.titleId)?.bonus||0,bonus=(1+p.rootGrade*.015+p.heritage*.03+(p.partner!==null?.05:0)+dharmaBonus);const attack=Math.round(meridian.attackMult*(meridian.attack+(34*(1+r*.2)+weapons*.5+total*.06+knowledge+petBonus*.7+title)*build.attack*bonus*(1+p.practice.intent*.01)));const hp=Math.round(meridian.hpMult*(meridian.hp+(330+r*55+total*1.4+knowledge*3+petBonus*3+mountBonus*3)*build.hp*bonus*(1+p.practice.body*.012)));const mp=Math.round(meridian.mpMult*(meridian.mp+(170+r*16+knowledge*1.5)*(p.classId==='spell'?1.5:1)*(1+p.practice.soul*.01)));const defense=Math.round(meridian.defense+total*.12+r*3+(p.classId==='body'?r*4:0)),crit=Math.min(50,meridian.crit+5+p.rootGrade+p.practice.soul*.2+(p.classId==='fist'?10:0));return{attack,hp,mp,defense,crit,speed:meridian.speed+(mount?260+mount.level*3:195),power:Math.round(attack*8+hp*.75+mp*.6+defense*5+title*8+mountBonus*4)};}
export function successChance(p:Profile){return Math.max(.28,Math.min(.97,.93-p.realm*.011-(p.star===10?.13:0)+p.rootGrade*.015));}
export function tideActive(now:number){return Math.floor(now/1000)%600<180;}
export function insightActive(now:number){return Math.floor(now/1000)%900<240;}
export function enemiesFor(p:Profile,now=Date.now()){return ENEMIES.filter(e=>e.map===p.mapId&&(!p.dungeon||!e.spawnOf)&&(p.mapId!==0||p.dungeon||p.claimed.includes(STORY_IDS[4])||(p.claimed.includes(STORY_IDS[3])?(!e.spawnOf&&(e.index<3||e.boss)):p.claimed.includes(STORY_IDS[2])&&!e.spawnOf&&e.index<3))).map(e=>{const state=p.encounters[e.id],dead=state&&state.hp<=0&&state.respawnAt>now;const dungeonMult=p.dungeon?1+p.dungeon.wave*.25:1;return{...e,...(p.dungeon?arenaEnemyPosition(e.index):{}),attack:Math.round(e.attack*(tideActive(now)?1.15:1)),maxHp:Math.round(e.maxHp*dungeonMult),hp:dead?0:state&&state.hp>0?state.hp:Math.round(e.maxHp*dungeonMult),respawnAt:dead?state.respawnAt:0};});}
export function questProgress(p:Profile,q:QuestDef){if(q.type==='ritual')return p.storyRituals?.includes(q.target)?1:0;if(q.type==='secret')return secretKnown(p,q.target)?1:0;if(q.type==='kill')return p.killCounts[q.target]||0;if(q.type==='boss')return p.bossCounts[q.target]||0;if(q.type==='gather')return p.gathered[q.target]||0;if(q.type==='talk')return p.talked.includes(Number(q.target))?1:0;if(q.type==='visit')return p.visited.includes(q.map)?1:0;if(q.type==='dungeon')return p.cleared[q.target]||0;return p.discovered.includes(q.map)?1:0;}
export function resourceNodes(mapId:number){return [{id:0,x:620,y:690,label:'Thanh Tâm Thảo',type:'herb'},{id:1,x:720,y:460,label:'Linh khoáng',type:'ore'},{id:2,x:540,y:610,label:'Bia cổ',type:'hidden'}].map(n=>({...n,x:n.x+(mapId%3)*20,y:n.y+(mapId%2)*10})).concat(mapId===0?[{id:3,x:680,y:600,label:'Tụ Linh Đài',type:'ritual'}]:[]).concat(SECRETS.filter(s=>s.map===mapId).map(s=>({id:100+SECRETS.indexOf(s),x:s.x,y:s.y,label:'Dấu tích cơ duyên',type:'secret'})));}
export const CLASS_SKILLS:Record<string,string[]>={sword:['Thanh Vân Kiếm','Băng Liên Trận','Thiên Lôi Quyết','Vạn Kiếm Quy Tông'],body:['Bất Diệt Chưởng','Kim Thân Trận','Thiên Cương Nộ','Bất Diệt Pháp Thân'],fist:['Băng Sơn Quyền','Phá Không Kình','Long Hổ Quyền','Vạn Tượng Băng Thiên'],spell:['Hỏa Linh Chú','Băng Liên Trận','Cửu Thiên Lôi','Thiên Địa Pháp Tướng'],spear:['Lạc Vân Thương','Băng Vũ Thương','Lôi Long Thương','Bách Điểu Triều Phượng'],healer:['Thanh Mộc Chú','Liên Hoa Trận','Linh Quang Pháp','Vạn Mộc Hồi Xuân']};
export const SKILLS=[{cost:0,cd:650,range:190,mult:1,color:'#d5ecea'},{cost:25,cd:5000,range:260,mult:1.8,color:'#7fd7ee'},{cost:45,cd:8000,range:300,mult:3,color:'#b899ee'},{cost:70,cd:14000,range:340,mult:4.7,color:'#e6c177'}];
export const safePosition=(x:number,y:number,arena=false)=>{const size=worldSize(arena);return{x:Math.max(arena?300:120,Math.min(size.width-(arena?306:120),x)),y:Math.max(arena?350:180,Math.min(size.height-(arena?204:120),y))};};
