import {db,GameError,type Session} from './database';
import {MAPS} from './catalog';
import {stats,type Profile} from './model';
import type {ActionResult} from './actions';
function check(ok:unknown,message:string){if(!ok)throw new GameError(message);}
export async function partyFor(owner:string){return await db().prepare('SELECT p.*,m.damage,m.reward_cycle FROM rpg_party_members m JOIN rpg_parties p ON p.id=m.party_id WHERE m.owner=?').bind(owner).first<any>();}
export async function partyView(s:Session,includeLobby=true){const party=await partyFor(s.id);let members:any[]=[];if(party){const r=await db().prepare('SELECT m.owner,m.damage,m.reward_cycle,p.name,p.realm,p.power,p.data,p.last_seen FROM rpg_party_members m JOIN rpg_profiles p ON p.id=m.owner WHERE m.party_id=? ORDER BY m.joined_at').bind(party.id).all<any>();members=r.results.map(m=>{const p=JSON.parse(m.data);return{key:m.owner.slice(-8),name:m.name,realm:m.realm,power:m.power,classId:p.classId,hp:Math.ceil(p.hp),mapId:p.mapId,damage:m.damage,rewarded:m.reward_cycle===party.cycle,online:m.last_seen>Date.now()-25000,me:m.owner===s.id,leader:m.owner===party.leader};});}
 let lobby:any[]=[];if(includeLobby){const result=await db().prepare("SELECT p.id,p.code,p.name,p.map_id,COUNT(m.owner) as members FROM rpg_parties p JOIN rpg_party_members m ON m.party_id=p.id WHERE p.phase='recruiting' GROUP BY p.id HAVING COUNT(m.owner)<5 ORDER BY p.created_at DESC LIMIT 30").all<any>();lobby=result.results;}
 const raid=party&&party.phase==='active'?{id:'party-raid',name:['Hộ Cảnh Yêu Vương','Thái Cổ Long Vệ','Huyết Ma Cổ Tôn'][party.wave-1],x:950,y:570,map:party.map_id,hp:party.hp,maxHp:party.max_hp,appearance:813+party.wave,kind:0,boss:true,worldBoss:true,partyRaid:true,wave:party.wave}:null;
 return{party:party?{id:party.id,code:party.code,name:party.name,mapId:party.map_id,phase:party.phase,cycle:party.cycle,wave:party.wave,hp:party.hp,maxHp:party.max_hp,leader:party.leader===s.id,damage:party.damage,rewarded:party.reward_cycle===party.cycle,members,raid}:null,...(includeLobby?{parties:lobby}:{})};
}
export async function partyAction(s:Session,body:any,out:ActionResult){if(!String(body.action).startsWith('party'))return false;const p=s.profile,action=body.action,now=Date.now(),party=await partyFor(s.id);
 if(action==='partyCreate'){check(!party,'Hãy rời tổ đội hiện tại trước.');const name=String(body.name||'Đồng đạo vấn thiên').trim();check(name.length>=3&&name.length<=24,'Tên tổ đội từ 3 đến 24 ký tự.');const id=crypto.randomUUID(),code=crypto.randomUUID().slice(0,8).toUpperCase();out.statements.push(db().prepare('INSERT INTO rpg_parties(id,code,name,leader,map_id,created_at) VALUES(?,?,?,?,?,?)').bind(id,code,name,s.id,p.mapId,now),db().prepare('INSERT INTO rpg_party_members(owner,party_id,name,joined_at) VALUES(?,?,?,?)').bind(s.id,id,p.name,now));out.notice='Lập tổ đội · mã mời '+code;}
 else if(action==='partyJoin'){check(!party,'Đã thuộc tổ đội khác.');const target=await db().prepare("SELECT p.*,COUNT(m.owner) as members FROM rpg_parties p LEFT JOIN rpg_party_members m ON m.party_id=p.id WHERE p.code=? GROUP BY p.id").bind(String(body.code||'').trim().toUpperCase()).first<any>();check(target&&target.phase==='recruiting'&&target.members<5,'Mã không đúng, tổ đội đã đầy hoặc đang chiến đấu.');check(p.realm>=MAPS[target.map_id].minRealm,'Cảnh giới chưa đủ đến linh địa tổ đội.');const joined=await db().prepare("INSERT INTO rpg_party_members(owner,party_id,name,joined_at) SELECT ?,id,?,? FROM rpg_parties WHERE id=? AND phase='recruiting' AND (SELECT COUNT(*) FROM rpg_party_members WHERE party_id=?)<5 RETURNING owner").bind(s.id,p.name,now,target.id,target.id).first();check(joined,'Tổ đội vừa đầy hoặc đã vào cổ cảnh.');out.notice='Đã gia nhập '+target.name;}
 else if(action==='partyLeave'){check(party,'Chưa có tổ đội.');check(party.phase!=='finished'||party.reward_cycle===party.cycle||party.damage<=0,'Nhận thưởng cổ cảnh trước khi rời.');const next=await db().prepare('SELECT owner FROM rpg_party_members WHERE party_id=? AND owner!=? ORDER BY joined_at LIMIT 1').bind(party.id,s.id).first<any>();out.statements.push(db().prepare('DELETE FROM rpg_party_members WHERE owner=? AND party_id=?').bind(s.id,party.id));if(party.leader===s.id){if(next)out.statements.push(db().prepare('UPDATE rpg_parties SET leader=? WHERE id=?').bind(next.owner,party.id));else out.statements.push(db().prepare('DELETE FROM rpg_parties WHERE id=?').bind(party.id));}out.notice='Đã rời tổ đội.';}
 else if(action==='partyStart'){check(party&&party.leader===s.id,'Chỉ đội trưởng được mở cổ cảnh.');check(party.phase==='recruiting'||party.phase==='finished','Cổ cảnh đang diễn ra.');const members=await db().prepare('SELECT COUNT(*) as total,SUM(CASE WHEN damage>0 AND reward_cycle<? THEN 1 ELSE 0 END) as pending FROM rpg_party_members WHERE party_id=?').bind(party.cycle,party.id).first<any>();check(members.total>=2,'Cổ cảnh tổ đội cần ít nhất 2 đạo hữu.');check(!members.pending,'Còn thành viên chưa nhận thưởng lượt trước.');const base=Math.round(500*(1+p.realm*.6)*members.total);out.statements.push(db().prepare("UPDATE rpg_parties SET phase='active',cycle=cycle+1,wave=1,hp=?,max_hp=?,base_hp=? WHERE id=? AND phase!='active'").bind(base,base,base,party.id),db().prepare('UPDATE rpg_party_members SET damage=0 WHERE party_id=?').bind(party.id));out.notice='Cổ cảnh tổ đội đã mở · 3 đợt chiến đấu chung';}
 else if(action==='partyEnter'){check(party&&party.phase==='active','Tổ đội chưa mở cổ cảnh.');check(!p.dungeon,'Rời cổ cảnh cá nhân trước.');check(p.realm>=MAPS[party.map_id].minRealm,'Cảnh giới chưa đủ.');check(p.hp>0,'Hãy hồi sinh trước.');p.mapId=party.map_id;p.x=700;p.y=570;p.encounters={};if(!p.visited.includes(p.mapId))p.visited.push(p.mapId);out.effect={type:'travel'};out.notice='Đã đến cổ cảnh tổ đội.';}
 else if(action==='partyReward'){check(party&&party.phase==='finished','Cổ cảnh chưa hoàn thành.');check(party.damage>0,'Cần gây sát thương để nhận thưởng.');check(party.reward_cycle<party.cycle,'Đã nhận thưởng lượt này.');p.coins.stone+=180*(MAPS[party.map_id].world+1);p.coins.jade+=4;p.materials.essence+=8;p.relics+=2;p.dharmaXp+=60;p.daily.raid++;p.raidCompletions++;p.meridianXp+=25;p.xp+=Math.round(300*(1+p.realm*.3));out.statements.push(db().prepare('UPDATE rpg_party_members SET reward_cycle=? WHERE owner=? AND party_id=? AND reward_cycle<?').bind(party.cycle,s.id,party.id,party.cycle));out.notice='Cổ cảnh hợp lực hoàn thành · +4 tiên ngọc, +8 tinh phách';}
 else return false;return true;
}
export async function partyHit(s:Session,damage:number,out:ActionResult){const party=await partyFor(s.id);check(party&&party.phase==='active'&&party.hp>0,'Cổ cảnh tổ đội không còn mục tiêu.');check(s.profile.mapId===party.map_id&&!s.profile.dungeon,'Hãy đến cổ cảnh của tổ đội.');const guards="id=? AND cycle=? AND wave=? AND phase='active' AND hp>0";out.statements.push(db().prepare(`UPDATE rpg_party_members SET damage=damage+COALESCE((SELECT MIN(hp,?) FROM rpg_parties WHERE ${guards}),0) WHERE owner=? AND party_id=?`).bind(damage,party.id,party.cycle,party.wave,s.id,party.id),db().prepare(`UPDATE rpg_parties SET hp=CASE WHEN hp<=? AND wave<3 THEN CAST(base_hp*CASE WHEN wave=1 THEN 1.6 ELSE 2.6 END AS INTEGER) ELSE MAX(0,hp-?) END,max_hp=CASE WHEN hp<=? AND wave<3 THEN CAST(base_hp*CASE WHEN wave=1 THEN 1.6 ELSE 2.6 END AS INTEGER) ELSE max_hp END,phase=CASE WHEN hp<=? AND wave=3 THEN 'finished' ELSE phase END,wave=CASE WHEN hp<=? AND wave<3 THEN wave+1 ELSE wave END WHERE ${guards}`).bind(damage,damage,damage,damage,damage,party.id,party.cycle,party.wave));s.profile.hp=Math.max(0,s.profile.hp-Math.max(1,Math.round(6+MAPS[party.map_id].minRealm*10-stats(s.profile).defense*.15)));out.hits.push({id:'party-raid',x:950,y:570,damage:Math.min(damage,party.hp),crit:false});out.notice='Đồng đạo hợp lực · cổ cảnh đợt '+party.wave+'/3';}
