import {env} from 'cloudflare:workers';
import {PayOS} from '@payos/node';
import {db,GameError} from './database';
import {creditOrder} from './commerce';
import {requestOrigin} from '../request-origin';
const runtime=()=>env as unknown as Record<string,unknown>;
export const payosConfigured=()=>['PAYOS_CLIENT_ID','PAYOS_API_KEY','PAYOS_CHECKSUM_KEY'].every(k=>typeof runtime()[k]==='string'&&String(runtime()[k]).length>0);
function client(){if(!payosConfigured())throw new GameError('Chưa cấu hình payOS.');return new PayOS({clientId:String(runtime().PAYOS_CLIENT_ID),apiKey:String(runtime().PAYOS_API_KEY),checksumKey:String(runtime().PAYOS_CHECKSUM_KEY),timeout:15000,maxRetries:0});}
export async function checkout(req:Request,owner:string,id:string){const order:any=await db().prepare('SELECT * FROM rpg_payment_orders WHERE id=? AND owner=?').bind(id,owner).first();if(!order||order.method!=='payos'||order.status!=='pending')throw new GameError('Yêu cầu nạp không hợp lệ.');if(order.checkout_url)return{checkoutUrl:order.checkout_url};const origin=requestOrigin(req);if(!origin.startsWith('https://'))throw new GameError('payOS cần website HTTPS.');const provider=client();let payment;try{payment=await provider.paymentRequests.create({orderCode:order.order_code,amount:order.amount,description:'VTK '+String(order.order_code).slice(-10),returnUrl:origin+'/?payment=return',cancelUrl:origin+'/?payment=cancel'});}catch(error){let existing;try{existing=await provider.paymentRequests.get(order.order_code);}catch{throw error;}if(existing.orderCode!==order.order_code||existing.amount!==order.amount||!['PENDING','PAID'].includes(existing.status)||!existing.id)throw error;payment={orderCode:existing.orderCode,amount:existing.amount,paymentLinkId:existing.id,checkoutUrl:'https://pay.payos.vn/web/'+encodeURIComponent(existing.id)};}if(payment.amount!==order.amount||payment.orderCode!==order.order_code)throw new Error('PAYMENT_RESPONSE_MISMATCH');const url=new URL(payment.checkoutUrl);if(url.protocol!=='https:'||!['pay.payos.vn','checkout.payos.vn'].includes(url.hostname))throw new Error('PAYMENT_URL_INVALID');await db().prepare("UPDATE rpg_payment_orders SET checkout_url=?,payment_link_id=? WHERE id=? AND status='pending'").bind(url.toString(),payment.paymentLinkId,id).run();return{checkoutUrl:url.toString()};}
export async function paymentWebhook(body:any){let data;try{data=await client().webhooks.verify(body);}catch{throw new GameError('Chữ ký thanh toán không hợp lệ.');}if(data.code!=='00')return{received:true,credited:false};const order:any=await db().prepare('SELECT * FROM rpg_payment_orders WHERE order_code=?').bind(data.orderCode).first();if(!order)return{received:true,credited:false};if(order.method!=='payos'||data.amount!==order.amount||data.currency!=='VND'||!order.payment_link_id||data.paymentLinkId!==order.payment_link_id||typeof data.reference!=='string'||!data.reference||data.reference.length>120)throw new GameError('Nội dung thanh toán không khớp yêu cầu.');const result=await creditOrder(order.id,'payos','payos:'+data.reference,'payOS xác nhận giao dịch');return{received:true,credited:true,...result};}
