export const RANKING_BOARDS=[
 {id:'cultivation',name:'Tu vi',label:'Tu vi tích lũy',order:"realm DESC,CAST(json_extract(data,'$.star') AS INTEGER) DESC,CAST(json_extract(data,'$.xp') AS INTEGER) DESC",value:"COALESCE(json_extract(data,'$.xp'),0)",eligible:'1=1',titles:['Tu Vi Đệ Nhất Nhân','Tinh Hà Kỳ Nhân','Khổ Tu Danh Sĩ']},
 {id:'power',name:'Lực chiến',label:'Lực chiến',order:'power DESC',value:'power',eligible:'power>0',titles:['Thiên Hạ Vô Song','Vô Song Chiến Tướng','Anh Hùng Cái Thế']},
 {id:'kills',name:'Trảm yêu',label:'Yêu thú đã hạ',order:"COALESCE(json_extract(data,'$.kills'),0) DESC",value:"COALESCE(json_extract(data,'$.kills'),0)",eligible:"COALESCE(json_extract(data,'$.kills'),0)>0",titles:['Vạn Yêu Kiếm Đế','Trảm Yêu Thiên Quân','Phá Tà Kiếm Sĩ']},
 {id:'bosses',name:'Săn boss',label:'Boss đã hạ',order:"COALESCE(json_extract(data,'$.bosses'),0) DESC",value:"COALESCE(json_extract(data,'$.bosses'),0)",eligible:"COALESCE(json_extract(data,'$.bosses'),0)>0",titles:['Chư Thiên Trấn Ma','Yêu Vương Khắc Tinh','Trấn Sơn Dũng Sĩ']},
 {id:'quests',name:'Tiên lộ',label:'Nhiệm vụ hoàn thành',order:"COALESCE(json_extract(data,'$.questCount'),0) DESC",value:"COALESCE(json_extract(data,'$.questCount'),0)",eligible:"COALESCE(json_extract(data,'$.questCount'),0)>0",titles:['Thiên Mệnh Chấp Chưởng','Vạn Duyên Hành Giả','Hiệp Cốt Tiên Tâm Vương']},
 {id:'secrets',name:'Thiên cơ',label:'Cơ duyên giải mã',order:"COALESCE(json_array_length(json_extract(data,'$.secretsFound')),0) DESC",value:"COALESCE(json_array_length(json_extract(data,'$.secretsFound')),0)",eligible:"COALESCE(json_array_length(json_extract(data,'$.secretsFound')),0)>0",titles:['Thiên Cơ Đệ Nhất Sứ','Huyền Cơ Tri Mệnh','Cổ Tích Tầm Chân Vương']},
 {id:'meridians',name:'Chu thiên',label:'Khiếu đã khai',order:'(SELECT COALESCE(SUM(value),0) FROM json_each(data,\'$.meridians\')) DESC',value:"(SELECT COALESCE(SUM(value),0) FROM json_each(data,'$.meridians'))",eligible:"(SELECT COALESCE(SUM(value),0) FROM json_each(data,'$.meridians'))>0",titles:['Chu Thiên Đệ Nhất Tôn','Kinh Mạch Thông Thiên','Linh Khiếu Chân Quân']},
 {id:'raids',name:'Đồng đạo',label:'Cổ cảnh tổ đội đã vượt',order:"COALESCE(json_extract(data,'$.raidCompletions'),0) DESC",value:"COALESCE(json_extract(data,'$.raidCompletions'),0)",eligible:"COALESCE(json_extract(data,'$.raidCompletions'),0)>0",titles:['Đồng Tâm Tiên Đế','Cổ Cảnh Phá Trận Vương','Đồng Đạo Hộ Pháp']}
] as const;
export const rankingTitleId=(board:string,place:number)=>`rank-${board}-${place}`;
