import type {Profile} from './model';
export type SecretDef={id:string;map:number;name:string;hint:string;story:string;x:number;y:number;realm:number;goal:number;metric:'meditate'|'herb'|'ore'|'kill'|'boss'|'visit'|'book'|'raid'|'story';stone:number;essence:number;relics:number};
export const SECRETS:SecretDef[]=[
 {id:'s-cloud',map:0,name:'Tiếng chuông không người',hint:'Sau ba lần điều tức, hãy tìm chuông cổ phía tây sân môn.',story:'Chuông ngân dù không ai chạm. Tàn niệm tổ sư truyền cho bạn Thanh Vân Hộ Đạo: kiếm chỉ được rút để bảo vệ sinh linh.',x:460,y:450,realm:0,metric:'meditate',goal:3,stone:80,essence:3,relics:1},
 {id:'s-lotus',map:0,name:'Hoa nở trong tro tàn',hint:'Mang năm nhánh linh thảo đến hoa sen bên vườn thuốc.',story:'Linh Nhi từng giữ một hạt sen sau đại hỏa. Linh khí từ thảo đánh thức hạt giống; Bích Liên Y Tướng lại trở về nhân gian.',x:600,y:830,realm:0,metric:'herb',goal:5,stone:90,essence:4,relics:1},
 {id:'s-jade',map:0,name:'Mảnh ngọc thứ hai',hint:'Khi phong ấn Thanh Vân hồi sinh, xem lại ngọc đài bên bia cổ.',story:'Hai mảnh ngọc hợp lại thành bản đồ sao. Có một người đang chờ bạn ở Trúc Lâm Sơn; tiên lộ chưa dừng ở cổng môn.',x:440,y:640,realm:0,metric:'story',goal:1,stone:120,essence:5,relics:3},
 {id:'s-bamboo',map:1,name:'Người thổi tiêu trong trúc',hint:'Hái tám nhánh thảo ở Trúc Lâm rồi tìm chiếc tiêu cạnh đường tây.',story:'Ẩn sĩ không hỏi cảnh giới, chỉ hỏi bạn còn nghe tiếng gió không. Một khúc tiêu gọi Phong Trúc Linh Tướng che chở người lữ hành.',x:470,y:570,realm:0,metric:'herb',goal:8,stone:120,essence:4,relics:2},
 {id:'s-well',map:2,name:'Giếng soi tiền kiếp',hint:'Khám phá ba linh địa rồi nhìn xuống giếng làng.',story:'Mặt nước phản chiếu một Thanh Vân Môn trước chiến loạn. Bạn nhận ra người giữ giếng là người từng cứu mình; ký ức hóa thành mảnh cổ tịch.',x:650,y:820,realm:1,metric:'visit',goal:3,stone:150,essence:5,relics:3},
 {id:'s-wolf',map:3,name:'Lời hứa với sói trắng',hint:'Diệt mười hai yêu thú ở Hắc Phong Cốc, tìm dấu chân bên vách đá.',story:'Bạch Lang bảo vệ đàn con khỏi ma khí. Nó trao một tia hồn quang cho người không bỏ chạy: Bạch Lang Nguyệt Tướng.',x:480,y:730,realm:2,metric:'kill',goal:12,stone:180,essence:6,relics:2},
 {id:'s-frost',map:4,name:'Đèn dưới hàn đàm',hint:'Tìm sáu linh khoáng ở Hàn Đàm, rồi chạm ngọn đèn phía nam.',story:'Ngọn đèn giữ lời hẹn của một đôi đạo lữ ngàn năm. Huyền Băng Kính Tướng ngưng tụ, nhắc bạn đừng đánh mất những người đi cùng.',x:700,y:850,realm:3,metric:'ore',goal:6,stone:200,essence:7,relics:3},
 {id:'s-deer',map:6,name:'Bạch lộc dẫn đường',hint:'Đã đọc hai bí tịch? Tìm chuông bạc ở Bạch Lộc Lâm.',story:'Bạch lộc bước ra khỏi sương, dẫn bạn tới thư khố bị lãng quên. Tri thức cứu một ngôi làng mà kiếm lực không thể cứu.',x:500,y:800,realm:5,metric:'book',goal:2,stone:230,essence:8,relics:4},
 {id:'s-sword',map:7,name:'Kiếm không tên',hint:'Hạ trấn thủ Cổ Kiếm Trủng rồi tìm thanh kiếm cạnh mộ tây.',story:'Chủ kiếm đã quên tên mình nhưng vẫn nhớ lời thề hộ thế. Vạn Kiếm Cổ Hồn trao cho bạn ý chí của những kiếm tu đã khuất.',x:470,y:620,realm:5,metric:'boss',goal:1,stone:260,essence:9,relics:4},
 {id:'s-stars',map:13,name:'Sao rơi vào lòng hồ',hint:'Khám phá mười linh địa rồi tìm tinh bàn ở Lạc Tinh Hồ.',story:'Một tinh tú đã rơi để đổi lấy bình minh. Tinh Hà Pháp Tướng gửi ánh sáng ấy vào đạo tâm của người còn muốn bước tiếp.',x:680,y:810,realm:10,metric:'visit',goal:10,stone:320,essence:10,relics:5},
 {id:'s-team',map:18,name:'Lời thề đồng đạo',hint:'Hoàn thành một cổ cảnh tổ đội rồi tìm bia minh ước ở Vân Hải Tiên Môn.',story:'Không ai một mình vượt hết tiên lộ. Những dấu tay trên bia sáng lên thành Đồng Tâm Hộ Pháp, ghi nhớ đồng đạo đã kề vai chiến đấu.',x:480,y:550,realm:15,metric:'raid',goal:1,stone:400,essence:12,relics:5},
 {id:'s-origin',map:36,name:'Hạt giống trước sáng thế',hint:'Đọc mười hai bí tịch trước khi chạm hạt giống ở Thần Khải Điện.',story:'Trước khi có thần vị, chỉ có một hạt giống và một người chăm sóc. Đại Đạo Sinh Liên truyền lại điều giản dị: sức mạnh là để gìn giữ.',x:610,y:820,realm:30,metric:'book',goal:12,stone:600,essence:18,relics:8},
];
export function secretProgress(p:Profile,s:SecretDef){switch(s.metric){case 'meditate':return p.meditations||0;case 'herb':return p.gathered[`${s.map}:herb`]||0;case 'ore':return p.gathered[`${s.map}:ore`]||0;case 'kill':return Object.entries(p.killCounts).filter(([id])=>id.startsWith(`m${s.map}-`)).reduce((n,[,count])=>n+count,0);case 'boss':return p.bossCounts[String(s.map)]||0;case 'visit':return p.visited.length;case 'book':return p.books.length;case 'raid':return p.raidCompletions||0;case 'story':return p.claimed.includes('q0-10')?1:0;}}
export function secretKnown(p:Profile,id:string){return (p.secretsFound||[]).includes(id);}
