import {RANKING_BOARDS,rankingTitleId} from './ranking-defs';
import type {Profile} from './model';
export type TitleMetric='kill'|'boss'|'visit'|'book'|'realm'|'quest'|'meditate'|'secret'|'raid'|'gather'|'meridian';
export type TitleEffect='mist'|'swords'|'flame'|'stars'|'lotus'|'lightning';
export type TitleDef={id:string;name:string;requirement:number;type:TitleMetric;bonus:number;effect:TitleEffect;color:string;tier:number;group:string;ranking?:{board:string;place:number}};
export const TITLE_METRICS:Record<TitleMetric,string>={kill:'Yêu thú đã hạ',boss:'Boss đã hạ',visit:'Linh địa đã đến',book:'Bí tịch đã học',realm:'Bậc cảnh giới',quest:'Nhiệm vụ hoàn thành',meditate:'Lần điều tức',secret:'Cơ duyên đã giải mã',raid:'Cổ cảnh tổ đội đã vượt',gather:'Tài nguyên đã thu thập',meridian:'Khiếu đã khai'};
export const TITLE_EFFECTS:Record<TitleEffect,string>={mist:'Vân khí lưu chuyển',swords:'Kiếm quang hộ thể',flame:'Hỏa diễm vờn quanh',stars:'Tinh hà xoay chuyển',lotus:'Thanh liên nở rộ',lightning:'Lôi quang chớp sáng'};
const legacy=[
 ['novice','Nhập Đạo',1,'visit',5,'mist','#a5cbb5'],['hunter','Trảm Yêu Sĩ',20,'kill',20,'swords','#8dcce5'],['slayer','Vạn Yêu Khắc Tinh',500,'kill',100,'flame','#ee9770'],['traveler','Du Hành Tam Giới',20,'visit',50,'stars','#83dccc'],['scholar','Tàng Kinh Học Sĩ',12,'book',45,'lotus','#b8a0ed'],['hero','Ma Quân Khắc Tinh',10,'boss',70,'lightning','#eeb770'],['immortal','Tiên Lộ Vô Song',15,'realm',150,'stars','#ebcf7e'],['divinity','Thần Vực Chí Tôn',30,'realm',300,'lightning','#f39ac3']
] as const;
const paths:Array<{id:string;group:string;type:TitleMetric;effect:TitleEffect;goals:number[];names:string[]}>= [
 {id:'sword',group:'Trảm yêu',type:'kill',effect:'swords',goals:[10,50,100,200,400,800,1500,2500,4000,6500,10000,20000],names:['Sơ Thí Kiếm Phong','Thanh Phong Trảm Yêu','Bách Chiến Kiếm Khách','Kiếm Tâm Vô Úy','Linh Sơn Hộ Đạo','Huyền Kiếm Phá Tà','Thiên Kiếm Hành Giả','Vạn Kiếm Quy Tông','Kiếm Ý Thông Thiên','Nhất Kiếm Trấn Càn Khôn','Vô Cực Kiếm Thánh','Hồng Mông Kiếm Chủ']},
 {id:'boss',group:'Chinh phục',type:'boss',effect:'flame',goals:[1,3,5,15,25,50,80,120,200,350,600,1000],names:['Sơ Chiến Yêu Vương','Sơn Hà Dũng Sĩ','Phá Trận Tiên Phong','Trấn Sơn Chi Chủ','Huyết Chiến Vô Song','Bách Thú Kinh Hồn','Thần Uy Trấn Ma','Thiên Hỏa Phá Kiếp','Cửu U Bình Định','Vạn Ma Quy Phục','Chư Thiên Chiến Tôn','Bất Diệt Chiến Đế']},
 {id:'travel',group:'Du hành',type:'visit',effect:'mist',goals:[2,4,6,9,12,18,24,30,36,42,48,54],names:['Rời Núi Vấn Đạo','Trúc Lâm Lữ Khách','Linh Khê Du Tử','Cổ Lộ Tầm Tiên','Hạ Giới Hành Nhân','Phàm Trần Vạn Dặm','Vân Hải Tiên Du','Bồng Lai Khách Quý','Tam Giới Lữ Hành','Tinh Hà Vô Ngại','Thiên Ngoại Tiêu Dao','Sơn Hà Vạn Lý Chí Tôn']},
 {id:'books',group:'Tàng kinh',type:'book',effect:'stars',goals:[1,3,6,10,16,22,30,38,46,54,64,72],names:['Khai Quyển Hữu Ích','Thanh Vân Thư Sinh','Linh Văn Học Giả','Cổ Kinh Truyền Nhân','Bách Gia Thông Hiểu','Đạo Tạng Tầm Chân','Huyền Văn Đại Sư','Tinh Đồ Giải Nghĩa','Thiên Thư Chưởng Sứ','Vạn Pháp Thông Huyền','Đạo Kinh Chân Quân','Vô Tự Thiên Thư Chủ']},
 {id:'story',group:'Tiên lộ',type:'quest',effect:'lotus',goals:[1,5,15,30,60,100,160,240,350,450,550,700],names:['Một Niệm Nhập Đạo','Thanh Vân Hữu Tình','Linh Khê Ân Nhân','Cổ Lộ Giữ Lời','Hiệp Cốt Tiên Tâm','Hạ Giới Nghĩa Sĩ','Vân Hải Giải Ưu','Tiên Môn Chấp Sự','Tam Giới Hộ Sinh','Nhân Quả Thông Minh','Thiên Mệnh Hành Giả','Vạn Duyên Quy Đạo']},
 {id:'meditation',group:'Đạo tâm',type:'meditate',effect:'mist',goals:[1,5,15,40,100,250,500,1000,2000,3500,6000,10000],names:['Tĩnh Tâm Nhập Định','Linh Tức Sơ Thành','Thanh Phong Dưỡng Khí','Ngưng Thần Thủ Nhất','Bách Nhật Trúc Tâm','Đạo Tâm Bất Động','Tọa Vong Sơn Hà','Thiên Nhật Tĩnh Tu','Tâm Như Minh Kính','Vạn Niệm Quy Nhất','Thái Hư Vô Trần','Vô Lượng Đạo Tâm']},
 {id:'secrets',group:'Thiên cơ',type:'secret',effect:'stars',goals:[1,2,3,4,5,6,7,8,9,10,11,12],names:['Cơ Duyên Sơ Ngộ','Vân Tích Tầm Chân','Thanh Liên Tri Kỷ','Cổ Bi Giải Ngữ','Nguyệt Ảnh Khách','Linh Mạch Tri Âm','Thiên Cơ Thám Sứ','Thất Tinh Dẫn Lộ','Bát Hoang Tầm Bí','Cửu Huyền Tri Mệnh','Thập Phương Giải Ách','Thập Nhị Thiên Cơ','Vạn Cổ Bí Cảnh Chủ']},
 {id:'raid',group:'Đồng đạo',type:'raid',effect:'lightning',goals:[1,3,7,15,30,60,100,150,220,300,400,500],names:['Đồng Đạo Sơ Kết','Tam Cửa Đồng Tâm','Thất Chiến Hữu Nghĩa','Cổ Cảnh Tiên Phong','Hợp Lực Phá Trận','Lôi Trận Hộ Đạo','Bách Chiến Đồng Minh','Tiên Môn Trụ Cột','Thiên Lôi Đồng Hành','Tam Giới Chiến Hữu','Vạn Quân Tín Nghĩa','Đồng Tâm Trấn Thiên']},
 {id:'gather',group:'Linh vật',type:'gather',effect:'lotus',goals:[5,20,50,100,200,400,800,1500,2500,4000,6500,10000],names:['Linh Thảo Tân Nhân','Sơn Lâm Dược Đồng','Thảo Mộc Tri Âm','Bách Thảo Tầm Hương','Linh Khoáng Thợ Giỏi','Dược Cốc Hành Nhân','Vạn Vật Dưỡng Linh','Thanh Liên Dược Sứ','Thiên Tài Địa Bảo','Vạn Thảo Quy Tâm','Thần Mộc Chân Nhân','Tạo Hóa Linh Vật Chủ']},
 {id:'meridian',group:'Chu thiên',type:'meridian',effect:'lightning',goals:[1,6,12,18,24,36,48,60,72,84,96,108],names:['Khí Hải Sơ Khai','Lục Khiếu Thông Linh','Thập Nhị Mạch Khởi','Nhất Mạch Viên Dung','Chu Thiên Dẫn Khí','Tam Thập Lục Huyền','Kinh Mạch Liên Hoa','Lục Thập Khí Hành','Thất Thập Nhị Địa Sát','Bát Thập Tứ Thiên Môn','Cửu Lục Thông Huyền','Bách Bát Chu Thiên Chủ']}
];
const colors:Record<string,string[]>={
 sword:['#a5cbb5','#83cce9','#a0c9ff','#64ddff','#b2f6ff'],boss:['#d1b09a','#f0ba79','#ec917d','#ff8269','#ffc887'],travel:['#a5cbb5','#7ec7c2','#8acfe8','#6fdfcb','#a8ffee'],books:['#b8bacb','#9caae8','#bda0ed','#c59bff','#e4b8ff'],story:['#cbb8bd','#dfa9cd','#e69dbb','#ff9dbe','#ffd6f2'],meditation:['#a5cbb5','#a0cadc','#b1dcdf','#8af0de','#d2fff5'],secrets:['#a6c2c8','#7cbbdf','#9caaf5','#7dccff','#b9e5ff'],raid:['#cab794','#dcc58a','#efb786','#ffc974','#ffeab8'],gather:['#abc99c','#81c99b','#9ed5ab','#77e9a0','#bcffd0'],meridian:['#bdb2d0','#9fb1f1','#b399ed','#be8dff','#dfc4ff']
};
export const TITLES:TitleDef[]=[...legacy.map(([id,name,requirement,type,bonus,effect,color])=>({id,name,requirement,type,bonus,effect,color,tier:bonus>=150?5:bonus>=70?4:bonus>=40?3:bonus>=20?2:1,group:'Truyền thống'})),...paths.flatMap(path=>path.goals.map((requirement,i)=>{const tier=Math.min(5,1+Math.floor(i*4/11));return{id:`title-${path.id}-${i+1}`,name:path.names[i],requirement,type:path.type,bonus:8+i*18,effect:path.effect,color:colors[path.id][tier-1],tier,group:path.group};}))];
TITLES.push(...RANKING_BOARDS.flatMap((b,i)=>b.titles.map((name,j)=>({id:rankingTitleId(b.id,j+1),name,requirement:1,type:'realm' as const,bonus:0,effect:(["stars","lightning","swords","flame","lotus","stars","lightning","mist"] as TitleEffect[])[i],color:j===0?['#9bcfff','#ffdc8b','#82eaff','#ff947d','#ffb2da','#a2e0ff','#c49fff','#9aeacb'][i]:['#f8d878','#add8f5','#e2ae88'][j],tier:5-j,group:'Phong Vân · '+b.name,ranking:{board:b.id,place:j+1}}))));
export function titleUnlocked(p:Profile,t:TitleDef){return t.ranking?(p.rankingTitles||[]).includes(t.id):titleProgress(p,t.type)>=t.requirement;}
export function titleProgress(p:Profile,type:TitleMetric){switch(type){case 'kill':return p.kills;case 'boss':return p.bosses;case 'visit':return p.visited.length;case 'book':return p.books.length;case 'realm':return p.realm;case 'quest':return p.questCount;case 'meditate':return p.meditations||0;case 'secret':return p.secretsFound?.length||0;case 'raid':return p.raidCompletions||0;case 'gather':return Object.values(p.gathered||{}).reduce((sum,n)=>sum+n,0);case 'meridian':return Object.values(p.meridians||{}).reduce((sum,n)=>sum+n,0);}}
export function equippedTitle(p:Profile){return TITLES.find(t=>t.id===p.titleId&&titleUnlocked(p,t));}
