import { sqliteTable, text, integer, real, index, uniqueIndex } from 'drizzle-orm/sqlite-core';
export const players = sqliteTable('players', {
 id:text('id').primaryKey(), name:text('name').notNull(), x:real('x').notNull().default(720), y:real('y').notNull().default(630),
 level:integer('level').notNull().default(1), xp:integer('xp').notNull().default(0), hp:integer('hp').notNull().default(360), mp:integer('mp').notNull().default(180), stones:integer('stones').notNull().default(100), potions:integer('potions').notNull().default(5), kills:integer('kills').notNull().default(0), bosses:integer('bosses').notNull().default(0), quest:integer('quest').notNull().default(0), equipment:integer('equipment').notNull().default(0), lastSeen:integer('last_seen').notNull().default(0), actionAt:integer('action_at').notNull().default(0), cooldowns:text('cooldowns').notNull().default('{}'),
}, t=>[index('idx_players_seen').on(t.lastSeen)]);
export const monsters=sqliteTable('monsters',{id:text('id').primaryKey(),kind:integer('kind').notNull(),x:real('x').notNull(),y:real('y').notNull(),hp:integer('hp').notNull(),maxHp:integer('max_hp').notNull(),respawnAt:integer('respawn_at').notNull().default(0)});
export const messages=sqliteTable('messages',{id:integer('id').primaryKey({autoIncrement:true}),name:text('name').notNull(),body:text('body').notNull(),createdAt:integer('created_at').notNull()},t=>[index('idx_messages_created').on(t.createdAt)]);

// Expansion tables: the existing characters remain available for migration.
export const rpgProfiles=sqliteTable('rpg_profiles',{id:text('id').primaryKey(),data:text('data').notNull(),version:integer('version').notNull().default(0),name:text('name').notNull(),power:integer('power').notNull().default(0),realm:integer('realm').notNull().default(0),mapId:integer('map_id').notNull().default(0),lastSeen:integer('last_seen').notNull().default(0),lockedUntil:integer('locked_until').notNull().default(0)},t=>[index('idx_rpg_profiles_power').on(t.power),index('idx_rpg_profiles_presence').on(t.mapId,t.lastSeen)]);
export const rpgWallets=sqliteTable('rpg_wallets',{id:text('id').primaryKey(),owner:text('owner').notNull(),currency:text('currency').notNull(),balance:integer('balance').notNull().default(0)},t=>[index('idx_rpg_wallets_owner').on(t.owner)]);
export const rpgItems=sqliteTable('rpg_items',{uid:text('uid').primaryKey(),owner:text('owner').notNull(),data:text('data').notNull(),equippedSlot:text('equipped_slot')},t=>[index('idx_rpg_items_owner').on(t.owner)]);
export const rpgListings=sqliteTable('rpg_listings',{id:text('id').primaryKey(),itemUid:text('item_uid').notNull(),owner:text('owner').notNull(),sellerName:text('seller_name').notNull(),itemData:text('item_data').notNull(),currency:text('currency').notNull(),price:integer('price').notNull(),status:text('status').notNull().default('open'),buyerId:text('buyer_id'),soldAt:integer('sold_at'),settled:integer('settled').notNull().default(0),createdAt:integer('created_at').notNull()},t=>[index('idx_rpg_listings_status').on(t.status,t.createdAt),index('idx_rpg_listings_item').on(t.itemUid,t.status)]);
export const rpgGuilds=sqliteTable('rpg_guilds',{id:text('id').primaryKey(),kind:text('kind').notNull(),name:text('name').notNull(),leader:text('leader').notNull(),treasury:integer('treasury').notNull().default(0),createdAt:integer('created_at').notNull()},t=>[index('idx_rpg_guilds_kind').on(t.kind)]);
export const rpgMembers=sqliteTable('rpg_members',{id:text('id').primaryKey(),owner:text('owner').notNull(),kind:text('kind').notNull(),guildId:text('guild_id').notNull(),contribution:integer('contribution').notNull().default(0)},t=>[index('idx_rpg_members_guild').on(t.guildId)]);
export const rpgBosses=sqliteTable('rpg_world_bosses',{id:text('id').primaryKey(),hp:integer('hp').notNull(),maxHp:integer('max_hp').notNull(),respawnAt:integer('respawn_at').notNull().default(0),cycle:integer('cycle').notNull().default(1)});
export const rpgBossDamage=sqliteTable('rpg_boss_damage',{id:text('id').primaryKey(),bossId:text('boss_id').notNull(),cycle:integer('cycle').notNull(),owner:text('owner').notNull(),damage:integer('damage').notNull().default(0),claimed:integer('claimed').notNull().default(0)},t=>[index('idx_rpg_boss_damage_owner').on(t.owner,t.claimed)]);
export const rpgMessages=sqliteTable('rpg_messages',{channel:text('channel').notNull().default('world'),scope:text('scope'),id:integer('id').primaryKey({autoIncrement:true}),owner:text('owner').notNull(),name:text('name').notNull(),mapId:integer('map_id').notNull(),body:text('body').notNull(),createdAt:integer('created_at').notNull()},t=>[index('idx_rpg_messages_map').on(t.mapId,t.createdAt)]);
export const rpgParties=sqliteTable('rpg_parties',{id:text('id').primaryKey(),code:text('code').notNull(),name:text('name').notNull(),leader:text('leader').notNull(),mapId:integer('map_id').notNull(),phase:text('phase').notNull().default('recruiting'),cycle:integer('cycle').notNull().default(0),wave:integer('wave').notNull().default(1),hp:integer('hp').notNull().default(0),maxHp:integer('max_hp').notNull().default(0),baseHp:integer('base_hp').notNull().default(0),createdAt:integer('created_at').notNull()},t=>[uniqueIndex('idx_rpg_parties_code').on(t.code),index('idx_rpg_parties_phase').on(t.phase,t.createdAt)]);
export const rpgPartyMembers=sqliteTable('rpg_party_members',{owner:text('owner').primaryKey(),partyId:text('party_id').notNull(),name:text('name').notNull(),damage:integer('damage').notNull().default(0),rewardCycle:integer('reward_cycle').notNull().default(0),joinedAt:integer('joined_at').notNull()},t=>[index('idx_rpg_party_members_party').on(t.partyId)]);
