CREATE TABLE "messages" (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"body" text NOT NULL,
	"created_at" BIGINT NOT NULL
);

CREATE INDEX "idx_messages_created" ON "messages" ("created_at");
CREATE TABLE "monsters" (
	"id" text PRIMARY KEY NOT NULL,
	"kind" BIGINT NOT NULL,
	"x" real NOT NULL,
	"y" real NOT NULL,
	"hp" BIGINT NOT NULL,
	"max_hp" BIGINT NOT NULL,
	"respawn_at" BIGINT DEFAULT 0 NOT NULL
);

CREATE TABLE "players" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"x" real DEFAULT 720 NOT NULL,
	"y" real DEFAULT 630 NOT NULL,
	"level" BIGINT DEFAULT 1 NOT NULL,
	"xp" BIGINT DEFAULT 0 NOT NULL,
	"hp" BIGINT DEFAULT 360 NOT NULL,
	"mp" BIGINT DEFAULT 180 NOT NULL,
	"stones" BIGINT DEFAULT 100 NOT NULL,
	"potions" BIGINT DEFAULT 5 NOT NULL,
	"kills" BIGINT DEFAULT 0 NOT NULL,
	"bosses" BIGINT DEFAULT 0 NOT NULL,
	"quest" BIGINT DEFAULT 0 NOT NULL,
	"equipment" BIGINT DEFAULT 0 NOT NULL,
	"last_seen" BIGINT DEFAULT 0 NOT NULL,
	"action_at" BIGINT DEFAULT 0 NOT NULL,
	"cooldowns" text DEFAULT '{}' NOT NULL
);

CREATE INDEX "idx_players_seen" ON "players" ("last_seen");
CREATE TABLE "rpg_boss_damage" (
	"id" text PRIMARY KEY NOT NULL,
	"boss_id" text NOT NULL,
	"cycle" BIGINT NOT NULL,
	"owner" text NOT NULL,
	"damage" BIGINT DEFAULT 0 NOT NULL,
	"claimed" BIGINT DEFAULT 0 NOT NULL
);

CREATE INDEX "idx_rpg_boss_damage_owner" ON "rpg_boss_damage" ("owner","claimed");
CREATE TABLE "rpg_world_bosses" (
	"id" text PRIMARY KEY NOT NULL,
	"hp" BIGINT NOT NULL,
	"max_hp" BIGINT NOT NULL,
	"respawn_at" BIGINT DEFAULT 0 NOT NULL,
	"cycle" BIGINT DEFAULT 1 NOT NULL
);

CREATE TABLE "rpg_guilds" (
	"id" text PRIMARY KEY NOT NULL,
	"kind" text NOT NULL,
	"name" text NOT NULL,
	"leader" text NOT NULL,
	"treasury" BIGINT DEFAULT 0 NOT NULL,
	"created_at" BIGINT NOT NULL
);

CREATE INDEX "idx_rpg_guilds_kind" ON "rpg_guilds" ("kind");
CREATE TABLE "rpg_items" (
	"uid" text PRIMARY KEY NOT NULL,
	"owner" text NOT NULL,
	"data" text NOT NULL,
	"equipped_slot" text
);

CREATE INDEX "idx_rpg_items_owner" ON "rpg_items" ("owner");
CREATE TABLE "rpg_listings" (
	"id" text PRIMARY KEY NOT NULL,
	"item_uid" text NOT NULL,
	"owner" text NOT NULL,
	"seller_name" text NOT NULL,
	"item_data" text NOT NULL,
	"currency" text NOT NULL,
	"price" BIGINT NOT NULL,
	"status" text DEFAULT 'open' NOT NULL,
	"buyer_id" text,
	"sold_at" BIGINT,
	"settled" BIGINT DEFAULT 0 NOT NULL,
	"created_at" BIGINT NOT NULL
);

CREATE INDEX "idx_rpg_listings_status" ON "rpg_listings" ("status","created_at");
CREATE INDEX "idx_rpg_listings_item" ON "rpg_listings" ("item_uid","status");
CREATE TABLE "rpg_members" (
	"id" text PRIMARY KEY NOT NULL,
	"owner" text NOT NULL,
	"kind" text NOT NULL,
	"guild_id" text NOT NULL,
	"contribution" BIGINT DEFAULT 0 NOT NULL
);

CREATE INDEX "idx_rpg_members_guild" ON "rpg_members" ("guild_id");
CREATE TABLE "rpg_messages" (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
	"owner" text NOT NULL,
	"name" text NOT NULL,
	"map_id" BIGINT NOT NULL,
	"body" text NOT NULL,
	"created_at" BIGINT NOT NULL
);

CREATE INDEX "idx_rpg_messages_map" ON "rpg_messages" ("map_id","created_at");
CREATE TABLE "rpg_profiles" (
	"id" text PRIMARY KEY NOT NULL,
	"data" text NOT NULL,
	"version" BIGINT DEFAULT 0 NOT NULL,
	"name" text NOT NULL,
	"power" BIGINT DEFAULT 0 NOT NULL,
	"realm" BIGINT DEFAULT 0 NOT NULL,
	"map_id" BIGINT DEFAULT 0 NOT NULL,
	"last_seen" BIGINT DEFAULT 0 NOT NULL,
	"locked_until" BIGINT DEFAULT 0 NOT NULL
);

CREATE INDEX "idx_rpg_profiles_power" ON "rpg_profiles" ("power");
CREATE INDEX "idx_rpg_profiles_presence" ON "rpg_profiles" ("map_id","last_seen");
CREATE TABLE "rpg_wallets" (
	"id" text PRIMARY KEY NOT NULL,
	"owner" text NOT NULL,
	"currency" text NOT NULL,
	"balance" BIGINT DEFAULT 0 NOT NULL
);

CREATE INDEX "idx_rpg_wallets_owner" ON "rpg_wallets" ("owner");
CREATE TABLE "rpg_parties" (
	"id" text PRIMARY KEY NOT NULL,
	"code" text NOT NULL,
	"name" text NOT NULL,
	"leader" text NOT NULL,
	"map_id" BIGINT NOT NULL,
	"phase" text DEFAULT 'recruiting' NOT NULL,
	"cycle" BIGINT DEFAULT 0 NOT NULL,
	"wave" BIGINT DEFAULT 1 NOT NULL,
	"hp" BIGINT DEFAULT 0 NOT NULL,
	"max_hp" BIGINT DEFAULT 0 NOT NULL,
	"base_hp" BIGINT DEFAULT 0 NOT NULL,
	"created_at" BIGINT NOT NULL
);

CREATE UNIQUE INDEX "idx_rpg_parties_code" ON "rpg_parties" ("code");
CREATE INDEX "idx_rpg_parties_phase" ON "rpg_parties" ("phase","created_at");
CREATE TABLE "rpg_party_members" (
	"owner" text PRIMARY KEY NOT NULL,
	"party_id" text NOT NULL,
	"name" text NOT NULL,
	"damage" BIGINT DEFAULT 0 NOT NULL,
	"reward_cycle" BIGINT DEFAULT 0 NOT NULL,
	"joined_at" BIGINT NOT NULL
);

CREATE INDEX "idx_rpg_party_members_party" ON "rpg_party_members" ("party_id");
ALTER TABLE "rpg_messages" ADD "channel" text DEFAULT 'world' NOT NULL;
ALTER TABLE "rpg_messages" ADD "scope" text;
CREATE TABLE rpg_admin_sessions (token_hash text PRIMARY KEY NOT NULL, credential_hash text NOT NULL, expires_at BIGINT NOT NULL, created_at BIGINT NOT NULL);

CREATE TABLE rpg_admin_limits (id text PRIMARY KEY NOT NULL, attempts BIGINT NOT NULL DEFAULT 0, window_at BIGINT NOT NULL);

CREATE TABLE rpg_admin_controls (owner text PRIMARY KEY NOT NULL, banned_until BIGINT NOT NULL DEFAULT 0, muted_until BIGINT NOT NULL DEFAULT 0, reason text NOT NULL DEFAULT '');

CREATE TABLE rpg_server_settings (id text PRIMARY KEY NOT NULL, data text NOT NULL);

CREATE TABLE rpg_admin_audit (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL, action text NOT NULL, target text, reason text NOT NULL, details text NOT NULL, created_at BIGINT NOT NULL);

CREATE INDEX idx_rpg_admin_audit_created ON rpg_admin_audit(created_at);
